import equational_theories.Spectrum.SmallPairs.OrderEleven.Encoding
import equational_theories.Definability.IncludeGzip
import equational_theories.Spectrum.Status

/-! Generated saved LRAT proofs. Hashes and solver timings are in
 data/spectrum/1313_order11_refutations.json. -/
namespace Spectrum.SmallPairs.OrderEleven
open Std.Sat Std.Tactic.BVDecide LRAT

private def proofs : Array (Array IntAction) := #[
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row000.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row001.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row002.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row003.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row004.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row005.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row006.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row007.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row008.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row009.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row010.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row011.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row012.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row013.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row014.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row015.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row016.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row017.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row018.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row019.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row020.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row021.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row022.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row023.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row024.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row025.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row026.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row027.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row028.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row029.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row030.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row031.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row032.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row033.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row034.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row035.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row036.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row037.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row038.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row039.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row040.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row041.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row042.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row043.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row044.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row045.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row046.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row047.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row048.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row049.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row050.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row051.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row052.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row053.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row054.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row055.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row056.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row057.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row058.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row059.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row060.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row061.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row062.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row063.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row064.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row065.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row066.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row067.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row068.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row069.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row070.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row071.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row072.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row073.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row074.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row075.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row076.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row077.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row078.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row079.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row080.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row081.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row082.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row083.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row084.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row085.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row086.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row087.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row088.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row089.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row090.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row091.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row092.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row093.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row094.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row095.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row096.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row097.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row098.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row099.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row100.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row101.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row102.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row103.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row104.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row105.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row106.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row107.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row108.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row109.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row110.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row111.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row112.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row113.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row114.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row115.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row116.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row117.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row118.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row119.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row120.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row121.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row122.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row123.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row124.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row125.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row126.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row127.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row128.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row129.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row130.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row131.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row132.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row133.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row134.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row135.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row136.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row137.lrat.gz").toUTF8).toOption.getD #[],
  (parseLRATProof (include_gzip_str "../../../../data/spectrum/1313_eleven_lrat/row138.lrat.gz").toUTF8).toOption.getD #[]]

@[spectrum_native]
theorem checked : ∀ i : Fin 139,
    check proofs[i.val]! (natFormula (row i)) = true := by
  native_decide

theorem unsat (i : Fin 139) : (natFormula (row i)).Unsat :=
  check_sound _ _ (checked i)

spectrum_assert unsat complete
end Spectrum.SmallPairs.OrderEleven
