import equational_theories.Definability.AutBox
import equational_theories.Definability.RigBox_00

/-!
# The diagonal obligation for `Equation1033`, inherited

Generated by `defwork/dfmono.py`.  `Equation1033` is `x = x ◇ ((x ◇ (y ◇ z)) ◇ z)`, which implies
`Equation308` (`x ◇ x = x ◇ (x ◇ y)`).  `AutBox.DiagFix` is antitone, so the obligation proved for the
weaker law covers the stronger one.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false
set_option maxHeartbeats 1000000

theorem DiagFix_Equation1033 : AutBox.DiagFix Law1033 := by
  refine AutBox.diagFix_mono (fun {G} M h ↦ ?_) DiagFix_Equation308
  rw [@Law308.models_iff G M]
  rw [@Law1033.models_iff G M] at h
  first
  | grind
  | grind (splits := 30) (ematch := 20)
  | (intro x y; grind (splits := 60) (ematch := 40))
