import equational_theories.Definability.AutBox
import equational_theories.Definability.CanBox_02

/-!
# Structurality from `Equation2068` through a diagonal companion, by replay

Generated by `defwork/creplay.py`.  `Equation2068` is `x = ((x ◇ y) ◇ y) ◇ (z ◇ z)`.  Each cell below is the
companion `x □ y = if x = y then d(x) else x ◇ y` satisfying one more law, and each proof is a
Vampire refutation written out one superposition step at a time -- `grind` reaches none of
this one on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation3256` from `Equation2068`: `x = ((x ◇ y) ◇ y) ◇ (z ◇ z)` ⊢ `x ◇ x = x ◇ (x ◇ (y ◇ y))`, through the
companion `x □ y = if x = y then (x ◇ (x ◇ (x ◇ x))) else x ◇ y`.  Vampire refutation replayed step by step. -/
theorem Equation3256_StructuralFromFin_Equation2068 : Law3256.StructuralFromFin Law2068 := by
  classical
  refine AutBox.structuralFromFin_diagOf ((Lf 0) ⋆ ((Lf 0) ⋆ ((Lf 0) ⋆ (Lf 0)))) DiagFix_Equation2068 (fun {G} M hM ↦ ?_)
  have hm := (@Law2068.models_iff G M).mp hM
  suffices h : ∀ N : Magma G, (∀ a b : G, a = b ∨ N.op a b = M.op a b) →
      (∀ a : G, N.op a a = (M.op a (M.op a (M.op a a)))) → @satisfies _ G N Law3256 by
    exact h _ (fun a b ↦ (eq_or_ne a b).imp id (QFOp.diagOf_ne ((Lf 0) ⋆ ((Lf 0) ⋆ ((Lf 0) ⋆ (Lf 0)))) M a b))
      (fun a ↦ by rw [QFOp.diagOf_eq ((Lf 0) ⋆ ((Lf 0) ⋆ ((Lf 0) ⋆ (Lf 0)))) M a a rfl]; simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one])
  intro N hne hdg
  rw [@Law3256.models_iff G N]
  intro x y
  by_contra nh
  have eq5 : ∀ X0 X1 X2 : G, (M.op (M.op (M.op X0 X1) X1) (M.op X2 X2)) = X0 := by
    intro X0 X1 X2
    grind
  have eq6 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ X0 = X1 := by
    intro X0 X1
    grind
  have eq7 : ∀ X0 : G, (N.op X0 X0) = (M.op X0 (M.op X0 (M.op X0 X0))) := by
    intro X0
    grind
  have eq8 : (N.op x x) ≠ (N.op x (N.op x (N.op y y))) := by grind
  clear hm hne hdg nh hM
  have eq9 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 X1) X1) = (M.op (M.op X0 (M.op X2 X2)) (M.op X3 X3)) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq5 (M.op (M.op X0 X1) X1) (M.op X2 X2) X3
       have i₂ := eq5 X0 X1 X2
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq10 : ∀ X0 X1 X2 : G, (M.op X0 (M.op X2 X2)) = (M.op X0 (M.op X1 X1)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 (M.op X0 (M.op X1 X1)) (M.op X1 X1) X2
       have i₂ := eq5 X0 (M.op X1 X1) X1
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq13 : (N.op x x) ≠ (N.op x (M.op x (N.op y y))) ∨ x = (N.op y y) := by
    first
    | (have i₁ := eq8
       have i₂ := eq6 x (N.op y y)
       grind)
    | exact superpose eq6 eq8
    | (have j1 := eq6 x (N.op y y)
       grind)
    | (have r₁ := eq8
       have r₂ := eq6 (N.op x x) (N.op x (N.op x (N.op y y)))
       grind)
    | (have r₁ := eq8
       have r₂ := eq6 (N.op x (N.op x (N.op y y))) (N.op x x)
       grind)
    | exact resolve eq8 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq32 : ∀ X0 X1 : G, (N.op X0 X0) = (M.op X0 (M.op X0 (M.op X1 X1))) := by
    intro X0 X1
    first
    | (have i₁ := eq7 X0
       have i₂ := eq10 X0 X1 X0
       grind)
    | (have i₁ := eq7 X0
       have i₂ := eq10 X0 X0 X1
       grind)
    | exact superpose eq10 eq7
    | exact resolve eq7 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq69 : ∀ X0 X1 X2 : G, (M.op (M.op (M.op X0 (M.op X1 X1)) X2) X2) = X0 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 X0 (M.op X1 X1) x
       have i₂ := eq9 (M.op X0 (M.op X1 X1)) X2 X1 x
       grind)
    | (have i₁ := eq5 X0 (M.op X2 X2) X2
       have i₂ := eq9 (M.op X0 (M.op X2 X2)) (M.op X2 X2) X2 x
       grind)
    | exact superpose eq9 eq5
    | exact resolve eq5 eq9
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq76 : ∀ X0 X1 X2 X3 : G, (M.op X2 (M.op X3 X3)) = (M.op X2 (M.op (M.op (M.op X0 X0) X1) X1)) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq10 X2 X3 (M.op (M.op X0 X0) (M.op X0 X0))
       have i₂ := eq9 (M.op X0 X0) X1 X0 (M.op X0 X0)
       grind)
    | exact superpose eq9 eq10
    | exact resolve eq10 eq9
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq9 eq10
  have eq187 : (N.op x x) ≠ (M.op x (M.op x (N.op y y))) ∨ x = (N.op y y) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq13
       have i₂ := eq6 x (M.op x (N.op y y))
       grind)
    | exact superpose eq6 eq13
    | (have j1 := eq6 x (N.op y y)
       grind)
    | (have r₁ := eq13
       have r₂ := eq6 (N.op x x) (N.op x (M.op x (N.op y y)))
       grind)
    | (have r₁ := eq13
       have r₂ := eq6 (N.op x (M.op x (N.op y y))) (N.op x x)
       grind)
    | exact resolve eq13 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq864 : ∀ X0 X1 X2 X3 : G, (M.op X1 (M.op X2 X2)) = (M.op X1 (M.op X0 (M.op X0 (M.op X3 X3)))) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq76 (M.op X0 (M.op X3 X3)) (M.op X0 (M.op X3 X3)) X1 X2
       have i₂ := eq69 X0 X3 (M.op X0 (M.op X3 X3))
       grind)
    | exact superpose eq69 eq76
    | exact resolve eq76 eq69
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq69 eq76
  have eq1017 : ∀ X0 X1 X2 : G, (M.op X1 (M.op X2 X2)) = (M.op X1 (N.op X0 X0)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq864 X0 X1 X2 x
       have i₂ := eq32 X0 x
       grind)
    | exact superpose eq32 eq864
    | exact resolve eq864 eq32
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq864
  have eq1084 : ∀ X0 X1 : G, (N.op X0 X0) = (M.op X0 (M.op X0 (N.op X1 X1))) := by
    intro X0 X1
    first
    | (have i₁ := eq32 X0 x
       have i₂ := eq1017 X1 X0 x
       grind)
    | exact superpose eq1017 eq32
    | exact resolve eq32 eq1017
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq32
  have eq10537 : (N.op x x) ≠ (N.op x x) ∨ x = (N.op y y) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq187
       have i₂ := eq1084 x y
       grind)
    | exact superpose eq1084 eq187
    | (have r₁ := eq187
       have r₂ := eq1084 x y
       grind)
    | exact resolve eq187 eq1084
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq187
  have eq10538 : x = (M.op x (N.op y y)) ∨ x = (N.op y y) := by grind
  clear eq10537
  have eq11755 : (N.op x x) ≠ (N.op x x) ∨ x = (N.op y y) ∨ x = (N.op y y) := by
    first
    | (have i₁ := eq13
       have i₂ := eq10538
       grind)
    | exact superpose eq10538 eq13
    | exact resolve eq13 eq10538
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13 eq10538
  have eq11779 : (N.op x x) ≠ (N.op x x) ∨ x = (N.op y y) := by grind
  clear eq11755
  have eq11780 : x = (N.op y y) := by grind
  clear eq11779
  have eq12008 : (N.op x x) ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq11780
       grind)
    | exact superpose eq11780 eq8
    | exact resolve eq8 eq11780
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq12016 : ∀ X0 X1 : G, (M.op X0 (M.op X1 X1)) = (M.op X0 x) := by
    intro X0 X1
    first
    | (have i₁ := eq1017 y X0 X1
       have i₂ := eq11780
       grind)
    | exact superpose eq11780 eq1017
    | exact resolve eq1017 eq11780
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1017
  have eq12020 : ∀ X0 : G, (N.op X0 X0) = (M.op X0 (M.op X0 x)) := by
    intro X0
    first
    | (have i₁ := eq1084 X0 y
       have i₂ := eq11780
       grind)
    | exact superpose eq11780 eq1084
    | exact resolve eq1084 eq11780
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1084 eq11780
  have eq16427 : (N.op x x) = (M.op x x) := by
    first
    | (have i₁ := eq12016 x x
       have i₂ := eq12020 x
       grind)
    | exact superpose eq12020 eq12016
    | exact resolve eq12016 eq12020
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12020
  have eq17728 : (M.op x x) ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq12008
       have i₂ := eq16427
       grind)
    | exact superpose eq16427 eq12008
    | exact resolve eq12008 eq16427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12008
  have eq25064 : (M.op x x) ≠ (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq17728
       have i₂ := eq6 x (M.op x x)
       grind)
    | exact superpose eq6 eq17728
    | (have j1 := eq6 x (M.op x x)
       grind)
    | (have r₁ := eq17728
       have r₂ := eq6 (M.op x x) (N.op x (M.op x x))
       grind)
    | (have r₁ := eq17728
       have r₂ := eq6 (N.op x (M.op x x)) (M.op x x)
       grind)
    | exact resolve eq17728 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq25065 : x = (M.op x x) := by
    first
    | (have r₁ := eq25064
       have r₂ := eq12016 x x
       grind)
    | exact resolve eq25064 eq12016
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12016 eq25064
  have eq26026 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq17728
       have i₂ := eq25065
       grind)
    | exact superpose eq25065 eq17728
    | exact resolve eq17728 eq25065
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq17728
  have eq26209 : x ≠ (M.op x x) := by
    first
    | (have i₁ := eq26026
       have i₂ := eq16427
       grind)
    | exact superpose eq16427 eq26026
    | exact resolve eq26026 eq16427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq16427 eq26026
  have eq26250 : False := by grind
  exact eq26250
