import equational_theories.Definability.AutBox
import equational_theories.Definability.Gfx_01

/-!
# Structurality from `Equation1247` through a guarded box

Generated by `defwork/gcell.py`.  `Equation1247` is `x = x ◇ (((y ◇ x) ◇ z) ◇ w)`.  Its guarded obligation --
a bijection of a finite model respecting the recipe `G0V1` companion off the diagonal is an
automorphism -- is `GuardFix_G0V1_Equation1247`, proved elsewhere for the `Equation3` cell.  That
obligation names no target, so every law the companion satisfies is another cell for free, and
there are 9 of them below.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation47` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x = x ◇ (x ◇ (x ◇ x))`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation47_StructuralFromFin_Equation1247 : Law47.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law47.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation151` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x = (x ◇ x) ◇ (x ◇ x)`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation151_StructuralFromFin_Equation1247 : Law151.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law151.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation326` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x ◇ y = x ◇ (y ◇ y)`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation326_StructuralFromFin_Equation1247 : Law326.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law326.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x y
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation614` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x = x ◇ (x ◇ ((x ◇ x) ◇ x))`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation614_StructuralFromFin_Equation1247 : Law614.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law614.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation1426` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x = (x ◇ x) ◇ (x ◇ (x ◇ x))`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation1426_StructuralFromFin_Equation1247 : Law1426.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law1426.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation3715` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x ◇ y = (x ◇ x) ◇ (y ◇ y)`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation3715_StructuralFromFin_Equation1247 : Law3715.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law3715.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x y
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation3722` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x ◇ y = (x ◇ y) ◇ (x ◇ y)`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation3722_StructuralFromFin_Equation1247 : Law3722.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law3722.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x y
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation4380` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x ◇ (x ◇ x) = (x ◇ x) ◇ x`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation4380_StructuralFromFin_Equation1247 : Law4380.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law4380.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))

/-- `Equation4470` from `Equation1247`: `x = x ◇ (((y ◇ x) ◇ z) ◇ w)` ⊢ `x ◇ (y ◇ y) = (x ◇ x) ◇ y`,
through `x □ y = if x = y then x else (if Y = m(X,X) then Y else x ◇ y)`. -/
theorem Equation4470_StructuralFromFin_Equation1247 : Law4470.StructuralFromFin Law1247 := by
  classical
  refine AutBox.structuralFromFin_guardOf (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardFix_G0V1_Equation1247 (fun {G} M hM ↦ ?_)
  have hm := (@Law1247.models_iff G M).mp hM
  rw [@Law4470.models_iff G ((AutBox.boxIteD (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))).magma M)]
  intro x y
  simp only [AutBox.boxIteD_apply, evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.head_cons, Matrix.cons_val_fin_one]
  first
    | (split_ifs <;> grind)
    | (split_ifs <;> grind (splits := 30) (ematch := 20))
    | (split_ifs <;> grind (splits := 60) (ematch := 40))
