import equational_theories.Definability.AutBox
import equational_theories.Definability.Iax_04

/-!
# Structurality from `Equation1096` through a guarded companion, by replay

Generated by `defwork/itautcreplay.py`.  `Equation1096` is `x = y ◇ ((x ◇ (z ◇ y)) ◇ x)`, and the companion is
`x □ y = if m(Y,X) = Y then m(Y,Y) else m(X,Y)`.  Its automorphism half is
`GuardAut_pyx_y_pyy_pxy_Equation1096`, proved elsewhere; each cell below is one more law the
companion satisfies, written out one superposition step at a time because `grind` reaches
none of these on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation104` from `Equation1096`: `x = y ◇ ((x ◇ (z ◇ y)) ◇ x)` ⊢ `x = x ◇ ((y ◇ x) ◇ x)`, through the
companion `x □ y = if m(Y,X) = Y then m(Y,Y) else m(X,Y)`, writing `X`, `Y` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation104_StructuralFromFin_Equation1096 : Law104.StructuralFromFin Law1096 := by
  classical
  refine AutBox.structuralFromFin_iteOf ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1))
    GuardAut_pyx_y_pyy_pxy_Equation1096 (fun {G} M hM ↦ ?_)
  have hm := (@Law1096.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ b ∨ N.op a b = (M.op b b)) →
      (∀ a b : G, (M.op b a) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law104 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).imp id (fun hg ↦ if_neg hg)
  intro N ht he
  rw [@Law104.models_iff G N]
  intro x y
  by_contra nh
  have eq5 : ∀ X0 X1 X2 : G, (M.op X1 (M.op (M.op X0 (M.op X2 X1)) X0)) = X0 := by
    intro X0 X1 X2
    grind
  have eq6 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X1 ∨ (N.op X0 X1) = (M.op X1 X1) := by
    intro X0 X1
    grind
  have eq7 : ∀ X0 X1 : G, (N.op X0 X1) = (M.op X0 X1) ∨ (M.op X1 X0) = X1 := by
    intro X0 X1
    grind
  have eq8 : x ≠ (N.op x (N.op (N.op y x) x)) := by grind
  clear hm ht he nh hM
  have eq10 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq5 X1 X0 (M.op X0 (M.op x X1))
       have i₂ := eq5 X0 X1 x
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq11 : ∀ X0 X1 X2 : G, (M.op (M.op X0 (M.op X2 X1)) X0) = (M.op X1 X0) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10 X1 (M.op (M.op X0 (M.op X2 X1)) X0)
       have i₂ := eq5 X0 X1 X2
       grind)
    | exact superpose eq5 eq10
    | exact resolve eq10 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq13 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) (M.op (M.op X2 X0) X2)) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 X2 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq5
    | exact resolve eq5 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq15 : ∀ X0 X1 : G, X0 ≠ X1 ∨ (M.op X1 X1) = (N.op (M.op X1 X0) X1) := by
    intro X0 X1
    first
    | (have i₁ := eq6 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq6
    | (have j0 := eq6 (M.op X1 X0) X1
       grind)
    | (have r₁ := eq6 (M.op X1 X1) X1
       have r₂ := eq10 X1 X1
       grind)
    | exact resolve eq6 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq18 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) X1) = (M.op (M.op X2 X0) X1) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq11 X1 (M.op X2 X0) X2
       have i₂ := eq10 X2 X0
       grind)
    | exact superpose eq10 eq11
    | exact resolve eq11 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq11
  have eq26 : x ≠ (N.op x (N.op (M.op y x) x)) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 y x
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 y x
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq28 : x ≠ (M.op x (N.op (N.op y x) x)) ∨ (N.op (N.op y x) x) = (M.op (N.op (N.op y x) x) x) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 x (N.op (N.op y x) x)
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 x (N.op (N.op y x) x)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq47 : x ≠ (N.op x (M.op (M.op y x) x)) ∨ x = (M.op x y) ∨ x = (M.op x (M.op y x)) := by
    first
    | (have i₁ := eq26
       have i₂ := eq7 (M.op y x) x
       grind)
    | exact superpose eq7 eq26
    | (have j1 := eq7 y x
       grind)
    | exact resolve eq26 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq48 : x ≠ (M.op x (N.op (M.op y x) x)) ∨ x = (M.op x y) ∨ (N.op (M.op y x) x) = (M.op (N.op (M.op y x) x) x) := by
    first
    | (have i₁ := eq26
       have i₂ := eq7 x (N.op (M.op y x) x)
       grind)
    | exact superpose eq7 eq26
    | (have j1 := eq7 y x
       grind)
    | exact resolve eq26 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq49 : x ≠ (N.op x (M.op (M.op x x) x)) ∨ x = (M.op x y) ∨ x = (M.op x (M.op y x)) := by
    first
    | (have i₁ := eq47
       have i₂ := eq18 x x y
       grind)
    | exact superpose eq18 eq47
    | exact resolve eq47 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq47
  have eq58 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 X1) X2) = (M.op (M.op X3 X1) X2) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq18 X1 X2 X3
       have i₂ := eq18 X1 X2 X0
       grind)
    | (have i₁ := eq18 X0 X1 X2
       have i₂ := eq18 X0 X1 X1
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq18
  have eq358 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have j0 := eq15 X0 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15
  have eq359 : ∀ X0 : G, (N.op X0 (M.op (M.op X0 X0) X0)) = X0 := by
    intro X0
    first
    | (have i₁ := eq358 (M.op (M.op x x) x)
       have i₂ := eq13 x (M.op x x) x
       grind)
    | exact superpose eq13 eq358
    | exact resolve eq358 eq13
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13
  have eq380 : ∀ X0 X1 : G, (N.op X1 (M.op (M.op X0 X1) X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq359 X1
       have i₂ := eq58 X1 X1 X1 X0
       grind)
    | (have i₁ := eq359 X1
       have i₂ := eq58 X0 X1 X1 X1
       grind)
    | exact superpose eq58 eq359
    | exact resolve eq359 eq58
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq58
  have eq382 : x ≠ x ∨ x = (M.op x y) ∨ x = (M.op x (M.op y x)) := by
    first
    | (have i₁ := eq49
       have i₂ := eq359 x
       grind)
    | exact superpose eq359 eq49
    | (have r₁ := eq49
       have r₂ := eq359 x
       grind)
    | exact resolve eq49 eq359
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq49 eq359
  have eq384 : x = (M.op x (M.op y x)) ∨ x = (M.op x y) := by grind
  clear eq382
  have eq1137 : (M.op y x) = (M.op x x) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq10 x (M.op y x)
       have i₂ := eq384
       grind)
    | exact superpose eq384 eq10
    | exact resolve eq10 eq384
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq384
  have eq1216 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x y) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq48
       have i₂ := eq1137
       grind)
    | exact superpose eq1137 eq48
    | exact resolve eq48 eq1137
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq48
  have eq1217 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x y) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq26
       have i₂ := eq1137
       grind)
    | exact superpose eq1137 eq26
    | exact resolve eq26 eq1137
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq26 eq1137
  have eq1250 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x y) := by grind
  clear eq1217
  have eq1251 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x y) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by grind
  clear eq1216
  have eq1255 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq1250
       have i₂ := eq358 x
       grind)
    | exact superpose eq358 eq1250
    | exact resolve eq1250 eq358
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1250
  have eq1256 : x ≠ (M.op x (M.op x x)) ∨ x = (M.op x y) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1251
       have i₂ := eq358 x
       grind)
    | exact superpose eq358 eq1251
    | exact resolve eq1251 eq358
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1251
  have eq1257 : x = (M.op x y) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have r₁ := eq1256
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1256 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1256
  have eq1258 : (M.op x x) = (M.op (M.op x x) x) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq1257
       have i₂ := eq358 x
       grind)
    | exact superpose eq358 eq1257
    | exact resolve eq1257 eq358
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq358 eq1257
  have eq2437 : x = (N.op x (M.op x x)) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq380 x x
       have i₂ := eq1258
       grind)
    | exact superpose eq1258 eq380
    | exact resolve eq380 eq1258
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1258
  have eq2498 : x = (M.op x y) := by
    first
    | (have r₁ := eq2437
       have r₂ := eq1255
       grind)
    | exact resolve eq2437 eq1255
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1255 eq2437
  have eq2628 : y = (N.op y (M.op x y)) := by
    first
    | (have i₁ := eq380 x y
       have i₂ := eq2498
       grind)
    | exact superpose eq2498 eq380
    | exact resolve eq380 eq2498
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq380
  have eq2630 : y = (N.op y x) := by
    first
    | (have i₁ := eq2628
       have i₂ := eq2498
       grind)
    | exact superpose eq2498 eq2628
    | exact resolve eq2628 eq2498
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2628
  have eq2892 : x ≠ (M.op x (N.op y x)) ∨ (N.op y x) = (M.op (N.op y x) x) := by
    first
    | (have i₁ := eq28
       have i₂ := eq2630
       grind)
    | exact superpose eq2630 eq28
    | exact resolve eq28 eq2630
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq28
  have eq2894 : x ≠ (N.op x (N.op y x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq2630
       grind)
    | exact superpose eq2630 eq8
    | exact resolve eq8 eq2630
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq2896 : x ≠ (N.op x y) := by
    first
    | (have i₁ := eq2894
       have i₂ := eq2630
       grind)
    | exact superpose eq2630 eq2894
    | exact resolve eq2894 eq2630
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2894
  have eq2897 : x ≠ (M.op x y) ∨ (N.op y x) = (M.op (N.op y x) x) := by
    first
    | (have i₁ := eq2892
       have i₂ := eq2630
       grind)
    | exact superpose eq2630 eq2892
    | exact resolve eq2892 eq2630
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2892
  have eq2898 : (N.op y x) = (M.op (N.op y x) x) := by
    first
    | (have r₁ := eq2897
       have r₂ := eq2498
       grind)
    | exact resolve eq2897 eq2498
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2498 eq2897
  have eq2899 : y = (M.op y x) := by
    first
    | (have i₁ := eq2898
       have i₂ := eq2630
       grind)
    | exact superpose eq2630 eq2898
    | exact resolve eq2898 eq2630
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2630 eq2898
  have eq3086 : y ≠ y ∨ (N.op x y) = (M.op y y) := by
    first
    | (have i₁ := eq6 x y
       have i₂ := eq2899
       grind)
    | exact superpose eq2899 eq6
    | (have j0 := eq6 x y
       grind)
    | (have r₁ := eq6 x y
       have r₂ := eq2899
       grind)
    | exact resolve eq6 eq2899
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq3089 : x = (M.op y y) := by
    first
    | (have i₁ := eq10 y x
       have i₂ := eq2899
       grind)
    | exact superpose eq2899 eq10
    | exact resolve eq10 eq2899
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10 eq2899
  have eq3137 : (N.op x y) = (M.op y y) := by grind
  clear eq3086
  have eq3150 : x = (N.op x y) := by
    first
    | (have i₁ := eq3137
       have i₂ := eq3089
       grind)
    | exact superpose eq3089 eq3137
    | exact resolve eq3137 eq3089
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq3089 eq3137
  have eq3154 : False := by grind
  exact eq3154

/-- `Equation1228` from `Equation1096`: `x = y ◇ ((x ◇ (z ◇ y)) ◇ x)` ⊢ `x = x ◇ (((x ◇ y) ◇ x) ◇ x)`, through the
companion `x □ y = if m(Y,X) = Y then m(Y,Y) else m(X,Y)`, writing `X`, `Y` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation1228_StructuralFromFin_Equation1096 : Law1228.StructuralFromFin Law1096 := by
  classical
  refine AutBox.structuralFromFin_iteOf ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1))
    GuardAut_pyx_y_pyy_pxy_Equation1096 (fun {G} M hM ↦ ?_)
  have hm := (@Law1096.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ b ∨ N.op a b = (M.op b b)) →
      (∀ a b : G, (M.op b a) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law1228 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).imp id (fun hg ↦ if_neg hg)
  intro N ht he
  rw [@Law1228.models_iff G N]
  intro x y
  by_contra nh
  have eq5 : ∀ X0 X1 X2 : G, (M.op X1 (M.op (M.op X0 (M.op X2 X1)) X0)) = X0 := by
    intro X0 X1 X2
    grind
  have eq6 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X1 ∨ (N.op X0 X1) = (M.op X1 X1) := by
    intro X0 X1
    grind
  have eq7 : ∀ X0 X1 : G, (N.op X0 X1) = (M.op X0 X1) ∨ (M.op X1 X0) = X1 := by
    intro X0 X1
    grind
  have eq8 : x ≠ (N.op x (N.op (N.op (N.op x y) x) x)) := by grind
  clear hm ht he nh hM
  have eq10 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq5 X1 X0 (M.op X0 (M.op x X1))
       have i₂ := eq5 X0 X1 x
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq11 : ∀ X0 X1 X2 : G, (M.op (M.op X0 (M.op X2 X1)) X0) = (M.op X1 X0) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10 X1 (M.op (M.op X0 (M.op X2 X1)) X0)
       have i₂ := eq5 X0 X1 X2
       grind)
    | exact superpose eq5 eq10
    | exact resolve eq10 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq13 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) (M.op (M.op X2 X0) X2)) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 X2 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq5
    | exact resolve eq5 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq15 : ∀ X0 X1 : G, X0 ≠ X1 ∨ (M.op X1 X1) = (N.op (M.op X1 X0) X1) := by
    intro X0 X1
    first
    | (have i₁ := eq6 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq6
    | (have j0 := eq6 (M.op X1 X0) X1
       grind)
    | (have r₁ := eq6 (M.op X1 X1) X1
       have r₂ := eq10 X1 X1
       grind)
    | exact resolve eq6 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq18 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) X1) = (M.op (M.op X2 X0) X1) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq11 X1 (M.op X2 X0) X2
       have i₂ := eq10 X2 X0
       grind)
    | exact superpose eq10 eq11
    | exact resolve eq11 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq11
  have eq27 : x ≠ (M.op x (N.op (N.op (N.op x y) x) x)) ∨ (N.op (N.op (N.op x y) x) x) = (M.op (N.op (N.op (N.op x y) x) x) x) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 x (N.op (N.op (N.op x y) x) x)
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 x (N.op (N.op (N.op x y) x) x)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq28 : x ≠ (N.op x (N.op (M.op (N.op x y) x) x)) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 (N.op x y) x
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 (N.op x y) x
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq83 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 X1) X2) = (M.op (M.op X3 X1) X2) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq18 X1 X2 X3
       have i₂ := eq18 X1 X2 X0
       grind)
    | (have i₁ := eq18 X0 X1 X2
       have i₂ := eq18 X0 X1 X1
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq176 : x ≠ (N.op x (M.op (M.op (N.op x y) x) x)) ∨ x = (M.op x (N.op x y)) ∨ x = (M.op x (M.op (N.op x y) x)) := by
    first
    | (have i₁ := eq28
       have i₂ := eq7 (M.op (N.op x y) x) x
       grind)
    | exact superpose eq7 eq28
    | (have j1 := eq7 (N.op x y) x
       grind)
    | exact resolve eq28 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq177 : x ≠ (M.op x (N.op (M.op (N.op x y) x) x)) ∨ x = (M.op x (N.op x y)) ∨ (N.op (M.op (N.op x y) x) x) = (M.op (N.op (M.op (N.op x y) x) x) x) := by
    first
    | (have i₁ := eq28
       have i₂ := eq7 x (N.op (M.op (N.op x y) x) x)
       grind)
    | exact superpose eq7 eq28
    | (have j1 := eq7 (N.op x y) x
       grind)
    | exact resolve eq28 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq178 : x ≠ (N.op x (M.op (M.op x x) x)) ∨ x = (M.op x (N.op x y)) ∨ x = (M.op x (M.op (N.op x y) x)) := by
    first
    | (have i₁ := eq176
       have i₂ := eq18 x x (N.op x y)
       grind)
    | exact superpose eq18 eq176
    | exact resolve eq176 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq18 eq176
  have eq435 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have j0 := eq15 X0 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15
  have eq439 : ∀ X0 : G, (N.op X0 (M.op (M.op X0 X0) X0)) = X0 := by
    intro X0
    first
    | (have i₁ := eq435 (M.op (M.op x x) x)
       have i₂ := eq13 x (M.op x x) x
       grind)
    | exact superpose eq13 eq435
    | exact resolve eq435 eq13
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13
  have eq461 : ∀ X0 X1 : G, (N.op X1 (M.op (M.op X0 X1) X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq439 X1
       have i₂ := eq83 X1 X1 X1 X0
       grind)
    | (have i₁ := eq439 X1
       have i₂ := eq83 X0 X1 X1 X1
       grind)
    | exact superpose eq83 eq439
    | exact resolve eq439 eq83
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq83 eq439
  have eq497 : x ≠ x ∨ x = (M.op x (N.op x y)) ∨ x = (M.op x (M.op (N.op x y) x)) := by
    first
    | (have i₁ := eq178
       have i₂ := eq461 x x
       grind)
    | exact superpose eq461 eq178
    | (have r₁ := eq178
       have r₂ := eq461 x x
       grind)
    | exact resolve eq178 eq461
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq178
  have eq499 : x = (M.op x (M.op (N.op x y) x)) ∨ x = (M.op x (N.op x y)) := by grind
  clear eq497
  have eq840 : (M.op (N.op x y) x) = (M.op x x) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq10 x (M.op (N.op x y) x)
       have i₂ := eq499
       grind)
    | exact superpose eq499 eq10
    | exact resolve eq10 eq499
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq499
  have eq994 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op x y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq177
       have i₂ := eq840
       grind)
    | exact superpose eq840 eq177
    | exact resolve eq177 eq840
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq177
  have eq995 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op x y)) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq28
       have i₂ := eq840
       grind)
    | exact superpose eq840 eq28
    | exact resolve eq28 eq840
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq28 eq840
  have eq1023 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op x y)) := by grind
  clear eq995
  have eq1024 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op x y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by grind
  clear eq994
  have eq1028 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq1023
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1023
    | exact resolve eq1023 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1023
  have eq1029 : x ≠ (M.op x (M.op x x)) ∨ x = (M.op x (N.op x y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1024
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1024
    | exact resolve eq1024 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1024
  have eq1031 : x = (M.op x (N.op x y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have r₁ := eq1029
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1029 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1029
  have eq1032 : (M.op x x) = (M.op (M.op x x) x) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq1031
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1031
    | exact resolve eq1031 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1031
  have eq1383 : x = (N.op x (M.op x x)) ∨ x = (M.op x (N.op x y)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1032
       grind)
    | exact superpose eq1032 eq461
    | exact resolve eq461 eq1032
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1032
  have eq1424 : x = (M.op x (N.op x y)) := by
    first
    | (have r₁ := eq1383
       have r₂ := eq1028
       grind)
    | exact resolve eq1383 eq1028
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1028 eq1383
  have eq1484 : (N.op x y) = (M.op x x) := by
    first
    | (have i₁ := eq10 x (N.op x y)
       have i₂ := eq1424
       grind)
    | exact superpose eq1424 eq10
    | exact resolve eq10 eq1424
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1424
  have eq1527 : x ≠ (N.op x (N.op (N.op (M.op x x) x) x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq1484
       grind)
    | exact superpose eq1484 eq8
    | exact resolve eq8 eq1484
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1528 : x ≠ (M.op x (N.op (N.op (M.op x x) x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq27
       have i₂ := eq1484
       grind)
    | exact superpose eq1484 eq27
    | exact resolve eq27 eq1484
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq27 eq1484
  have eq1540 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1528
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1528
    | exact resolve eq1528 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1528
  have eq1541 : x ≠ (N.op x (N.op (M.op x x) x)) := by
    first
    | (have i₁ := eq1527
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1527
    | exact resolve eq1527 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1527
  have eq1543 : x ≠ (M.op x (M.op x x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1540
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1540
    | exact resolve eq1540 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1540
  have eq1544 : x ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq1541
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1541
    | exact resolve eq1541 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1541
  have eq1546 : (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have r₁ := eq1543
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1543 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10 eq1543
  have eq1547 : (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1546
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1546
    | exact resolve eq1546 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1546
  have eq1548 : (M.op x x) = (M.op (M.op x x) x) := by
    first
    | (have i₁ := eq1547
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1547
    | exact resolve eq1547 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq435 eq1547
  have eq2783 : x = (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1548
       grind)
    | exact superpose eq1548 eq461
    | exact resolve eq461 eq1548
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq461 eq1548
  have eq2841 : False := by grind
  exact eq2841

/-- `Equation1238` from `Equation1096`: `x = y ◇ ((x ◇ (z ◇ y)) ◇ x)` ⊢ `x = x ◇ (((y ◇ x) ◇ x) ◇ x)`, through the
companion `x □ y = if m(Y,X) = Y then m(Y,Y) else m(X,Y)`, writing `X`, `Y` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation1238_StructuralFromFin_Equation1096 : Law1238.StructuralFromFin Law1096 := by
  classical
  refine AutBox.structuralFromFin_iteOf ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1))
    GuardAut_pyx_y_pyy_pxy_Equation1096 (fun {G} M hM ↦ ?_)
  have hm := (@Law1096.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ b ∨ N.op a b = (M.op b b)) →
      (∀ a b : G, (M.op b a) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law1238 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).imp id (fun hg ↦ if_neg hg)
  intro N ht he
  rw [@Law1238.models_iff G N]
  intro x y
  by_contra nh
  have eq5 : ∀ X0 X1 X2 : G, (M.op X1 (M.op (M.op X0 (M.op X2 X1)) X0)) = X0 := by
    intro X0 X1 X2
    grind
  have eq6 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X1 ∨ (N.op X0 X1) = (M.op X1 X1) := by
    intro X0 X1
    grind
  have eq7 : ∀ X0 X1 : G, (N.op X0 X1) = (M.op X0 X1) ∨ (M.op X1 X0) = X1 := by
    intro X0 X1
    grind
  have eq8 : x ≠ (N.op x (N.op (N.op (N.op y x) x) x)) := by grind
  clear hm ht he nh hM
  have eq10 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq5 X1 X0 (M.op X0 (M.op x X1))
       have i₂ := eq5 X0 X1 x
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq11 : ∀ X0 X1 X2 : G, (M.op (M.op X0 (M.op X2 X1)) X0) = (M.op X1 X0) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10 X1 (M.op (M.op X0 (M.op X2 X1)) X0)
       have i₂ := eq5 X0 X1 X2
       grind)
    | exact superpose eq5 eq10
    | exact resolve eq10 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq13 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) (M.op (M.op X2 X0) X2)) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 X2 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq5
    | exact resolve eq5 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq15 : ∀ X0 X1 : G, X0 ≠ X1 ∨ (M.op X1 X1) = (N.op (M.op X1 X0) X1) := by
    intro X0 X1
    first
    | (have i₁ := eq6 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq6
    | (have j0 := eq6 (M.op X1 X0) X1
       grind)
    | (have r₁ := eq6 (M.op X1 X1) X1
       have r₂ := eq10 X1 X1
       grind)
    | exact resolve eq6 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq18 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) X1) = (M.op (M.op X2 X0) X1) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq11 X1 (M.op X2 X0) X2
       have i₂ := eq10 X2 X0
       grind)
    | exact superpose eq10 eq11
    | exact resolve eq11 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq11
  have eq27 : x ≠ (N.op x (N.op (M.op (N.op y x) x) x)) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 (N.op y x) x
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 (N.op y x) x
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq29 : x ≠ (M.op x (N.op (N.op (N.op y x) x) x)) ∨ (N.op (N.op (N.op y x) x) x) = (M.op (N.op (N.op (N.op y x) x) x) x) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 x (N.op (N.op (N.op y x) x) x)
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 x (N.op (N.op (N.op y x) x) x)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq83 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 X1) X2) = (M.op (M.op X3 X1) X2) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq18 X1 X2 X3
       have i₂ := eq18 X1 X2 X0
       grind)
    | (have i₁ := eq18 X0 X1 X2
       have i₂ := eq18 X0 X1 X1
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq176 : x ≠ (N.op x (M.op (M.op (N.op y x) x) x)) ∨ x = (M.op x (N.op y x)) ∨ x = (M.op x (M.op (N.op y x) x)) := by
    first
    | (have i₁ := eq27
       have i₂ := eq7 (M.op (N.op y x) x) x
       grind)
    | exact superpose eq7 eq27
    | (have j1 := eq7 (N.op y x) x
       grind)
    | exact resolve eq27 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq177 : x ≠ (M.op x (N.op (M.op (N.op y x) x) x)) ∨ x = (M.op x (N.op y x)) ∨ (N.op (M.op (N.op y x) x) x) = (M.op (N.op (M.op (N.op y x) x) x) x) := by
    first
    | (have i₁ := eq27
       have i₂ := eq7 x (N.op (M.op (N.op y x) x) x)
       grind)
    | exact superpose eq7 eq27
    | (have j1 := eq7 (N.op y x) x
       grind)
    | exact resolve eq27 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq178 : x ≠ (N.op x (M.op (M.op x x) x)) ∨ x = (M.op x (N.op y x)) ∨ x = (M.op x (M.op (N.op y x) x)) := by
    first
    | (have i₁ := eq176
       have i₂ := eq18 x x (N.op y x)
       grind)
    | exact superpose eq18 eq176
    | exact resolve eq176 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq18 eq176
  have eq435 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have j0 := eq15 X0 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15
  have eq439 : ∀ X0 : G, (N.op X0 (M.op (M.op X0 X0) X0)) = X0 := by
    intro X0
    first
    | (have i₁ := eq435 (M.op (M.op x x) x)
       have i₂ := eq13 x (M.op x x) x
       grind)
    | exact superpose eq13 eq435
    | exact resolve eq435 eq13
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13
  have eq461 : ∀ X0 X1 : G, (N.op X1 (M.op (M.op X0 X1) X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq439 X1
       have i₂ := eq83 X1 X1 X1 X0
       grind)
    | (have i₁ := eq439 X1
       have i₂ := eq83 X0 X1 X1 X1
       grind)
    | exact superpose eq83 eq439
    | exact resolve eq439 eq83
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq83 eq439
  have eq497 : x ≠ x ∨ x = (M.op x (N.op y x)) ∨ x = (M.op x (M.op (N.op y x) x)) := by
    first
    | (have i₁ := eq178
       have i₂ := eq461 x x
       grind)
    | exact superpose eq461 eq178
    | (have r₁ := eq178
       have r₂ := eq461 x x
       grind)
    | exact resolve eq178 eq461
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq178
  have eq499 : x = (M.op x (M.op (N.op y x) x)) ∨ x = (M.op x (N.op y x)) := by grind
  clear eq497
  have eq925 : (M.op (N.op y x) x) = (M.op x x) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq10 x (M.op (N.op y x) x)
       have i₂ := eq499
       grind)
    | exact superpose eq499 eq10
    | exact resolve eq10 eq499
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq499
  have eq996 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y x)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq177
       have i₂ := eq925
       grind)
    | exact superpose eq925 eq177
    | exact resolve eq177 eq925
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq177
  have eq997 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y x)) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq27
       have i₂ := eq925
       grind)
    | exact superpose eq925 eq27
    | exact resolve eq27 eq925
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq27 eq925
  have eq1025 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y x)) := by grind
  clear eq997
  have eq1026 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y x)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by grind
  clear eq996
  have eq1030 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq1025
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1025
    | exact resolve eq1025 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1025
  have eq1031 : x ≠ (M.op x (M.op x x)) ∨ x = (M.op x (N.op y x)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1026
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1026
    | exact resolve eq1026 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1026
  have eq1033 : x = (M.op x (N.op y x)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have r₁ := eq1031
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1031 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1031
  have eq1034 : (M.op x x) = (M.op (M.op x x) x) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq1033
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1033
    | exact resolve eq1033 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1033
  have eq1386 : x = (N.op x (M.op x x)) ∨ x = (M.op x (N.op y x)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1034
       grind)
    | exact superpose eq1034 eq461
    | exact resolve eq461 eq1034
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1034
  have eq1427 : x = (M.op x (N.op y x)) := by
    first
    | (have r₁ := eq1386
       have r₂ := eq1030
       grind)
    | exact resolve eq1386 eq1030
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1030 eq1386
  have eq1488 : (N.op y x) = (M.op x x) := by
    first
    | (have i₁ := eq10 x (N.op y x)
       have i₂ := eq1427
       grind)
    | exact superpose eq1427 eq10
    | exact resolve eq10 eq1427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1427
  have eq1527 : x ≠ (N.op x (N.op (N.op (M.op x x) x) x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq1488
       grind)
    | exact superpose eq1488 eq8
    | exact resolve eq8 eq1488
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1530 : x ≠ (M.op x (N.op (N.op (M.op x x) x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq29
       have i₂ := eq1488
       grind)
    | exact superpose eq1488 eq29
    | exact resolve eq29 eq1488
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq29 eq1488
  have eq1539 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1530
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1530
    | exact resolve eq1530 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1530
  have eq1541 : x ≠ (N.op x (N.op (M.op x x) x)) := by
    first
    | (have i₁ := eq1527
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1527
    | exact resolve eq1527 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1527
  have eq1542 : x ≠ (M.op x (M.op x x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1539
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1539
    | exact resolve eq1539 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1539
  have eq1544 : x ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq1541
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1541
    | exact resolve eq1541 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1541
  have eq1545 : (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have r₁ := eq1542
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1542 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10 eq1542
  have eq1547 : (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1545
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1545
    | exact resolve eq1545 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1545
  have eq1548 : (M.op x x) = (M.op (M.op x x) x) := by
    first
    | (have i₁ := eq1547
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1547
    | exact resolve eq1547 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq435 eq1547
  have eq1921 : x = (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1548
       grind)
    | exact superpose eq1548 eq461
    | exact resolve eq461 eq1548
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq461 eq1548
  have eq1970 : False := by grind
  exact eq1970

/-- `Equation1248` from `Equation1096`: `x = y ◇ ((x ◇ (z ◇ y)) ◇ x)` ⊢ `x = x ◇ (((y ◇ y) ◇ x) ◇ x)`, through the
companion `x □ y = if m(Y,X) = Y then m(Y,Y) else m(X,Y)`, writing `X`, `Y` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation1248_StructuralFromFin_Equation1096 : Law1248.StructuralFromFin Law1096 := by
  classical
  refine AutBox.structuralFromFin_iteOf ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1))
    GuardAut_pyx_y_pyy_pxy_Equation1096 (fun {G} M hM ↦ ?_)
  have hm := (@Law1096.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ b ∨ N.op a b = (M.op b b)) →
      (∀ a b : G, (M.op b a) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law1248 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf_apply ((Lf 1) ⋆ (Lf 0)) (Lf 1) ((Lf 1) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (b)).imp id (fun hg ↦ if_neg hg)
  intro N ht he
  rw [@Law1248.models_iff G N]
  intro x y
  by_contra nh
  have eq5 : ∀ X0 X1 X2 : G, (M.op X1 (M.op (M.op X0 (M.op X2 X1)) X0)) = X0 := by
    intro X0 X1 X2
    grind
  have eq6 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X1 ∨ (N.op X0 X1) = (M.op X1 X1) := by
    intro X0 X1
    grind
  have eq7 : ∀ X0 X1 : G, (N.op X0 X1) = (M.op X0 X1) ∨ (M.op X1 X0) = X1 := by
    intro X0 X1
    grind
  have eq8 : x ≠ (N.op x (N.op (N.op (N.op y y) x) x)) := by grind
  clear hm ht he nh hM
  have eq10 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq5 X1 X0 (M.op X0 (M.op x X1))
       have i₂ := eq5 X0 X1 x
       grind)
    | exact superpose eq5 eq5
    | exact resolve eq5 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq11 : ∀ X0 X1 X2 : G, (M.op (M.op X0 (M.op X2 X1)) X0) = (M.op X1 X0) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10 X1 (M.op (M.op X0 (M.op X2 X1)) X0)
       have i₂ := eq5 X0 X1 X2
       grind)
    | exact superpose eq5 eq10
    | exact resolve eq10 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq13 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) (M.op (M.op X2 X0) X2)) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq5 X2 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq5
    | exact resolve eq5 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq15 : ∀ X0 X1 : G, X0 ≠ X1 ∨ (M.op X1 X1) = (N.op (M.op X1 X0) X1) := by
    intro X0 X1
    first
    | (have i₁ := eq6 (M.op X1 X0) X1
       have i₂ := eq10 X1 X0
       grind)
    | exact superpose eq10 eq6
    | (have j0 := eq6 (M.op X1 X0) X1
       grind)
    | (have r₁ := eq6 (M.op X1 X1) X1
       have r₂ := eq10 X1 X1
       grind)
    | exact resolve eq6 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq18 : ∀ X0 X1 X2 : G, (M.op (M.op X1 X0) X1) = (M.op (M.op X2 X0) X1) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq11 X1 (M.op X2 X0) X2
       have i₂ := eq10 X2 X0
       grind)
    | exact superpose eq10 eq11
    | exact resolve eq11 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq11
  have eq26 : x ≠ (N.op x (N.op (M.op (N.op y y) x) x)) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 (N.op y y) x
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 (N.op y y) x
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq28 : x ≠ (M.op x (N.op (N.op (N.op y y) x) x)) ∨ (N.op (N.op (N.op y y) x) x) = (M.op (N.op (N.op (N.op y y) x) x) x) := by
    first
    | (have i₁ := eq8
       have i₂ := eq7 x (N.op (N.op (N.op y y) x) x)
       grind)
    | exact superpose eq7 eq8
    | (have j1 := eq7 x (N.op (N.op (N.op y y) x) x)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq83 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 X1) X2) = (M.op (M.op X3 X1) X2) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq18 X1 X2 X3
       have i₂ := eq18 X1 X2 X0
       grind)
    | (have i₁ := eq18 X0 X1 X2
       have i₂ := eq18 X0 X1 X1
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq176 : x ≠ (N.op x (M.op (M.op (N.op y y) x) x)) ∨ x = (M.op x (N.op y y)) ∨ x = (M.op x (M.op (N.op y y) x)) := by
    first
    | (have i₁ := eq26
       have i₂ := eq7 (M.op (N.op y y) x) x
       grind)
    | exact superpose eq7 eq26
    | (have j1 := eq7 (N.op y y) x
       grind)
    | exact resolve eq26 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq177 : x ≠ (M.op x (N.op (M.op (N.op y y) x) x)) ∨ x = (M.op x (N.op y y)) ∨ (N.op (M.op (N.op y y) x) x) = (M.op (N.op (M.op (N.op y y) x) x) x) := by
    first
    | (have i₁ := eq26
       have i₂ := eq7 x (N.op (M.op (N.op y y) x) x)
       grind)
    | exact superpose eq7 eq26
    | (have j1 := eq7 (N.op y y) x
       grind)
    | exact resolve eq26 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq178 : x ≠ (N.op x (M.op (M.op x x) x)) ∨ x = (M.op x (N.op y y)) ∨ x = (M.op x (M.op (N.op y y) x)) := by
    first
    | (have i₁ := eq176
       have i₂ := eq18 x x (N.op y y)
       grind)
    | exact superpose eq18 eq176
    | exact resolve eq176 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq18 eq176
  have eq435 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have j0 := eq15 X0 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15
  have eq439 : ∀ X0 : G, (N.op X0 (M.op (M.op X0 X0) X0)) = X0 := by
    intro X0
    first
    | (have i₁ := eq435 (M.op (M.op x x) x)
       have i₂ := eq13 x (M.op x x) x
       grind)
    | exact superpose eq13 eq435
    | exact resolve eq435 eq13
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13
  have eq461 : ∀ X0 X1 : G, (N.op X1 (M.op (M.op X0 X1) X1)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq439 X1
       have i₂ := eq83 X1 X1 X1 X0
       grind)
    | (have i₁ := eq439 X1
       have i₂ := eq83 X0 X1 X1 X1
       grind)
    | exact superpose eq83 eq439
    | exact resolve eq439 eq83
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq83 eq439
  have eq497 : x ≠ x ∨ x = (M.op x (N.op y y)) ∨ x = (M.op x (M.op (N.op y y) x)) := by
    first
    | (have i₁ := eq178
       have i₂ := eq461 x x
       grind)
    | exact superpose eq461 eq178
    | (have r₁ := eq178
       have r₂ := eq461 x x
       grind)
    | exact resolve eq178 eq461
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq178
  have eq499 : x = (M.op x (M.op (N.op y y) x)) ∨ x = (M.op x (N.op y y)) := by grind
  clear eq497
  have eq925 : (M.op (N.op y y) x) = (M.op x x) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq10 x (M.op (N.op y y) x)
       have i₂ := eq499
       grind)
    | exact superpose eq499 eq10
    | exact resolve eq10 eq499
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq499
  have eq996 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq177
       have i₂ := eq925
       grind)
    | exact superpose eq925 eq177
    | exact resolve eq177 eq925
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq177
  have eq997 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y y)) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq26
       have i₂ := eq925
       grind)
    | exact superpose eq925 eq26
    | exact resolve eq26 eq925
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq26 eq925
  have eq1025 : x ≠ (N.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y y)) := by grind
  clear eq997
  have eq1026 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ x = (M.op x (N.op y y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by grind
  clear eq996
  have eq1030 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq1025
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1025
    | exact resolve eq1025 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1025
  have eq1031 : x ≠ (M.op x (M.op x x)) ∨ x = (M.op x (N.op y y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1026
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1026
    | exact resolve eq1026 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1026
  have eq1033 : x = (M.op x (N.op y y)) ∨ (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have r₁ := eq1031
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1031 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1031
  have eq1034 : (M.op x x) = (M.op (M.op x x) x) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq1033
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1033
    | exact resolve eq1033 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1033
  have eq1384 : x = (N.op x (M.op x x)) ∨ x = (M.op x (N.op y y)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1034
       grind)
    | exact superpose eq1034 eq461
    | exact resolve eq461 eq1034
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1034
  have eq1425 : x = (M.op x (N.op y y)) := by
    first
    | (have r₁ := eq1384
       have r₂ := eq1030
       grind)
    | exact resolve eq1384 eq1030
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1030 eq1384
  have eq1485 : (N.op y y) = (M.op x x) := by
    first
    | (have i₁ := eq10 x (N.op y y)
       have i₂ := eq1425
       grind)
    | exact superpose eq1425 eq10
    | exact resolve eq10 eq1425
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1425
  have eq1524 : x ≠ (N.op x (N.op (N.op (M.op x x) x) x)) := by
    first
    | (have i₁ := eq8
       have i₂ := eq1485
       grind)
    | exact superpose eq1485 eq8
    | exact resolve eq8 eq1485
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1527 : x ≠ (M.op x (N.op (N.op (M.op x x) x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq28
       have i₂ := eq1485
       grind)
    | exact superpose eq1485 eq28
    | exact resolve eq28 eq1485
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq28 eq1485
  have eq1536 : x ≠ (M.op x (N.op (M.op x x) x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1527
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1527
    | exact resolve eq1527 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1527
  have eq1538 : x ≠ (N.op x (N.op (M.op x x) x)) := by
    first
    | (have i₁ := eq1524
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1524
    | exact resolve eq1524 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1524
  have eq1539 : x ≠ (M.op x (M.op x x)) ∨ (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have i₁ := eq1536
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1536
    | exact resolve eq1536 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1536
  have eq1541 : x ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq1538
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1538
    | exact resolve eq1538 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1538
  have eq1542 : (N.op (N.op (M.op x x) x) x) = (M.op (N.op (N.op (M.op x x) x) x) x) := by
    first
    | (have r₁ := eq1539
       have r₂ := eq10 x x
       grind)
    | exact resolve eq1539 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10 eq1539
  have eq1544 : (N.op (M.op x x) x) = (M.op (N.op (M.op x x) x) x) := by
    first
    | (have i₁ := eq1542
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1542
    | exact resolve eq1542 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1542
  have eq1545 : (M.op x x) = (M.op (M.op x x) x) := by
    first
    | (have i₁ := eq1544
       have i₂ := eq435 x
       grind)
    | exact superpose eq435 eq1544
    | exact resolve eq1544 eq435
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq435 eq1544
  have eq1915 : x = (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq461 x x
       have i₂ := eq1545
       grind)
    | exact superpose eq1545 eq461
    | exact resolve eq461 eq1545
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq461 eq1545
  have eq1964 : False := by grind
  exact eq1964
