import equational_theories.Definability.AutBox3
import equational_theories.Definability.Lw6_00

/-!
# Structurality from `Equation2702` through a three-guard companion, by replay

Generated by `defwork/itautcreplay3.py`.  `Equation2702` is `x = ((y ◇ x) ◇ (x ◇ z)) ◇ x`, and the companion is
`x □ y = if (M.op a b) = b then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op a b) then b else (M.op a b)`.  Its automorphism half is `GuardAut3_pxy_y_x_y_pxx_pxy_pxx_pxx_y_pxy_Equation2702`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches it on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation3253` from `Equation2702`: `x = ((y ◇ x) ◇ (x ◇ z)) ◇ x` ⊢ `x ◇ x = x ◇ (x ◇ (x ◇ x))`, through the
companion `x □ y = if (M.op a b) = b then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op a b) then b else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation3253_StructuralFromFin_Equation2702 : Law3253.StructuralFromFin Law2702 := by
  classical
  refine AutBox.structuralFromFin_iteOf3 ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardAut3_pxy_y_x_y_pxx_pxy_pxx_pxx_y_pxy_Equation2702 (fun {G} M hM ↦ ?_)
  have hm := (@Law2702.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op a b) = b ∨ a ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op a b) = b ∨ a = b ∨ (M.op a a) ≠ (M.op a b) ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = b ∨ a = b ∨ (M.op a a) = (M.op a b) ∨ N.op a b = (M.op a b)) →
        @satisfies _ G N Law3253 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op a b))).symm.imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_pos hg3))))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op a b))).imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_neg hg3))))
  intro N ht hu hv hw
  rw [@Law3253.models_iff G N]
  intro x
  by_contra nh
  have eq7 : ∀ X0 X1 X2 : G, (M.op (M.op (M.op X1 X0) (M.op X0 X2)) X0) = X0 := by
    intro X0 X1 X2
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (N.op X0 X1) = (M.op X0 X0) := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X0 X1) = X1 ∨ X0 ≠ X1 ∨ (N.op X0 X1) = (M.op X0 X0) := by
    intro X0 X1
    grind
  have eq11 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = (M.op X0 X0) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq12 : (N.op x x) ≠ (N.op x (N.op x (N.op x x))) := by grind
  clear hm ht hu hv hw nh hM
  have eq14 : ∀ X0 X3 : G, (M.op (M.op X0 (M.op X0 X3)) X0) = X0 := by
    intro X0 X3
    first
    | (have i₁ := eq7 X0 (M.op (M.op x X0) (M.op X0 x)) X3
       have i₂ := eq7 X0 x x
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq17 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = (M.op (M.op (M.op X0 (M.op X0 X1)) X0) (M.op X0 (M.op X0 X1))) := by
    intro X0 X1
    first
    | (have i₁ := eq14 (M.op X0 (M.op X0 X1)) X0
       have i₂ := eq14 X0 X1
       grind)
    | exact superpose eq14 eq14
    | exact resolve eq14 eq14
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq20 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) = (M.op X0 (M.op X0 (M.op X0 X1))) := by
    intro X0 X1
    first
    | (have i₁ := eq17 X0 X1
       have i₂ := eq14 X0 X1
       grind)
    | exact superpose eq14 eq17
    | exact resolve eq17 eq14
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq14 eq17
  have eq26 : (M.op x x) ≠ (N.op x (N.op x (M.op x x))) ∨ x = (M.op x x) := by grind
  have eq33 : ∀ X0 X1 : G, (M.op X0 (M.op X0 X1)) ≠ (M.op X0 (M.op X0 X1)) ∨ (M.op X0 X0) = (N.op X0 (M.op X0 (M.op X0 X1))) := by
    intro X0 X1
    first
    | (have i₁ := eq8 X0 (M.op X0 (M.op X0 X1))
       have i₂ := eq20 X0 X1
       grind)
    | exact superpose eq20 eq8
    | (have j0 := eq8 X0 (M.op X0 (M.op X0 X1))
       grind)
    | (have r₁ := eq8 X0 (M.op X0 (M.op X0 X1))
       have r₂ := eq20 X0 X1
       grind)
    | exact resolve eq8 eq20
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq20
  have eq37 : ∀ X0 X1 : G, (M.op X0 X0) = (N.op X0 (M.op X0 (M.op X0 X1))) := by
    intro X0 X1
    first
    | (have j0 := eq33 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq33
  have eq75 : (M.op x x) ≠ (N.op x (M.op x (M.op x x))) ∨ x = (M.op x x) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) ∨ (M.op x x) = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq26
       have i₂ := eq11 x (M.op x x)
       grind)
    | exact superpose eq11 eq26
    | (have j1 := eq11 x (M.op x x)
       grind)
    | (have r₁ := eq26
       have r₂ := eq11 (M.op x x) (N.op x (N.op x (M.op x x)))
       grind)
    | (have r₁ := eq26
       have r₂ := eq11 (N.op x (N.op x (M.op x x))) (M.op x x)
       grind)
    | exact resolve eq26 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq77 : (M.op x x) ≠ (N.op x (M.op x (M.op x x))) ∨ x = (M.op x x) ∨ (M.op x x) = (M.op x (M.op x x)) := by grind
  clear eq75
  have eq78 : (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have r₁ := eq77
       have r₂ := eq37 x x
       grind)
    | exact resolve eq77 eq37
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq37 eq77
  have eq84 : (M.op x x) ≠ (M.op x x) ∨ (M.op x x) = (N.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq8 x (M.op x x)
       have i₂ := eq78
       grind)
    | exact superpose eq78 eq8
    | (have j0 := eq8 x (M.op x x)
       grind)
    | (have r₁ := eq8 x (M.op x x)
       have r₂ := eq78
       grind)
    | (have r₁ := eq8 x x
       have r₂ := eq78
       grind)
    | exact resolve eq8 eq78
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq78
  have eq88 : (M.op x x) = (N.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq84
  have eq108 : (M.op x x) ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq26
       have i₂ := eq88
       grind)
    | exact superpose eq88 eq26
    | exact resolve eq26 eq88
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq26
  have eq111 : (M.op x x) ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq108
  have eq114 : x = (M.op x x) := by
    first
    | (have r₁ := eq111
       have r₂ := eq88
       grind)
    | exact resolve eq111 eq88
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq88 eq111
  have eq119 : x ≠ x ∨ x = (N.op x x) := by
    first
    | (have i₁ := eq8 x x
       have i₂ := eq114
       grind)
    | exact superpose eq114 eq8
    | (have r₁ := eq8 x x
       have r₂ := eq114
       grind)
    | exact resolve eq8 eq114
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq114
  have eq126 : x = (N.op x x) := by grind
  clear eq119
  have eq164 : x ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq12
       have i₂ := eq126
       grind)
    | exact superpose eq126 eq12
    | exact resolve eq12 eq126
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq168 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq164
       have i₂ := eq126
       grind)
    | exact superpose eq126 eq164
    | exact resolve eq164 eq126
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq164
  have eq169 : False := by grind
  exact eq169
