import equational_theories.Definability.AutBox3
import equational_theories.Definability.Lw6_00

/-!
# Structurality from `Equation3886` through a three-guard companion, by replay

Generated by `defwork/itautcreplay3.py`.  `Equation3886` is `x ◇ x = (y ◇ (x ◇ z)) ◇ w`, and the companion is
`x □ y = if (M.op b a) = a then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op b a) then a else (M.op b a)`.  Its automorphism half is `GuardAut3_pyx_x_x_y_pxx_pyx_pxx_pxx_x_pyx_Equation3886`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches it on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation107` from `Equation3886`: `x ◇ x = (y ◇ (x ◇ z)) ◇ w` ⊢ `x = x ◇ ((y ◇ y) ◇ x)`, through the
companion `x □ y = if (M.op b a) = a then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op b a) then a else (M.op b a)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation107_StructuralFromFin_Equation3886 : Law107.StructuralFromFin Law3886 := by
  classical
  refine AutBox.structuralFromFin_iteOf3 ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0))
    GuardAut3_pyx_x_x_y_pxx_pyx_pxx_pxx_x_pyx_Equation3886 (fun {G} M hM ↦ ?_)
  have hm := (@Law3886.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ a ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op b a) = a ∨ a ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op b a) = a ∨ a = b ∨ (M.op a a) ≠ (M.op b a) ∨ N.op a b = a) →
      (∀ a b : G, (M.op b a) = a ∨ a = b ∨ (M.op a a) = (M.op b a) ∨ N.op a b = (M.op b a)) →
        @satisfies _ G N Law107 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op b a))).symm.imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_pos hg3))))
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op b a))).imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_neg hg3))))
  intro N ht hu hv hw
  rw [@Law107.models_iff G N]
  intro x y
  by_contra nh
  have eq7 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) = (M.op (M.op X1 (M.op X0 X2)) X3) := by
    intro X0 X1 X2 X3
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X1 X0) = X0 ∨ X0 ≠ X1 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq10 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X1 X0) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq11 : ∀ X0 X1 : G, (M.op X1 X0) = (N.op X0 X1) ∨ (M.op X0 X0) = (M.op X1 X0) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 := by
    intro X0 X1
    grind
  have eq12 : x ≠ (N.op x (N.op (N.op y y) x)) := by grind
  clear hm ht hu hv hw nh hM
  have eq19 : ∀ X0 X1 X5 : G, (M.op X1 X1) = (M.op (M.op X0 X0) X5) := by
    intro X0 X1 X5
    first
    | (have i₁ := eq7 X1 (M.op x (M.op X0 x)) x X5
       have i₂ := eq7 X0 x x (M.op X1 x)
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq38 : ∀ X0 X1 : G, (M.op X0 X0) = (M.op X1 X1) := by
    intro X0 X1
    first
    | (have i₁ := eq7 X0 (M.op X0 x) x x
       have i₂ := eq19 (M.op X0 x) X1 x
       grind)
    | (have i₁ := eq7 X0 X1 x (M.op X1 (M.op X0 x))
       have i₂ := eq19 X0 (M.op X1 (M.op X0 x)) x
       grind)
    | exact superpose eq19 eq7
    | exact resolve eq7 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq44 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X0 (M.op X1 X2)) X3) ≠ X1 ∨ (N.op X1 X1) = (M.op (M.op X0 (M.op X1 X2)) X3) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq8 X0 X0
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | exact superpose eq7 eq8
    | (have r₁ := eq8 (M.op X0 X0) (M.op X1 (M.op X0 X2))
       have r₂ := eq7 X0 X1 X2 (M.op X0 X0)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq69 : ∀ X0 X1 X2 X3 X4 : G, (M.op X0 X0) = (M.op (M.op X2 (M.op X1 X3)) X4) := by
    intro X0 X1 X2 X3 X4
    first
    | (have i₁ := eq7 X1 X2 X3 X4
       have i₂ := eq38 X1 X0
       grind)
    | (have i₁ := eq7 X1 X2 X3 X4
       have i₂ := eq38 X0 X1
       grind)
    | exact superpose eq38 eq7
    | exact resolve eq7 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq136 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 (M.op X0 X3)) = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X1 (M.op X2 (M.op X0 X3))) = X1 := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq10 X3 (M.op X1 (M.op X0 X2))
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | exact superpose eq7 eq10
    | (have j0 := eq10 (M.op X2 (M.op X0 X3)) X1
       grind)
    | (have r₁ := eq10 X3 (M.op X1 (M.op X3 X2))
       have r₂ := eq7 X3 X1 X2 X3
       grind)
    | exact resolve eq10 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq144 : ∀ X0 X1 X2 X3 : G, (N.op X1 (M.op X2 (M.op X0 X3))) = X1 ∨ (M.op X0 X0) = X1 ∨ (M.op X2 (M.op X0 X3)) = X1 := by
    intro X0 X1 X2 X3
    first
    | (have j0 := eq136 X0 X1 X2 X3
       grind)
    | (have r₁ := eq136 X0 X1 X2 X3
       have r₂ := eq38 X0 X1
       grind)
    | (have r₁ := eq136 X1 X0 X2 X3
       have r₂ := eq38 X0 X1
       grind)
    | exact resolve eq136 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq136
  have eq254 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) ∨ (M.op X1 X0) = (N.op X0 X1) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq8 X0 X1
       have i₂ := eq11 X0 X1
       grind)
    | (have i₁ := eq8 X0 X0
       have i₂ := eq11 X0 X1
       grind)
    | exact superpose eq11 eq8
    | (have j0 := eq8 X0 X0
       have j1 := eq11 X0 X1
       grind)
    | (have r₁ := eq8 X1 X1
       have r₂ := eq11 (M.op X1 X1) X1
       grind)
    | (have r₁ := eq8 X0 X1
       have r₂ := eq11 X0 (M.op X1 X0)
       grind)
    | (have r₁ := eq8 X0 X1
       have r₂ := eq11 X0 X1
       grind)
    | exact resolve eq8 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq263 : ∀ X0 X1 : G, (M.op X1 X1) ≠ X1 ∨ (M.op X0 X1) = (N.op X1 X0) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq11 X1 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq266 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) ∨ (M.op X1 X0) = (N.op X0 X1) ∨ X0 = X1 := by
    intro X0 X1
    first
    | (have j0 := eq254 X0 X1
       have j1 := eq8 X0 X0
       grind)
    | (have r₁ := eq254 (M.op X1 X0) X0
       have r₂ := eq8 X0 X1
       grind)
    | (have r₁ := eq254 X0 (M.op X1 X0)
       have r₂ := eq8 X0 X1
       grind)
    | (have r₁ := eq254 X0 X1
       have r₂ := eq8 X0 X1
       grind)
    | exact resolve eq254 eq8
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq254
  have eq361 : ∀ X0 X1 X2 X3 X4 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 (M.op X3 X4)) = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X1 (M.op X2 (M.op X3 X4))) = X1 := by
    intro X0 X1 X2 X3 X4
    first
    | (have i₁ := eq10 X0 X0
       have i₂ := eq69 X0 X1 X2 X3 X4
       grind)
    | (have i₁ := eq10 X4 (M.op X2 (M.op X1 X3))
       have i₂ := eq69 X0 X1 X2 X3 X4
       grind)
    | exact superpose eq69 eq10
    | (have j0 := eq10 (M.op X2 (M.op X3 X4)) X1
       grind)
    | (have r₁ := eq10 X4 (M.op X2 (M.op X1 X3))
       have r₂ := eq69 X4 X1 X2 X3 X4
       grind)
    | (have r₁ := eq10 (M.op X2 (M.op X1 X3)) (M.op X2 (M.op X1 X3))
       have r₂ := eq69 (M.op X2 (M.op X1 X3)) X1 X2 X3 (M.op X2 (M.op X1 X3))
       grind)
    | exact resolve eq10 eq69
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq365 : ∀ X0 X1 X2 X3 X4 : G, (M.op X2 (M.op X3 X4)) = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X1 (M.op X2 (M.op X3 X4))) = X1 := by
    intro X0 X1 X2 X3 X4
    first
    | (have j0 := eq361 X0 X1 X2 X3 X4
       grind)
    | (have r₁ := eq361 X0 X1 X2 X3 X4
       have r₂ := eq38 X0 X1
       grind)
    | (have r₁ := eq361 X1 X0 X2 X3 X4
       have r₂ := eq38 X0 X1
       grind)
    | exact resolve eq361 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq361
  have eq2148 : ∀ X0 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X0) := by
    intro X0
    first
    | (have i₁ := eq44 x X0 x x
       have i₂ := eq7 X0 x x x
       grind)
    | exact superpose eq7 eq44
    | exact resolve eq44 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq44
  have eq2173 : ∀ X0 : G, (M.op X0 X0) = (N.op X0 X0) := by
    intro X0
    grind
  clear eq2148
  have eq2176 : x ≠ (N.op x (N.op (M.op y y) x)) := by
    first
    | (have i₁ := eq12
       have i₂ := eq2173 y
       grind)
    | exact superpose eq2173 eq12
    | exact resolve eq12 eq2173
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq2198 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 ∨ (M.op X1 X1) = (M.op X2 (M.op X1 X1)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq263 X2 (M.op X1 X1)
       have i₂ := eq19 X1 X0 (M.op X1 X1)
       grind)
    | (have i₁ := eq263 X0 X1
       have i₂ := eq19 X0 X1 x
       grind)
    | exact superpose eq19 eq263
    | (have j0 := eq263 X2 (M.op X1 X1)
       grind)
    | (have r₁ := eq263 X0 (M.op (M.op X0 X0) x)
       have r₂ := eq19 X0 (M.op (M.op X0 X0) x) x
       grind)
    | (have r₁ := eq263 X0 (M.op X1 X1)
       have r₂ := eq19 X1 X1 (M.op X1 X1)
       grind)
    | exact resolve eq263 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq263
  have eq2209 : ∀ X1 X2 : G, (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 ∨ (M.op X1 X1) = (M.op X2 (M.op X1 X1)) := by
    intro X1 X2
    first
    | (have j0 := eq2198 x X1 X2
       grind)
    | (have r₁ := eq2198 x X1 X2
       have r₂ := eq38 x X1
       grind)
    | (have r₁ := eq2198 X1 x X2
       have r₂ := eq38 x X1
       grind)
    | exact resolve eq2198 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2198
  have eq2215 : ∀ X0 : G, x ≠ (N.op x (N.op (M.op X0 X0) x)) := by
    intro X0
    first
    | (have i₁ := eq2176
       have i₂ := eq38 y X0
       grind)
    | (have i₁ := eq2176
       have i₂ := eq38 X0 y
       grind)
    | exact superpose eq38 eq2176
    | exact resolve eq2176 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq2355 : ∀ X0 X1 X2 X3 X4 X5 : G, (N.op X0 (M.op X4 (M.op X2 X5))) = X0 ∨ (M.op X1 X1) = (M.op X0 X3) ∨ (M.op X4 (M.op X2 X5)) = X0 := by
    intro X0 X1 X2 X3 X4 X5
    first
    | (have i₁ := eq19 X2 X1 X3
       have i₂ := eq144 X2 X0 X4 X5
       grind)
    | (have i₁ := eq19 X0 X1 X5
       have i₂ := eq144 X0 (M.op X0 X0) X2 X3
       grind)
    | exact superpose eq144 eq19
    | (have j1 := eq144 X2 X0 X4 X5
       grind)
    | exact resolve eq19 eq144
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq144
  have eq2522 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X0 X0) = (N.op (M.op X1 X1) X2) ∨ (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq266 X1 X1
       have i₂ := eq19 X0 X1 x
       grind)
    | (have i₁ := eq266 (M.op X0 X0) X1
       have i₂ := eq19 X0 X1 (M.op X0 X0)
       grind)
    | exact superpose eq19 eq266
    | (have j0 := eq266 (M.op X1 X1) X2
       grind)
    | (have r₁ := eq266 (M.op (M.op X0 X0) x) X1
       have r₂ := eq19 X0 (M.op (M.op X0 X0) x) x
       grind)
    | (have r₁ := eq266 (M.op X1 X1) X1
       have r₂ := eq19 X1 X1 (M.op X1 X1)
       grind)
    | exact resolve eq266 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq266
  have eq2533 : ∀ X0 X1 X2 : G, (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X0 X0) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 := by
    intro X0 X1 X2
    first
    | (have j0 := eq2522 X0 X1 X2
       grind)
    | (have r₁ := eq2522 X0 X1 X2
       have r₂ := eq38 X0 X1
       grind)
    | (have r₁ := eq2522 X1 X0 X2
       have r₂ := eq38 X0 X1
       grind)
    | exact resolve eq2522 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2522
  have eq15094 : ∀ X0 X1 X2 X3 : G, (M.op X3 X3) ≠ X0 ∨ (N.op X0 (M.op X0 (M.op X1 X2))) = X0 ∨ (M.op X0 (M.op X1 X2)) = X0 := by
    intro X0 X1 X2 X3
    first
    | (have j0 := eq2355 X0 X1 X1 X3 X0 X2
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2355
  have eq15106 : ∀ X0 X1 X2 : G, (N.op X0 (M.op X0 (M.op X1 X2))) = X0 ∨ (M.op X0 (M.op X1 X2)) = X0 := by
    intro X0 X1 X2
    first
    | (have j0 := eq15094 X0 X1 X2 x
       have j1 := eq365 X0 X0 X0 X1 X2
       grind)
    | (have r₁ := eq15094 X1 X1 X2 (M.op x x)
       have r₂ := eq365 X0 X1 (M.op x x) x x
       grind)
    | (have r₁ := eq15094 (M.op X2 (M.op x x)) X1 X2 x
       have r₂ := eq365 X0 (M.op x x) X2 x x
       grind)
    | (have r₁ := eq15094 X1 X1 X2 X0
       have r₂ := eq365 X0 X1 X2 x x
       grind)
    | exact resolve eq15094 eq365
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq365 eq15094
  have eq24638 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op X1 (M.op X2 X2)) ∨ (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) ∨ (M.op X2 X2) = X1 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq2209 X2 X1
       have i₂ := eq2533 X0 X2 X1
       grind)
    | exact superpose eq2533 eq2209
    | (have j0 := eq2209 X2 X1
       have j1 := eq2533 X0 X2 X1
       grind)
    | exact resolve eq2209 eq2533
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2209
  have eq24673 : ∀ X0 X1 X2 : G, (M.op X2 X2) ≠ (M.op X1 (M.op X0 X0)) ∨ (M.op X1 (M.op X0 X0)) = (N.op (M.op X0 X0) X1) ∨ (M.op X0 X0) = X1 := by
    intro X0 X1 X2
    first
    | (have j0 := eq2533 X0 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2533
  have eq24687 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op X1 (M.op X2 X2)) ∨ (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) := by
    intro X0 X1 X2
    first
    | (have j0 := eq24638 X0 X1 X2
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq24638
  have eq24716 : ∀ X1 X2 : G, (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) := by
    intro X1 X2
    first
    | (have j0 := eq24687 X2 X1 X2
       have j1 := eq24673 X2 X1 X2
       grind)
    | (have r₁ := eq24687 X2 X1 x
       have r₂ := eq24673 x X1 X2
       grind)
    | (have r₁ := eq24687 (M.op x x) (M.op X2 X2) X2
       have r₂ := eq24673 x (M.op x x) (M.op X2 X2)
       grind)
    | (have r₁ := eq24687 x (M.op X1 (M.op x x)) X2
       have r₂ := eq24673 x X1 X2
       grind)
    | exact resolve eq24687 eq24673
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq24687
  have eq24733 : ∀ X1 X2 : G, (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) ∨ (M.op X2 X2) = X1 := by
    intro X1 X2
    first
    | (have j0 := eq24716 X1 X2
       have j1 := eq24673 X2 X1 X2
       grind)
    | (have r₁ := eq24716 (M.op X1 (M.op x x)) X2
       have r₂ := eq24673 x X1 X2
       grind)
    | (have r₁ := eq24716 (M.op X2 X2) (M.op x x)
       have r₂ := eq24673 x (M.op x x) X2
       grind)
    | (have r₁ := eq24716 X1 x
       have r₂ := eq24673 x X1 x
       grind)
    | exact resolve eq24716 eq24673
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq24673 eq24716
  have eq77381 : x ≠ (N.op x (M.op x (M.op y y))) ∨ x = (M.op y y) := by
    first
    | (have i₁ := eq2176
       have i₂ := eq24733 x y
       grind)
    | exact superpose eq24733 eq2176
    | (have j1 := eq24733 x y
       grind)
    | exact resolve eq2176 eq24733
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2176 eq24733
  have eq77477 : x ≠ x ∨ x = (M.op y y) ∨ x = (M.op x (M.op y y)) := by
    first
    | (have i₁ := eq77381
       have i₂ := eq15106 x y y
       grind)
    | exact superpose eq15106 eq77381
    | (have j1 := eq15106 x y y
       grind)
    | (have r₁ := eq77381
       have r₂ := eq15106 x y y
       grind)
    | exact resolve eq77381 eq15106
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15106
  have eq77484 : x = (M.op x (M.op y y)) ∨ x = (M.op y y) := by grind
  clear eq77477
  have eq78295 : x ≠ (N.op x x) ∨ x = (M.op y y) ∨ x = (M.op y y) := by
    first
    | (have i₁ := eq77381
       have i₂ := eq77484
       grind)
    | exact superpose eq77484 eq77381
    | exact resolve eq77381 eq77484
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq77381
  have eq78304 : ∀ X0 X1 : G, (M.op X0 X0) = (M.op x X1) ∨ x = (M.op y y) := by
    intro X0 X1
    first
    | (have i₁ := eq69 X0 y x y X1
       have i₂ := eq77484
       grind)
    | exact superpose eq77484 eq69
    | exact resolve eq69 eq77484
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq69
  have eq78465 : x ≠ (N.op x x) ∨ x = (M.op y y) := by grind
  clear eq78295
  have eq78484 : x ≠ (M.op x x) ∨ x = (M.op y y) := by
    first
    | (have i₁ := eq78465
       have i₂ := eq2173 x
       grind)
    | exact superpose eq2173 eq78465
    | exact resolve eq78465 eq2173
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq78465
  have eq80673 : ∀ X0 : G, (M.op X0 X0) ≠ x ∨ x = (M.op y y) := by
    intro X0
    first
    | (have i₁ := eq78484
       have i₂ := eq38 x X0
       grind)
    | (have i₁ := eq78484
       have i₂ := eq38 X0 x
       grind)
    | exact superpose eq38 eq78484
    | exact resolve eq78484 eq38
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq78484
  have eq84447 : ∀ X0 : G, (M.op X0 X0) = x ∨ x = (M.op y y) ∨ x = (M.op y y) := by
    intro X0
    first
    | (have i₁ := eq77484
       have i₂ := eq78304 X0 (M.op y y)
       grind)
    | exact superpose eq78304 eq77484
    | exact resolve eq77484 eq78304
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq77484 eq78304
  have eq85012 : ∀ X0 : G, (M.op X0 X0) = x ∨ x = (M.op y y) := by
    intro X0
    first
    | (have j0 := eq84447 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq84447
  have eq85052 : x = (M.op y y) := by
    first
    | (have j0 := eq85012 y
       grind)
    | (have r₁ := eq85012 x
       have r₂ := eq80673 x
       grind)
    | (have r₁ := eq85012 x
       have r₂ := eq80673 y
       grind)
    | exact resolve eq85012 eq80673
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq80673 eq85012
  have eq85194 : ∀ X0 X1 : G, (M.op X0 X0) = (M.op x X1) := by
    intro X0 X1
    first
    | (have i₁ := eq19 y X0 X1
       have i₂ := eq85052
       grind)
    | exact superpose eq85052 eq19
    | exact resolve eq19 eq85052
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq85201 : ∀ X0 : G, (M.op X0 X0) = x := by
    intro X0
    first
    | (have i₁ := eq38 X0 y
       have i₂ := eq85052
       grind)
    | exact superpose eq85052 eq38
    | exact resolve eq38 eq85052
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq38
  have eq85233 : x ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq2215 y
       have i₂ := eq85052
       grind)
    | exact superpose eq85052 eq2215
    | exact resolve eq2215 eq85052
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2215 eq85052
  have eq85421 : x ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq85233
       have i₂ := eq2173 x
       grind)
    | exact superpose eq2173 eq85233
    | exact resolve eq85233 eq2173
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq85233
  have eq85430 : ∀ X1 : G, x = (M.op x X1) := by
    intro X1
    first
    | (have i₁ := eq85194 x X1
       have i₂ := eq85201 x
       grind)
    | exact superpose eq85201 eq85194
    | exact resolve eq85194 eq85201
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq85194
  have eq85439 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq85421
       have i₂ := eq85201 x
       grind)
    | exact superpose eq85201 eq85421
    | exact resolve eq85421 eq85201
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq85201 eq85421
  have eq85448 : x ≠ (M.op x x) := by
    first
    | (have i₁ := eq85439
       have i₂ := eq2173 x
       grind)
    | exact superpose eq2173 eq85439
    | exact resolve eq85439 eq2173
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2173 eq85439
  have eq85455 : False := by grind
  exact eq85455
