import equational_theories.Definability.AutBox3
import equational_theories.Definability.Lw6_00

/-!
# Structurality from `Equation1636` through a three-guard companion, by replay

Generated by `defwork/itautcreplay3.py`.  `Equation1636` is `x = (x ◇ x) ◇ ((y ◇ x) ◇ z)`, and the companion is
`x □ y = if (M.op a b) = b then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op a b) then b else (M.op a b)`.  Its automorphism half is `GuardAut3_pxy_y_x_y_pxx_pxy_pxx_pxx_y_pxy_Equation1636`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches it on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation323` from `Equation1636`: `x = (x ◇ x) ◇ ((y ◇ x) ◇ z)` ⊢ `x ◇ y = x ◇ (x ◇ y)`, through the
companion `x □ y = if (M.op a b) = b then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op a b) then b else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation323_StructuralFromFin_Equation1636 : Law323.StructuralFromFin Law1636 := by
  classical
  refine AutBox.structuralFromFin_iteOf3 ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardAut3_pxy_y_x_y_pxx_pxy_pxx_pxx_y_pxy_Equation1636 (fun {G} M hM ↦ ?_)
  have hm := (@Law1636.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op a b) = b ∨ a ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op a b) = b ∨ a = b ∨ (M.op a a) ≠ (M.op a b) ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = b ∨ a = b ∨ (M.op a a) = (M.op a b) ∨ N.op a b = (M.op a b)) →
        @satisfies _ G N Law323 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op a b))).symm.imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_pos hg3))))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 1)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op a b))).imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_neg hg3))))
  intro N ht hu hv hw
  rw [@Law323.models_iff G N]
  intro x y
  by_contra nh
  have eq7 : ∀ X0 X1 X2 : G, (M.op (M.op X0 X0) (M.op (M.op X1 X0) X2)) = X0 := by
    intro X0 X1 X2
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X0 X1) = X1 ∨ X0 ≠ X1 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq10 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X0 X1) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 ∨ (N.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq11 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X0) = (M.op X0 X1) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq12 : (N.op x y) ≠ (N.op x (N.op x y)) := by grind
  clear hm ht hu hv hw nh hM
  have eq14 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X1 X0) X2) = (M.op (M.op (M.op (M.op X1 X0) X2) (M.op (M.op X1 X0) X2)) (M.op X0 X3)) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq7 (M.op (M.op X1 X0) X2) (M.op X0 X0) X3
       have i₂ := eq7 X0 X1 X2
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq15 : ∀ X0 : G, (M.op (M.op X0 X0) X0) = X0 := by
    intro X0
    first
    | (have i₁ := eq7 X0 X0 (M.op (M.op x X0) x)
       have i₂ := eq7 X0 x x
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq17 : ∀ X0 X1 : G, (M.op (M.op X0 X0) (M.op X0 X1)) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq7 X0 (M.op X0 X0) X1
       have i₂ := eq15 X0
       grind)
    | exact superpose eq15 eq7
    | exact resolve eq7 eq15
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq19 : ∀ X0 : G, X0 ≠ X0 ∨ (M.op (M.op X0 X0) (M.op X0 X0)) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have i₁ := eq8 (M.op X0 X0) X0
       have i₂ := eq15 X0
       grind)
    | exact superpose eq15 eq8
    | (have j0 := eq8 (M.op X0 X0) X0
       grind)
    | (have r₁ := eq8 (M.op X0 X0) X0
       have r₂ := eq15 X0
       grind)
    | exact resolve eq8 eq15
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq20 : ∀ X0 : G, (M.op (M.op X0 X0) (M.op X0 X0)) = (N.op (M.op X0 X0) X0) := by
    intro X0
    first
    | (have j0 := eq19 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq21 : ∀ X0 : G, (N.op (M.op X0 X0) X0) = X0 := by
    intro X0
    first
    | (have i₁ := eq20 X0
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq20
    | exact resolve eq20 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq20
  have eq28 : ∀ X0 : G, (M.op X0 X0) = (N.op X0 (M.op X0 X0)) := by
    intro X0
    first
    | (have i₁ := eq21 (M.op X0 X0)
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq21
    | exact resolve eq21 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq21
  have eq30 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op X0 (M.op (M.op X1 (M.op X0 X0)) X2)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq7 (M.op X0 X0) X1 X2
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq7
    | exact resolve eq7 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq31 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X0 ∨ (M.op (M.op X0 X0) (M.op X0 X0)) = (N.op (M.op X0 X0) (M.op X0 X1)) := by
    intro X0 X1
    first
    | (have i₁ := eq8 (M.op X0 X0) (M.op X0 X1)
       have i₂ := eq17 X0 X1
       grind)
    | exact superpose eq17 eq8
    | (have j0 := eq8 (M.op X0 X0) (M.op X0 X1)
       grind)
    | exact resolve eq8 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq33 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X0 ∨ (N.op (M.op X0 X0) (M.op X0 X1)) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq31 X0 X1
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq31
    | (have j0 := eq31 X0 X1
       grind)
    | exact resolve eq31 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq31
  have eq60 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X0 X0) ∨ X0 = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X0 X1) = X1 ∨ (M.op X0 X1) = (N.op X0 X1) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq10 X0 X0
       have i₂ := eq11 X0 X1
       grind)
    | (have i₁ := eq10 X0 X1
       have i₂ := eq11 X0 X1
       grind)
    | exact superpose eq11 eq10
    | (have j0 := eq10 X0 X1
       have j1 := eq11 X0 X1
       grind)
    | (have r₁ := eq10 X0 X1
       have r₂ := eq11 X0 X1
       grind)
    | (have r₁ := eq10 X1 X1
       have r₂ := eq11 X1 X1
       grind)
    | (have r₁ := eq10 X0 X1
       have r₂ := eq11 (M.op X0 X0) (M.op X0 X1)
       grind)
    | exact resolve eq10 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq67 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X1 ∨ (M.op X0 X1) = (N.op X0 X1) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq11 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq68 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X0 X0) ∨ X0 = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X0 X1) = X1 ∨ (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq60 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq60
  have eq69 : ∀ X0 X1 : G, X0 = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X0 X1) = X1 ∨ (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq68 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq68
  have eq73 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (N.op X0 X1) = X1 ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq69 X0 X1
       have j1 := eq67 X0 X1
       grind)
    | (have r₁ := eq69 (M.op X0 X0) X1
       have r₂ := eq67 X0 X1
       grind)
    | (have r₁ := eq69 X1 (M.op X0 X0)
       have r₂ := eq67 X0 X1
       grind)
    | (have r₁ := eq69 X0 X1
       have r₂ := eq67 X0 X1
       grind)
    | exact resolve eq69 eq67
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq67 eq69
  have eq118 : ∀ X0 X1 : G, (M.op X0 X0) = (M.op X0 (M.op X0 X1)) := by
    intro X0 X1
    first
    | (have i₁ := eq30 X0 (M.op X0 X0) X1
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq30
    | exact resolve eq30 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq143 : (M.op x y) ≠ (N.op x (M.op x y)) ∨ y = (N.op x y) ∨ x = y ∨ y = (M.op x y) := by
    first
    | (have i₁ := eq12
       have i₂ := eq73 x y
       grind)
    | exact superpose eq73 eq12
    | (have j1 := eq73 x y
       grind)
    | (have r₁ := eq12
       have r₂ := eq73 x (N.op x y)
       grind)
    | (have r₁ := eq12
       have r₂ := eq73 (N.op x y) (N.op x (N.op x y))
       grind)
    | (have r₁ := eq12
       have r₂ := eq73 (N.op x (N.op x y)) (N.op x y)
       grind)
    | exact resolve eq12 eq73
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq73
  have eq163 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X0 X0) ∨ (M.op X0 X1) = X0 ∨ (M.op X0 X0) = (M.op X0 X1) ∨ (M.op X0 X1) = (N.op X0 (M.op X0 X1)) := by
    intro X0 X1
    first
    | (have i₁ := eq10 X0 (M.op X0 X1)
       have i₂ := eq118 X0 X1
       grind)
    | exact superpose eq118 eq10
    | (have j0 := eq10 X0 X0
       grind)
    | (have r₁ := eq10 X0 (M.op X0 X1)
       have r₂ := eq118 X0 X1
       grind)
    | exact resolve eq10 eq118
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq118
  have eq171 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 (M.op X0 X1)) ∨ (M.op X0 X0) = (M.op X0 X1) ∨ (M.op X0 X1) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq163 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq163
  have eq211 : ∀ X0 X1 X2 X3 : G, (M.op X1 X1) = (M.op X1 (M.op (M.op (M.op X0 X1) X2) X3)) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq30 X1 (M.op (M.op (M.op X0 X1) X2) (M.op (M.op X0 X1) X2)) X3
       have i₂ := eq14 X1 X0 X2 X1
       grind)
    | exact superpose eq14 eq30
    | exact resolve eq30 eq14
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq14 eq30
  have eq248 : ∀ X0 X1 : G, (M.op X1 X1) = (M.op X1 (M.op X0 X1)) := by
    intro X0 X1
    first
    | (have i₁ := eq211 X0 X1 (M.op X0 X1) (M.op X0 X1)
       have i₂ := eq15 (M.op X0 X1)
       grind)
    | exact superpose eq15 eq211
    | exact resolve eq211 eq15
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq211
  have eq793 : ∀ X0 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op (M.op (M.op X0 X0) (M.op X0 X0)) X0) := by
    intro X0
    first
    | (have i₁ := eq33 (M.op X0 X0) X0
       have i₂ := eq15 X0
       grind)
    | exact superpose eq15 eq33
    | (have j0 := eq33 X0 X0
       grind)
    | exact resolve eq33 eq15
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq15 eq33
  have eq812 : ∀ X0 : G, (M.op X0 X0) = (N.op X0 X0) ∨ (M.op X0 X0) ≠ X0 := by
    intro X0
    first
    | (have i₁ := eq793 X0
       have i₂ := eq17 X0 X0
       grind)
    | exact superpose eq17 eq793
    | (have j0 := eq793 X0
       grind)
    | exact resolve eq793 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq17 eq793
  have eq818 : ∀ X0 : G, (M.op X0 X0) = (N.op X0 X0) := by
    intro X0
    grind
  clear eq812
  have eq329203 : (M.op x y) ≠ (M.op x y) ∨ y = (N.op x y) ∨ x = y ∨ y = (M.op x y) ∨ (M.op x y) = (M.op x x) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq143
       have i₂ := eq171 x y
       grind)
    | exact superpose eq171 eq143
    | (have j1 := eq171 x y
       grind)
    | (have r₁ := eq143
       have r₂ := eq171 x y
       grind)
    | exact resolve eq143 eq171
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq143 eq171
  have eq329204 : y = (N.op x y) ∨ x = y ∨ y = (M.op x y) ∨ (M.op x y) = (M.op x x) ∨ x = (M.op x y) := by grind
  clear eq329203
  have eq329205 : y = (N.op x y) ∨ x = y ∨ y = (M.op x y) ∨ x = (M.op x y) := by
    first
    | (have j1 := eq10 x y
       grind)
    | (have r₁ := eq329204
       have r₂ := eq10 x y
       grind)
    | exact resolve eq329204 eq10
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq329204
  have eq330712 : y ≠ (N.op x y) ∨ x = y ∨ y = (M.op x y) ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq12
       have i₂ := eq329205
       grind)
    | exact superpose eq329205 eq12
    | exact resolve eq12 eq329205
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq330717 : y = (M.op x y) ∨ x = y ∨ x = (M.op x y) := by
    first
    | (have r₁ := eq330712
       have r₂ := eq329205
       grind)
    | exact resolve eq330712 eq329205
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq329205 eq330712
  have eq331057 : y ≠ y ∨ (N.op x y) = (M.op x x) ∨ x = y ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq8 x y
       have i₂ := eq330717
       grind)
    | exact superpose eq330717 eq8
    | (have j0 := eq8 x y
       grind)
    | (have r₁ := eq8 x y
       have r₂ := eq330717
       grind)
    | exact resolve eq8 eq330717
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq330717
  have eq331354 : (N.op x y) = (M.op x x) ∨ x = y ∨ x = (M.op x y) := by grind
  clear eq331057
  have eq344444 : (M.op x x) ≠ (N.op x (M.op x x)) ∨ x = y ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq12
       have i₂ := eq331354
       grind)
    | exact superpose eq331354 eq12
    | exact resolve eq12 eq331354
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq331354
  have eq344453 : x = (M.op x y) ∨ x = y := by
    first
    | (have r₁ := eq344444
       have r₂ := eq28 x
       grind)
    | exact resolve eq344444 eq28
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq344444
  have eq344933 : ∀ X0 : G, y = (M.op (M.op y y) (M.op x X0)) ∨ x = y := by
    intro X0
    first
    | (have i₁ := eq7 y x X0
       have i₂ := eq344453
       grind)
    | exact superpose eq344453 eq7
    | exact resolve eq7 eq344453
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq344935 : x ≠ (M.op x x) ∨ x = y ∨ x = y ∨ y = (N.op x y) ∨ x = y := by
    first
    | (have i₁ := eq10 x y
       have i₂ := eq344453
       grind)
    | exact superpose eq344453 eq10
    | (have j0 := eq10 x y
       grind)
    | exact resolve eq10 eq344453
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq345265 : x ≠ (M.op x x) ∨ x = y ∨ y = (N.op x y) := by grind
  clear eq344935
  have eq352185 : y = (M.op (M.op y y) x) ∨ x = y ∨ x = y := by
    first
    | (have i₁ := eq344933 y
       have i₂ := eq344453
       grind)
    | exact superpose eq344453 eq344933
    | exact resolve eq344933 eq344453
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq344933
  have eq352702 : y = (M.op (M.op y y) x) ∨ x = y := by grind
  clear eq352185
  have eq355150 : (M.op x y) = (M.op x x) ∨ x = y := by
    first
    | (have i₁ := eq248 (M.op y y) x
       have i₂ := eq352702
       grind)
    | exact superpose eq352702 eq248
    | exact resolve eq248 eq352702
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq248 eq352702
  have eq356044 : x = (M.op x x) ∨ x = y ∨ x = y := by
    first
    | (have i₁ := eq344453
       have i₂ := eq355150
       grind)
    | exact superpose eq355150 eq344453
    | exact resolve eq344453 eq355150
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq344453 eq355150
  have eq356353 : x = (M.op x x) ∨ x = y := by grind
  clear eq356044
  have eq389499 : x ≠ x ∨ x = y ∨ y = (N.op x y) ∨ x = y := by
    first
    | (have i₁ := eq345265
       have i₂ := eq356353
       grind)
    | exact superpose eq356353 eq345265
    | (have r₁ := eq345265
       have r₂ := eq356353
       grind)
    | exact resolve eq345265 eq356353
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq345265 eq356353
  have eq389500 : x ≠ x ∨ x = y ∨ y = (N.op x y) := by grind
  clear eq389499
  have eq389501 : y = (N.op x y) ∨ x = y := by grind
  clear eq389500
  have eq389894 : y ≠ (N.op x y) ∨ x = y := by
    first
    | (have i₁ := eq12
       have i₂ := eq389501
       grind)
    | exact superpose eq389501 eq12
    | exact resolve eq12 eq389501
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq389908 : x = y := by
    first
    | (have r₁ := eq389894
       have r₂ := eq389501
       grind)
    | exact resolve eq389894 eq389501
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq389501 eq389894
  have eq390809 : (N.op x x) ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq12
       have i₂ := eq389908
       grind)
    | exact superpose eq389908 eq12
    | exact resolve eq12 eq389908
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq389908
  have eq390810 : (M.op x x) ≠ (N.op x (M.op x x)) := by
    first
    | (have i₁ := eq390809
       have i₂ := eq818 x
       grind)
    | exact superpose eq818 eq390809
    | exact resolve eq390809 eq818
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq818 eq390809
  have eq390811 : False := by grind
  exact eq390811
