import equational_theories.Definability.AutBox3
import equational_theories.Definability.Lw6_00

/-!
# Structurality from `Equation3904` through a three-guard companion, by replay

Generated by `defwork/itautcreplay3.py`.  `Equation3904` is `x ◇ x = (y ◇ (z ◇ y)) ◇ w`, and the companion is
`x □ y = if (M.op b a) = a then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op b a) then a else (M.op b a)`.  Its automorphism half is `GuardAut3_pyx_x_x_y_pxx_pyx_pxx_pxx_x_pyx_Equation3904`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches it on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation107` from `Equation3904`: `x ◇ x = (y ◇ (z ◇ y)) ◇ w` ⊢ `x = x ◇ ((y ◇ y) ◇ x)`, through the
companion `x □ y = if (M.op b a) = a then (M.op a a) else if a = b then (M.op a a) else if (M.op a a) = (M.op b a) then a else (M.op b a)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation107_StructuralFromFin_Equation3904 : Law107.StructuralFromFin Law3904 := by
  classical
  refine AutBox.structuralFromFin_iteOf3 ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0))
    GuardAut3_pyx_x_x_y_pxx_pyx_pxx_pxx_x_pyx_Equation3904 (fun {G} M hM ↦ ?_)
  have hm := (@Law3904.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op b a) ≠ a ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op b a) = a ∨ a ≠ b ∨ N.op a b = (M.op a a)) →
      (∀ a b : G, (M.op b a) = a ∨ a = b ∨ (M.op a a) ≠ (M.op b a) ∨ N.op a b = a) →
      (∀ a b : G, (M.op b a) = a ∨ a = b ∨ (M.op a a) = (M.op b a) ∨ N.op a b = (M.op b a)) →
        @satisfies _ G N Law107 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op b a))).symm.imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_pos hg3))))
    · rw [AutBox.iteOf3_apply ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 0)) ((Lf 1) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) ((Lf 0) ⋆ (Lf 0)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op b a)) (a)).imp id (fun hg ↦
        (eq_or_ne (a) (b)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a a)) ((M.op b a))).imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_neg hg3))))
  intro N ht hu hv hw
  rw [@Law107.models_iff G N]
  intro x y
  by_contra nh
  have eq7 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) = (M.op (M.op X1 (M.op X2 X1)) X3) := by
    intro X0 X1 X2 X3
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X1 X0) = X0 ∨ X0 ≠ X1 ∨ (M.op X0 X0) = (N.op X0 X1) := by
    intro X0 X1
    grind
  have eq10 : ∀ X0 X1 : G, (M.op X0 X0) ≠ (M.op X1 X0) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq11 : ∀ X0 X1 : G, (M.op X1 X0) = (N.op X0 X1) ∨ (M.op X0 X0) = (M.op X1 X0) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 := by
    intro X0 X1
    grind
  have eq12 : x ≠ (N.op x (N.op (N.op y y) x)) := by grind
  clear hm ht hu hv hw nh hM
  have eq14 : ∀ X0 X1 X2 X4 X5 X6 : G, (M.op (M.op X0 (M.op X1 X0)) X2) = (M.op (M.op X4 (M.op X5 X4)) X6) := by
    intro X0 X1 X2 X4 X5 X6
    first
    | (have i₁ := eq7 x X4 X5 X6
       have i₂ := eq7 x X0 X1 X2
       grind)
    | (have i₁ := eq7 (M.op X1 (M.op X2 X1)) X1 X2 x
       have i₂ := eq7 X0 X1 X2 (M.op X1 (M.op X2 X1))
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq16 : ∀ X0 X1 X2 X3 X4 X5 : G, (M.op X3 X3) = (M.op (M.op X4 (M.op (M.op X0 (M.op X1 X0)) X2)) X5) := by
    intro X0 X1 X2 X3 X4 X5
    first
    | (have i₁ := eq7 X3 X4 X4 X5
       have i₂ := eq7 X4 X0 X1 X2
       grind)
    | (have i₁ := eq7 X0 X3 (M.op X1 (M.op X2 X1)) X3
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq17 : ∀ X0 X1 X2 X5 : G, (M.op X1 X1) = (M.op (M.op X2 (M.op X0 X0)) X5) := by
    intro X0 X1 X2 X5
    first
    | (have i₁ := eq7 X1 X2 (M.op x (M.op x x)) X5
       have i₂ := eq7 X0 x x X2
       grind)
    | (have i₁ := eq7 X0 X0 X0 x
       have i₂ := eq7 X0 X1 X2 x
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq18 : ∀ X0 X1 X5 : G, (M.op X1 X1) = (M.op (M.op X0 X0) X5) := by
    intro X0 X1 X5
    first
    | (have i₁ := eq7 X1 (M.op x (M.op x x)) x X5
       have i₂ := eq7 X0 x x (M.op x (M.op x (M.op x x)))
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq19 : ∀ X0 X1 : G, (M.op X0 X0) = (M.op X1 X1) := by
    intro X0 X1
    first
    | (have i₁ := eq7 X0 x x x
       have i₂ := eq7 X1 x x x
       grind)
    | (have i₁ := eq7 X0 X1 x (M.op X1 (M.op x X1))
       have i₂ := eq7 (M.op X1 (M.op x X1)) X1 x x
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq38 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) ≠ X3 ∨ (M.op X3 X3) = (N.op X3 (M.op X1 (M.op X2 X1))) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq8 X3 (M.op X1 (M.op X2 X1))
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | (have i₁ := eq8 X0 X0
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | exact superpose eq7 eq8
    | (have j0 := eq8 X3 (M.op X1 (M.op X2 X1))
       grind)
    | (have r₁ := eq8 (M.op (M.op X1 (M.op X2 X1)) X3) (M.op (M.op X1 (M.op X2 X1)) X3)
       have r₂ := eq7 (M.op (M.op X1 (M.op X2 X1)) X3) X1 X2 X3
       grind)
    | (have r₁ := eq8 (M.op X0 X0) (M.op X1 (M.op X2 X1))
       have r₂ := eq7 X0 X1 X2 (M.op X0 X0)
       grind)
    | exact resolve eq8 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq39 : ∀ X0 X1 X3 X4 : G, (M.op (M.op X0 X0) X1) = (M.op (M.op X3 X3) X4) := by
    intro X0 X1 X3 X4
    first
    | (have i₁ := eq18 X3 x X4
       have i₂ := eq18 X0 x X1
       grind)
    | (have i₁ := eq18 X0 (M.op X0 X0) x
       have i₂ := eq18 X0 X1 (M.op X0 X0)
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq45 : ∀ X0 X1 X2 X4 : G, (M.op X2 X2) = (M.op (M.op (M.op X0 X0) X1) X4) := by
    intro X0 X1 X2 X4
    first
    | (have i₁ := eq18 x X2 X4
       have i₂ := eq18 X0 x X1
       grind)
    | (have i₁ := eq18 (M.op X0 X0) X1 x
       have i₂ := eq18 X0 X1 (M.op X0 X0)
       grind)
    | exact superpose eq18 eq18
    | exact resolve eq18 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq65 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ X2 ∨ (M.op X2 X2) = (N.op X2 (M.op X1 X1)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq8 X2 (M.op X1 X1)
       have i₂ := eq18 X1 X0 X2
       grind)
    | (have i₁ := eq8 X1 X1
       have i₂ := eq18 X0 X1 x
       grind)
    | exact superpose eq18 eq8
    | (have j0 := eq8 X2 (M.op X1 X1)
       grind)
    | (have r₁ := eq8 (M.op (M.op X0 X0) x) (M.op (M.op X0 X0) x)
       have r₂ := eq18 X0 (M.op (M.op X0 X0) x) x
       grind)
    | (have r₁ := eq8 (M.op X1 X1) (M.op X0 X0)
       have r₂ := eq18 X0 X1 (M.op X1 X1)
       grind)
    | exact resolve eq8 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq68 : x ≠ (N.op x (N.op (M.op y y) x)) ∨ y = (M.op y y) := by grind
  have eq102 : ∀ X0 X1 X2 X3 X5 : G, (M.op X3 X3) = (M.op (M.op (M.op X0 (M.op X1 X1)) X2) X5) := by
    intro X0 X1 X2 X3 X5
    first
    | (have i₁ := eq18 x X3 X5
       have i₂ := eq17 X1 x X0 X2
       grind)
    | (have i₁ := eq18 (M.op X2 (M.op X0 X0)) X1 X5
       have i₂ := eq17 X0 X1 X2 (M.op X2 (M.op X0 X0))
       grind)
    | exact superpose eq17 eq18
    | exact resolve eq18 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq128 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 (M.op X3 X2)) = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X1 (M.op X2 (M.op X3 X2))) = X1 := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq10 X0 X0
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | (have i₁ := eq10 X3 (M.op X1 (M.op X2 X1))
       have i₂ := eq7 X0 X1 X2 X3
       grind)
    | exact superpose eq7 eq10
    | (have j0 := eq10 (M.op X2 (M.op X3 X2)) X1
       grind)
    | (have r₁ := eq10 X3 (M.op X1 (M.op X2 X1))
       have r₂ := eq7 X3 X1 X2 X3
       grind)
    | (have r₁ := eq10 (M.op X1 (M.op X2 X1)) (M.op X1 (M.op X2 X1))
       have r₂ := eq7 (M.op X1 (M.op X2 X1)) X1 X2 (M.op X1 (M.op X2 X1))
       grind)
    | exact resolve eq10 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq130 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 X2) = X1 ∨ (M.op X0 X0) = X1 ∨ (N.op X1 (M.op X2 X2)) = X1 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10 X1 X1
       have i₂ := eq18 X0 X1 x
       grind)
    | (have i₁ := eq10 x (M.op X0 X0)
       have i₂ := eq18 X0 X1 x
       grind)
    | exact superpose eq18 eq10
    | (have j0 := eq10 (M.op X2 X2) X1
       grind)
    | (have r₁ := eq10 x (M.op X0 X0)
       have r₂ := eq18 X0 x x
       grind)
    | (have r₁ := eq10 (M.op X0 X0) (M.op X0 X0)
       have r₂ := eq18 X0 (M.op X0 X0) (M.op X0 X0)
       grind)
    | exact resolve eq10 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq132 : ∀ X0 X1 X2 : G, (N.op X1 (M.op X2 X2)) = X1 ∨ (M.op X0 X0) = X1 ∨ (M.op X2 X2) = X1 := by
    intro X0 X1 X2
    first
    | (have j0 := eq130 X0 X1 X2
       grind)
    | (have r₁ := eq130 X0 X1 X2
       have r₂ := eq19 X0 X1
       grind)
    | (have r₁ := eq130 X1 X0 X2
       have r₂ := eq19 X0 X1
       grind)
    | exact resolve eq130 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq130
  have eq134 : ∀ X0 X1 X2 X3 : G, (N.op X1 (M.op X2 (M.op X3 X2))) = X1 ∨ (M.op X0 X0) = X1 ∨ (M.op X2 (M.op X3 X2)) = X1 := by
    intro X0 X1 X2 X3
    first
    | (have j0 := eq128 X0 X1 X2 X3
       grind)
    | (have r₁ := eq128 X0 X1 X2 X3
       have r₂ := eq19 X0 X1
       grind)
    | (have r₁ := eq128 X1 X0 X2 X3
       have r₂ := eq19 X0 X1
       grind)
    | exact resolve eq128 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq128
  have eq154 : ∀ X0 X1 X2 X3 X4 X6 : G, (M.op (M.op X3 X3) X4) = (M.op (M.op (M.op X0 (M.op X1 X1)) X2) X6) := by
    intro X0 X1 X2 X3 X4 X6
    first
    | (have i₁ := eq39 X3 X4 x X6
       have i₂ := eq17 X1 x X0 X2
       grind)
    | (have i₁ := eq39 X0 X1 (M.op X2 (M.op X0 X0)) X4
       have i₂ := eq17 X0 X1 X2 (M.op X2 (M.op X0 X0))
       grind)
    | exact superpose eq17 eq39
    | exact resolve eq39 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq39
  have eq241 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) ∨ (M.op X1 X0) = (N.op X0 X1) ∨ X0 = X1 ∨ (M.op X1 X0) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq8 X0 X1
       have i₂ := eq11 X0 X1
       grind)
    | (have i₁ := eq8 X0 X0
       have i₂ := eq11 X0 X1
       grind)
    | exact superpose eq11 eq8
    | (have j0 := eq8 X0 X0
       have j1 := eq11 X0 X1
       grind)
    | (have r₁ := eq8 X1 X1
       have r₂ := eq11 (M.op X1 X1) X1
       grind)
    | (have r₁ := eq8 X0 X1
       have r₂ := eq11 X0 (M.op X1 X0)
       grind)
    | (have r₁ := eq8 X0 X1
       have r₂ := eq11 X0 X1
       grind)
    | exact resolve eq8 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq249 : ∀ X0 X1 : G, (M.op X1 X1) ≠ X1 ∨ (M.op X0 X1) = (N.op X1 X0) ∨ X0 = X1 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    first
    | (have j0 := eq11 X1 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq252 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X0 ∨ (M.op X0 X0) = (N.op X0 X1) ∨ (M.op X1 X0) = (N.op X0 X1) ∨ X0 = X1 := by
    intro X0 X1
    first
    | (have j0 := eq241 X0 X1
       have j1 := eq8 X0 X0
       grind)
    | (have r₁ := eq241 (M.op X1 X0) X0
       have r₂ := eq8 X0 X1
       grind)
    | (have r₁ := eq241 X0 (M.op X1 X0)
       have r₂ := eq8 X0 X1
       grind)
    | (have r₁ := eq241 X0 X1
       have r₂ := eq8 X0 X1
       grind)
    | exact resolve eq241 eq8
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq241
  have eq269 : ∀ X0 X1 X2 X3 X5 X6 : G, (M.op X3 X3) = (M.op (M.op (M.op (M.op X0 (M.op X1 X1)) X2) X5) X6) := by
    intro X0 X1 X2 X3 X5 X6
    first
    | (have i₁ := eq45 x X5 X3 X6
       have i₂ := eq17 X1 x X0 X2
       grind)
    | (have i₁ := eq45 (M.op X2 (M.op X0 X0)) X1 X2 x
       have i₂ := eq17 X0 X1 X2 (M.op X2 (M.op X0 X0))
       grind)
    | exact superpose eq17 eq45
    | exact resolve eq45 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq350 : ∀ X0 : G, x ≠ (N.op x (N.op (M.op X0 X0) x)) ∨ (M.op X0 X0) = y := by
    intro X0
    first
    | (have i₁ := eq68
       have i₂ := eq19 y x
       grind)
    | (have i₁ := eq68
       have i₂ := eq19 X0 y
       grind)
    | exact superpose eq19 eq68
    | exact resolve eq68 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq509 : ∀ X0 X1 X2 X3 X4 X6 X7 X8 X9 X10 : G, (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4) = (M.op (M.op X6 (M.op (M.op X7 (M.op X8 X7)) X9)) X10) := by
    intro X0 X1 X2 X3 X4 X6 X7 X8 X9 X10
    first
    | (have i₁ := eq16 X7 X8 X9 x X6 X10
       have i₂ := eq16 X1 X2 X3 x X0 X4
       grind)
    | (have i₁ := eq16 X0 X1 X2 (M.op X4 (M.op (M.op X0 (M.op X1 X0)) X2)) X4 x
       have i₂ := eq16 X0 X1 X2 X3 X4 (M.op X4 (M.op (M.op X0 (M.op X1 X0)) X2))
       grind)
    | exact superpose eq16 eq16
    | exact resolve eq16 eq16
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq543 : ∀ X0 X1 X2 X3 X4 X8 X9 : G, (M.op X3 X3) = (M.op (M.op X4 (M.op (M.op (M.op X0 (M.op X1 X0)) X2) X8)) X9) := by
    intro X0 X1 X2 X3 X4 X8 X9
    first
    | (have i₁ := eq16 (M.op x (M.op x x)) x X8 X3 X4 X9
       have i₂ := eq14 x x (M.op x (M.op x (M.op x x))) X0 X1 X2
       grind)
    | (have i₁ := eq16 (M.op x (M.op x x)) x X8 X3 X4 X9
       have i₂ := eq14 X0 X1 X2 x x (M.op x (M.op x (M.op x x)))
       grind)
    | exact superpose eq14 eq16
    | exact resolve eq16 eq14
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq14
  have eq626 : ∀ X0 X1 X2 X3 X4 X5 X7 : G, (M.op X5 X5) = (M.op (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4) X7) := by
    intro X0 X1 X2 X3 X4 X5 X7
    first
    | (have i₁ := eq45 x (M.op x x) X5 X7
       have i₂ := eq16 X1 X2 X3 (M.op x x) X0 X4
       grind)
    | (have i₁ := eq45 (M.op (M.op X0 (M.op X1 X0)) X2) X5 X2 X4
       have i₂ := eq16 X0 X1 X2 X3 (M.op (M.op X0 (M.op X1 X0)) X2) X5
       grind)
    | exact superpose eq16 eq45
    | exact resolve eq45 eq16
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq16 eq45
  have eq844 : ∀ X0 X1 X2 : G, (M.op (M.op X0 X0) (M.op X0 X0)) = (N.op (M.op X0 X0) (M.op X1 (M.op X2 X1))) := by
    intro X0 X1 X2
    first
    | (have j0 := eq38 X0 X1 X2 (M.op X0 X0)
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq38
  have eq1299 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 ∨ (M.op X1 X1) = (M.op X2 (M.op X1 X1)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq249 X2 (M.op X1 X1)
       have i₂ := eq18 X1 X0 (M.op X1 X1)
       grind)
    | (have i₁ := eq249 X0 X1
       have i₂ := eq18 X0 X1 x
       grind)
    | exact superpose eq18 eq249
    | (have j0 := eq249 X2 (M.op X1 X1)
       grind)
    | (have r₁ := eq249 X0 (M.op (M.op X0 X0) x)
       have r₂ := eq18 X0 (M.op (M.op X0 X0) x) x
       grind)
    | (have r₁ := eq249 X0 (M.op X1 X1)
       have r₂ := eq18 X1 X1 (M.op X1 X1)
       grind)
    | exact resolve eq249 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq249
  have eq1311 : ∀ X1 X2 : G, (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 ∨ (M.op X1 X1) = (M.op X2 (M.op X1 X1)) := by
    intro X1 X2
    first
    | (have j0 := eq1299 x X1 X2
       grind)
    | (have r₁ := eq1299 x X1 X2
       have r₂ := eq19 x X1
       grind)
    | (have r₁ := eq1299 X1 x X2
       have r₂ := eq19 x X1
       grind)
    | exact resolve eq1299 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1299
  have eq1949 : ∀ X0 X1 X4 X5 X6 : G, (N.op X0 (M.op X5 (M.op X6 X5))) = X0 ∨ (M.op X1 X1) = (M.op X0 X4) ∨ (M.op X5 (M.op X6 X5)) = X0 := by
    intro X0 X1 X4 X5 X6
    first
    | (have i₁ := eq102 x x (M.op x (M.op x x)) X1 X4
       have i₂ := eq134 (M.op x (M.op x x)) X0 X5 X6
       grind)
    | (have i₁ := eq102 X0 X1 x x X5
       have i₂ := eq134 X0 (M.op (M.op X0 (M.op X1 X1)) x) x x
       grind)
    | exact superpose eq134 eq102
    | (have j1 := eq134 X0 X0 X5 X6
       grind)
    | exact resolve eq102 eq134
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq102
  have eq2261 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ (M.op X1 X1) ∨ (M.op X0 X0) = (N.op (M.op X1 X1) X2) ∨ (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq252 X1 X1
       have i₂ := eq18 X0 X1 x
       grind)
    | (have i₁ := eq252 (M.op X0 X0) X1
       have i₂ := eq18 X0 X1 (M.op X0 X0)
       grind)
    | exact superpose eq18 eq252
    | (have j0 := eq252 (M.op X1 X1) X2
       grind)
    | (have r₁ := eq252 (M.op (M.op X0 X0) x) X1
       have r₂ := eq18 X0 (M.op (M.op X0 X0) x) x
       grind)
    | (have r₁ := eq252 (M.op X1 X1) X1
       have r₂ := eq18 X1 X1 (M.op X1 X1)
       grind)
    | exact resolve eq252 eq18
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq18 eq252
  have eq2278 : ∀ X0 X1 X2 : G, (M.op X2 (M.op X1 X1)) = (N.op (M.op X1 X1) X2) ∨ (M.op X0 X0) = (N.op (M.op X1 X1) X2) ∨ (M.op X1 X1) = X2 := by
    intro X0 X1 X2
    first
    | (have j0 := eq2261 X0 X1 X2
       grind)
    | (have r₁ := eq2261 X0 X1 X2
       have r₂ := eq19 X0 X1
       grind)
    | (have r₁ := eq2261 X1 X0 X2
       have r₂ := eq19 X0 X1
       grind)
    | exact resolve eq2261 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2261
  have eq2724 : ∀ X0 X1 : G, (M.op (M.op X0 X0) (M.op X0 X0)) = (N.op (M.op X0 X0) (M.op X1 X1)) := by
    intro X0 X1
    first
    | (have j0 := eq65 X0 X1 (M.op X0 X0)
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq7223 : ∀ X0 X1 X2 : G, (M.op X1 X1) ≠ (M.op X2 X2) ∨ (N.op X0 (M.op X2 X2)) = X0 ∨ (M.op X2 X2) = X0 := by
    intro X0 X1 X2
    first
    | (have j0 := eq132 X2 X0 X2
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq7235 : ∀ X0 X2 : G, (N.op X0 (M.op X2 X2)) = X0 ∨ (M.op X2 X2) = X0 := by
    intro X0 X2
    first
    | (have j0 := eq7223 X0 x X2
       grind)
    | (have r₁ := eq7223 X0 X0 x
       have r₂ := eq19 X0 x
       grind)
    | (have r₁ := eq7223 X0 x X0
       have r₂ := eq19 X0 x
       grind)
    | exact resolve eq7223 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq7223
  have eq8593 : ∀ X0 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11 : G, (M.op X6 X6) = (M.op (M.op X7 (M.op (M.op (M.op X8 (M.op (M.op X0 (M.op (M.op (M.op X1 (M.op X2 X1)) X3) X4)) X5)) X9) X10)) X11) := by
    intro X0 X1 X2 X3 X4 X5 X6 X7 X8 X9 X10 X11
    first
    | (have i₁ := eq543 X8 X8 X9 X6 X7 X10 X11
       have i₂ := eq543 X1 X2 X3 X8 X0 X4 X5
       grind)
    | (have i₁ := eq543 X9 (M.op X4 (M.op (M.op (M.op X0 (M.op X1 X0)) X2) X8)) X2 X3 X4 X8 X9
       have i₂ := eq543 X0 X1 X2 X3 X4 X8 X9
       grind)
    | exact superpose eq543 eq543
    | exact resolve eq543 eq543
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq543
  have eq10139 : ∀ X0 X1 X2 X3 : G, (M.op X3 X3) = (N.op (M.op X0 X0) (M.op X1 (M.op X2 X1))) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq19 X3 (M.op X0 X0)
       have i₂ := eq844 X0 X1 X2
       grind)
    | exact superpose eq844 eq19
    | exact resolve eq19 eq844
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq844
  have eq10390 : ∀ X0 X1 X2 X3 : G, (M.op X1 X1) = (N.op (M.op X2 X2) (M.op X3 (M.op X0 X0))) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq10139 X2 X3 (M.op (M.op (M.op x (M.op x x)) x) x) X1
       have i₂ := eq269 x x x X0 x X3
       grind)
    | (have i₁ := eq10139 X0 X3 X3 X3
       have i₂ := eq269 X0 X1 X2 X3 x x
       grind)
    | exact superpose eq269 eq10139
    | exact resolve eq10139 eq269
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq10430 : ∀ X0 X1 X2 : G, (M.op X1 X1) = (N.op (M.op X2 X2) (M.op X0 X0)) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq10139 X2 (M.op (M.op (M.op x (M.op x x)) x) x) x X1
       have i₂ := eq269 x x x X0 x (M.op x (M.op (M.op (M.op x (M.op x x)) x) x))
       grind)
    | exact superpose eq269 eq10139
    | exact resolve eq10139 eq269
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10139
  have eq11760 : ∀ X0 X1 X2 X3 X6 : G, (M.op (M.op X2 X2) X3) = (M.op (N.op (M.op X0 X0) (M.op X1 X1)) X6) := by
    intro X0 X1 X2 X3 X6
    first
    | (have i₁ := eq154 x x (M.op x (M.op x x)) X2 X3 X6
       have i₂ := eq10430 X1 (M.op x (M.op x x)) X0
       grind)
    | exact superpose eq10430 eq154
    | exact resolve eq154 eq10430
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq11778 : ∀ X0 X1 X2 X6 : G, (M.op X2 X2) = (M.op (N.op (M.op X0 X0) (M.op X1 X1)) X6) := by
    intro X0 X1 X2 X6
    first
    | (have i₁ := eq269 x x x X2 (M.op (M.op x (M.op x x)) x) X6
       have i₂ := eq10430 X1 (M.op (M.op x (M.op x x)) x) X0
       grind)
    | exact superpose eq10430 eq269
    | exact resolve eq269 eq10430
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq269
  have eq12766 : ∀ X0 X1 X2 X6 X7 : G, (M.op X2 X2) = (N.op (M.op (M.op X0 X0) X1) (M.op X6 (M.op X7 X7))) := by
    intro X0 X1 X2 X6 X7
    first
    | (have i₁ := eq10390 X7 X2 (M.op (M.op x (M.op x x)) x) X6
       have i₂ := eq154 x x x X0 X1 (M.op (M.op x (M.op x x)) x)
       grind)
    | (have i₁ := eq10390 X0 X1 (M.op x x) x
       have i₂ := eq154 X0 X1 X2 x (M.op x x) X6
       grind)
    | exact superpose eq154 eq10390
    | exact resolve eq10390 eq154
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq154 eq10390
  have eq17147 : ∀ X0 X1 X2 X3 X5 : G, (M.op X2 X2) = (M.op (N.op (M.op X3 X3) (N.op (M.op X0 X0) (M.op X1 X1))) X5) := by
    intro X0 X1 X2 X3 X5
    first
    | (have i₁ := eq11778 X3 x X2 X5
       have i₂ := eq10430 X1 x X0
       grind)
    | exact superpose eq10430 eq11778
    | exact resolve eq11778 eq10430
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq10430 eq11778
  have eq27861 : ∀ X0 X2 X3 : G, (M.op X0 X0) = (N.op X0 (M.op X2 X2)) ∨ (N.op X0 (M.op X3 X3)) = X0 ∨ (M.op X3 X3) = X0 := by
    intro X0 X2 X3
    first
    | (have i₁ := eq2724 X0 x
       have i₂ := eq132 X0 x X2
       grind)
    | (have i₁ := eq2724 X0 x
       have i₂ := eq132 X0 (M.op X0 X0) X2
       grind)
    | exact superpose eq132 eq2724
    | (have j1 := eq132 X3 X0 X3
       grind)
    | exact resolve eq2724 eq132
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq132 eq2724
  have eq28310 : ∀ X0 X2 X3 : G, (M.op X0 X0) = (N.op X0 (M.op X2 X2)) ∨ (N.op X0 (M.op X3 X3)) = X0 := by
    intro X0 X2 X3
    first
    | (have j0 := eq27861 X0 X2 X3
       have j1 := eq65 X0 X2 X0
       grind)
    | (have r₁ := eq27861 X0 X2 X3
       have r₂ := eq65 X0 x (N.op X0 (M.op X2 X2))
       grind)
    | (have r₁ := eq27861 (M.op X0 X0) X2 X3
       have r₂ := eq65 X0 x (N.op (M.op X0 X0) (M.op X3 X3))
       grind)
    | (have r₁ := eq27861 X2 X2 X0
       have r₂ := eq65 X0 x X2
       grind)
    | exact resolve eq27861 eq65
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq65 eq27861
  have eq55426 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op X1 (M.op X2 X2)) ∨ (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) ∨ (M.op X2 X2) = X1 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq1311 X2 X1
       have i₂ := eq2278 X0 X2 X1
       grind)
    | exact superpose eq2278 eq1311
    | (have j0 := eq1311 X2 X1
       have j1 := eq2278 X0 X2 X1
       grind)
    | exact resolve eq1311 eq2278
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1311
  have eq55470 : ∀ X0 X1 X2 : G, (M.op X2 X2) ≠ (M.op X1 (M.op X0 X0)) ∨ (M.op X1 (M.op X0 X0)) = (N.op (M.op X0 X0) X1) ∨ (M.op X0 X0) = X1 := by
    intro X0 X1 X2
    first
    | (have j0 := eq2278 X0 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq2278
  have eq55484 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op X1 (M.op X2 X2)) ∨ (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) := by
    intro X0 X1 X2
    first
    | (have j0 := eq55426 X0 X1 X2
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq55426
  have eq55512 : ∀ X1 X2 : G, (M.op X2 X2) = X1 ∨ (M.op X2 X2) = (M.op X1 (M.op X2 X2)) ∨ (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) := by
    intro X1 X2
    first
    | (have j0 := eq55484 X2 X1 X2
       have j1 := eq55470 X2 X1 X2
       grind)
    | (have r₁ := eq55484 X2 X1 x
       have r₂ := eq55470 x X1 X2
       grind)
    | (have r₁ := eq55484 (M.op x x) (M.op X2 X2) X2
       have r₂ := eq55470 x (M.op x x) (M.op X2 X2)
       grind)
    | (have r₁ := eq55484 x (M.op X1 (M.op x x)) X2
       have r₂ := eq55470 x X1 X2
       grind)
    | exact resolve eq55484 eq55470
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq55484
  have eq55518 : ∀ X1 X2 : G, (M.op X1 (M.op X2 X2)) = (N.op (M.op X2 X2) X1) ∨ (M.op X2 X2) = X1 := by
    intro X1 X2
    first
    | (have j0 := eq55512 X1 X2
       have j1 := eq55470 X2 X1 X2
       grind)
    | (have r₁ := eq55512 (M.op X1 (M.op x x)) X2
       have r₂ := eq55470 x X1 X2
       grind)
    | (have r₁ := eq55512 (M.op X2 X2) (M.op x x)
       have r₂ := eq55470 x (M.op x x) X2
       grind)
    | (have r₁ := eq55512 X1 x
       have r₂ := eq55470 x X1 x
       grind)
    | exact resolve eq55512 eq55470
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq55470 eq55512
  have eq85168 : ∀ X0 : G, x ≠ (N.op x (M.op x (M.op X0 X0))) ∨ (M.op X0 X0) = y ∨ (M.op X0 X0) = x := by
    intro X0
    first
    | (have i₁ := eq350 X0
       have i₂ := eq55518 x X0
       grind)
    | exact superpose eq55518 eq350
    | (have j0 := eq350 X0
       have j1 := eq55518 y X0
       grind)
    | exact resolve eq350 eq55518
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq350
  have eq87036 : ∀ X0 X1 X2 : G, (M.op X0 X0) = X0 ∨ (M.op X1 X1) = X0 ∨ (N.op X0 (M.op X2 X2)) = X0 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq7235 X0 X1
       have i₂ := eq28310 X0 X1 X2
       grind)
    | exact superpose eq28310 eq7235
    | (have j0 := eq7235 X0 X2
       have j1 := eq28310 X0 X2 X2
       grind)
    | exact resolve eq7235 eq28310
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq7235
  have eq87133 : ∀ X0 X1 : G, (M.op X0 X0) ≠ X0 ∨ (N.op X0 (M.op X1 X1)) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq28310 X0 x X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq28310
  have eq87163 : ∀ X0 X1 X2 : G, (M.op X1 X1) = X0 ∨ (N.op X0 (M.op X2 X2)) = X0 := by
    intro X0 X1 X2
    first
    | (have j0 := eq87036 X0 X1 X2
       have j1 := eq87133 X0 X2
       grind)
    | (have r₁ := eq87036 X0 X1 X2
       have r₂ := eq87133 X0 X1
       grind)
    | (have r₁ := eq87036 X0 X0 X2
       have r₂ := eq87133 X0 X1
       grind)
    | (have r₁ := eq87036 (M.op (M.op X1 X1) (M.op X1 X1)) X1 X2
       have r₂ := eq87133 (M.op X1 X1) X1
       grind)
    | exact resolve eq87036 eq87133
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq87036
  have eq87650 : ∀ X0 X1 X2 : G, (M.op X0 X0) ≠ X1 ∨ (N.op X1 (M.op X2 X2)) = X1 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq87133 X1 X2
       have i₂ := eq19 X1 X0
       grind)
    | (have i₁ := eq87133 X1 X2
       have i₂ := eq19 X0 X1
       grind)
    | exact superpose eq19 eq87133
    | (have j0 := eq87133 X1 X2
       grind)
    | (have r₁ := eq87133 (M.op X1 X1) X1
       have r₂ := eq19 (M.op X1 X1) X1
       grind)
    | (have r₁ := eq87133 (M.op X0 X0) X1
       have r₂ := eq19 X0 (M.op X0 X0)
       grind)
    | exact resolve eq87133 eq19
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq87133
  have eq87816 : ∀ X1 X2 : G, (N.op X1 (M.op X2 X2)) = X1 := by
    intro X1 X2
    first
    | (have j0 := eq87650 x X1 X2
       have j1 := eq87163 X1 X1 X2
       grind)
    | (have r₁ := eq87650 X1 x X2
       have r₂ := eq87163 x X1 X2
       grind)
    | (have r₁ := eq87650 x (M.op X1 X1) X2
       have r₂ := eq87163 (M.op x x) X1 X2
       grind)
    | (have r₁ := eq87650 x (N.op (M.op x x) (M.op X2 X2)) X2
       have r₂ := eq87163 (M.op x x) X1 X2
       grind)
    | exact resolve eq87650 eq87163
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq87163 eq87650
  have eq89855 : ∀ X0 X1 X2 X3 X4 X5 : G, (N.op X5 (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4)) = X5 := by
    intro X0 X1 X2 X3 X4 X5
    first
    | (have i₁ := eq87816 X5 (M.op x (M.op (M.op x (M.op x x)) x))
       have i₂ := eq509 x x x x (M.op x (M.op (M.op x (M.op x x)) x)) X0 X1 X2 X3 X4
       grind)
    | (have i₁ := eq87816 X5 (M.op x (M.op (M.op x (M.op x x)) x))
       have i₂ := eq509 X0 X1 X2 X3 X4 x x x x (M.op x (M.op (M.op x (M.op x x)) x))
       grind)
    | exact superpose eq509 eq87816
    | exact resolve eq87816 eq509
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq509
  have eq89887 : ∀ X0 X1 X2 : G, (N.op X2 (M.op (M.op X0 X0) X1)) = X2 := by
    intro X0 X1 X2
    first
    | (have i₁ := eq87816 X2 (N.op (M.op x x) (M.op x x))
       have i₂ := eq11760 x x X0 X1 (N.op (M.op x x) (M.op x x))
       grind)
    | exact superpose eq11760 eq87816
    | exact resolve eq87816 eq11760
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq11760
  have eq92183 : ∀ X0 X1 X2 X3 X4 X6 : G, (N.op X4 (M.op (N.op (M.op (M.op X0 X0) X1) (M.op X2 (M.op X3 X3))) X6)) = X4 := by
    intro X0 X1 X2 X3 X4 X6
    first
    | (have i₁ := eq89887 x X6 X4
       have i₂ := eq12766 X0 X1 x X2 X3
       grind)
    | exact superpose eq12766 eq89887
    | exact resolve eq89887 eq12766
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12766 eq89887
  have eq157387 : ∀ X0 X1 X2 X3 X4 X5 X6 : G, (M.op X0 X0) ≠ X6 ∨ (M.op X6 X6) = (N.op X6 (M.op (M.op X1 (M.op (M.op X2 (M.op X3 X2)) X4)) X5)) := by
    intro X0 X1 X2 X3 X4 X5 X6
    first
    | (have i₁ := eq8 X6 (M.op (M.op X1 (M.op (M.op X2 (M.op X3 X2)) X4)) X5)
       have i₂ := eq626 X1 X2 X3 X4 X5 X0 X6
       grind)
    | (have i₁ := eq8 X5 X5
       have i₂ := eq626 X0 X1 X2 X3 X4 X5 x
       grind)
    | exact superpose eq626 eq8
    | (have j0 := eq8 X6 (M.op (M.op X1 (M.op (M.op X2 (M.op X3 X2)) X4)) X5)
       grind)
    | (have r₁ := eq8 (M.op (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4) x) (M.op (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4) x)
       have r₂ := eq626 X0 X1 X2 X3 X4 (M.op (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4) x) x
       grind)
    | (have r₁ := eq8 (M.op X5 X5) (M.op (M.op X0 (M.op (M.op X1 (M.op X2 X1)) X3)) X4)
       have r₂ := eq626 X0 X1 X2 X3 X4 X5 (M.op X5 X5)
       grind)
    | exact resolve eq8 eq626
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq626
  have eq157711 : ∀ X0 X6 : G, (M.op X0 X0) ≠ X6 ∨ (M.op X6 X6) = X6 := by
    intro X0 X6
    first
    | (have i₁ := eq157387 X0 x x x x x X6
       have i₂ := eq89855 x x x x x X6
       grind)
    | exact superpose eq89855 eq157387
    | (have j0 := eq157387 X0 x x x x x X6
       grind)
    | (have r₁ := eq157387 X0 x x x x x (N.op (M.op X0 X0) (M.op (M.op X0 (M.op (M.op x (M.op x x)) x)) x))
       have r₂ := eq89855 X0 x x x x (M.op X0 X0)
       grind)
    | exact resolve eq157387 eq89855
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq89855 eq157387
  have eq665314 : ∀ X0 X1 X2 : G, (M.op X2 X2) ≠ X0 ∨ (N.op X0 (M.op X0 (M.op X1 X0))) = X0 ∨ (M.op X0 (M.op X1 X0)) = X0 := by
    intro X0 X1 X2
    first
    | (have j0 := eq1949 X0 X1 x X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1949
  have eq665315 : ∀ X0 X1 : G, (N.op X0 (M.op X0 (M.op X1 X0))) = X0 ∨ (M.op X0 (M.op X1 X0)) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq665314 X0 X1 x
       have j1 := eq134 X0 X0 X0 X1
       grind)
    | (have r₁ := eq665314 (N.op (M.op x x) (M.op x (M.op x x))) X1 x
       have r₂ := eq134 X0 (M.op x x) x x
       grind)
    | (have r₁ := eq665314 X1 X1 X0
       have r₂ := eq134 X0 X1 x x
       grind)
    | (have r₁ := eq665314 (M.op X0 X0) X1 x
       have r₂ := eq134 X0 (M.op x x) x x
       grind)
    | exact resolve eq665314 eq134
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq134 eq665314
  have eq665426 : ∀ X0 X1 : G, (N.op X1 (M.op X1 (M.op X0 X0))) = X1 ∨ (M.op X1 (M.op X0 X0)) = X1 := by
    intro X0 X1
    first
    | (have i₁ := eq665315 x x
       have i₂ := eq17147 X0 X1 x x x
       grind)
    | (have i₁ := eq665315 x (N.op (M.op x x) (N.op (M.op X0 X0) (M.op X1 X1)))
       have i₂ := eq17147 X0 X1 x x x
       grind)
    | exact superpose eq17147 eq665315
    | exact resolve eq665315 eq17147
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq17147 eq665315
  have eq1223179 : ∀ X0 : G, x ≠ x ∨ (M.op X0 X0) = y ∨ (M.op X0 X0) = x ∨ x = (M.op x (M.op X0 X0)) := by
    intro X0
    first
    | (have i₁ := eq85168 X0
       have i₂ := eq665426 X0 x
       grind)
    | exact superpose eq665426 eq85168
    | (have j0 := eq85168 X0
       have j1 := eq665426 X0 x
       grind)
    | (have r₁ := eq85168 X0
       have r₂ := eq665426 X0 x
       grind)
    | exact resolve eq85168 eq665426
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq85168
  have eq1223180 : ∀ X0 : G, x = (M.op x (M.op X0 X0)) ∨ (M.op X0 X0) = x ∨ (M.op X0 X0) = y := by
    intro X0
    first
    | (have j0 := eq1223179 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1223179
  have eq1223320 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op x X2) ∨ y = (M.op X1 X1) ∨ x = (M.op X1 X1) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq17 X1 X0 x X2
       have i₂ := eq1223180 X1
       grind)
    | exact superpose eq1223180 eq17
    | (have j1 := eq1223180 X1
       grind)
    | exact resolve eq17 eq1223180
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1224505 : ∀ X0 X1 X2 X3 : G, (M.op X0 X0) = y ∨ (M.op X2 X2) = (M.op x X3) ∨ x = (M.op X1 X1) := by
    intro X0 X1 X2 X3
    first
    | (have i₁ := eq19 X0 X1
       have i₂ := eq1223320 X2 X1 X3
       grind)
    | exact superpose eq1223320 eq19
    | (have j1 := eq1223320 X2 X0 X3
       grind)
    | exact resolve eq19 eq1223320
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1223320
  have eq1229267 : ∀ X0 X1 X2 : G, x ≠ (M.op x X1) ∨ y = (M.op X2 X2) ∨ (M.op X0 X0) = x := by
    intro X0 X1 X2
    first
    | (have j0 := eq1224505 X2 X0 X2 x
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1224505
  have eq1274635 : ∀ X0 : G, x = (M.op x (M.op X0 X0)) ∨ (M.op X0 X0) = x ∨ (M.op X0 X0) = y := by
    intro X0
    first
    | (have i₁ := eq1223180 x
       have i₂ := eq8593 X0 x x x x x x x x x x x
       grind)
    | (have i₁ := eq1223180 (M.op x (M.op (M.op (M.op x (M.op (M.op X0 (M.op (M.op (M.op x (M.op x x)) x) x)) x)) x) x))
       have i₂ := eq8593 X0 x x x x x x x x x x (M.op x (M.op (M.op (M.op x (M.op (M.op X0 (M.op (M.op (M.op x (M.op x x)) x) x)) x)) x) x))
       grind)
    | exact superpose eq8593 eq1223180
    | (have j0 := eq1223180 X0
       grind)
    | exact resolve eq1223180 eq8593
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq8593 eq1223180
  have eq1275682 : ∀ X0 : G, (M.op X0 X0) = y ∨ (M.op X0 X0) = x := by
    intro X0
    first
    | (have j0 := eq1274635 X0
       have j1 := eq1229267 X0 x X0
       grind)
    | (have r₁ := eq1274635 X0
       have r₂ := eq1229267 X0 (M.op X0 X0) x
       grind)
    | (have r₁ := eq1274635 x
       have r₂ := eq1229267 X0 x x
       grind)
    | exact resolve eq1274635 eq1229267
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1229267 eq1274635
  have eq1275985 : ∀ X0 X1 : G, (M.op X0 X0) = y ∨ x = (M.op X1 X1) := by
    intro X0 X1
    first
    | (have i₁ := eq19 X0 X1
       have i₂ := eq1275682 X1
       grind)
    | exact superpose eq1275682 eq19
    | (have j1 := eq1275682 X0
       grind)
    | exact resolve eq19 eq1275682
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1275682
  have eq1288212 : ∀ X0 X5 : G, (N.op X0 x) = X0 ∨ y = (M.op X5 X5) := by
    intro X0 X5
    first
    | (have i₁ := eq92183 x x x x X0 (N.op (M.op (M.op x x) x) (M.op x (M.op x x)))
       have i₂ := eq1275985 X5 (N.op (M.op (M.op x x) x) (M.op x (M.op x x)))
       grind)
    | exact superpose eq1275985 eq92183
    | (have j1 := eq1275985 X5 x
       grind)
    | exact resolve eq92183 eq1275985
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq92183 eq1275985
  have eq1292620 : ∀ X0 : G, x ≠ (N.op x (M.op y y)) ∨ y = (M.op y y) ∨ (M.op X0 X0) = y := by
    intro X0
    first
    | (have i₁ := eq68
       have i₂ := eq1288212 (M.op y y) X0
       grind)
    | exact superpose eq1288212 eq68
    | (have j1 := eq1288212 X0 y
       grind)
    | exact resolve eq68 eq1288212
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq68 eq1288212
  have eq1294603 : x ≠ (N.op x (M.op y y)) ∨ y = (M.op y y) := by
    first
    | (have j0 := eq1292620 y
       have j1 := eq157711 x y
       grind)
    | (have r₁ := eq1292620 x
       have r₂ := eq157711 y y
       grind)
    | (have r₁ := eq1292620 x
       have r₂ := eq157711 x y
       grind)
    | exact resolve eq1292620 eq157711
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq157711 eq1292620
  have eq1294671 : y = (M.op y y) := by
    first
    | (have r₁ := eq1294603
       have r₂ := eq87816 x y
       grind)
    | exact resolve eq1294603 eq87816
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1294603
  have eq1294693 : ∀ X0 X1 X2 : G, (M.op X0 X0) = (M.op (M.op X1 y) X2) := by
    intro X0 X1 X2
    first
    | (have i₁ := eq17 y X0 X1 X2
       have i₂ := eq1294671
       grind)
    | exact superpose eq1294671 eq17
    | exact resolve eq17 eq1294671
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq17
  have eq1294696 : ∀ X0 : G, (M.op X0 X0) = y := by
    intro X0
    first
    | (have i₁ := eq19 X0 y
       have i₂ := eq1294671
       grind)
    | exact superpose eq1294671 eq19
    | exact resolve eq19 eq1294671
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq1295317 : ∀ X0 : G, (M.op X0 y) = (N.op y X0) ∨ y = X0 := by
    intro X0
    first
    | (have i₁ := eq55518 x y
       have i₂ := eq1294671
       grind)
    | exact superpose eq1294671 eq55518
    | exact resolve eq55518 eq1294671
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq55518
  have eq1295362 : ∀ X0 : G, (N.op X0 y) = X0 := by
    intro X0
    first
    | (have i₁ := eq87816 X0 y
       have i₂ := eq1294671
       grind)
    | exact superpose eq1294671 eq87816
    | exact resolve eq87816 eq1294671
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq87816
  have eq1295441 : ∀ X0 : G, (N.op X0 (M.op X0 y)) = X0 ∨ (M.op X0 y) = X0 := by
    intro X0
    first
    | (have i₁ := eq665426 y x
       have i₂ := eq1294671
       grind)
    | exact superpose eq1294671 eq665426
    | exact resolve eq665426 eq1294671
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq665426 eq1294671
  have eq1295977 : ∀ X1 X2 : G, y = (M.op (M.op X1 y) X2) := by
    intro X1 X2
    first
    | (have i₁ := eq1294693 x X1 X2
       have i₂ := eq1294696 x
       grind)
    | exact superpose eq1294696 eq1294693
    | exact resolve eq1294693 eq1294696
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1294693 eq1294696
  have eq1303952 : x ≠ (N.op x (N.op y x)) := by
    first
    | (have i₁ := eq12
       have i₂ := eq1295362 y
       grind)
    | exact superpose eq1295362 eq12
    | exact resolve eq12 eq1295362
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1374826 : x ≠ (N.op x (M.op x y)) ∨ x = y := by
    first
    | (have i₁ := eq1303952
       have i₂ := eq1295317 x
       grind)
    | exact superpose eq1295317 eq1303952
    | (have j1 := eq1295317 x
       grind)
    | exact resolve eq1303952 eq1295317
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1295317
  have eq1486903 : x ≠ x ∨ x = y ∨ x = (M.op x y) := by
    first
    | (have i₁ := eq1374826
       have i₂ := eq1295441 x
       grind)
    | exact superpose eq1295441 eq1374826
    | (have j1 := eq1295441 x
       grind)
    | (have r₁ := eq1374826
       have r₂ := eq1295441 x
       grind)
    | exact resolve eq1374826 eq1295441
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1295441 eq1374826
  have eq1486906 : x = (M.op x y) ∨ x = y := by grind
  clear eq1486903
  have eq1486946 : ∀ X0 : G, y = (M.op x X0) ∨ x = y := by
    intro X0
    first
    | (have i₁ := eq1295977 x X0
       have i₂ := eq1486906
       grind)
    | exact superpose eq1486906 eq1295977
    | exact resolve eq1295977 eq1486906
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1295977
  have eq1487171 : x = y ∨ x = y ∨ x = y := by
    first
    | (have i₁ := eq1486906
       have i₂ := eq1486946 y
       grind)
    | exact superpose eq1486946 eq1486906
    | exact resolve eq1486906 eq1486946
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1486906 eq1486946
  have eq1488448 : x = y := by grind
  clear eq1487171
  have eq1489031 : ∀ X0 : G, (N.op X0 x) = X0 := by
    intro X0
    first
    | (have i₁ := eq1295362 X0
       have i₂ := eq1488448
       grind)
    | exact superpose eq1488448 eq1295362
    | exact resolve eq1295362 eq1488448
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1488448
  have eq1489136 : x ≠ (N.op x y) := by
    first
    | (have i₁ := eq1303952
       have i₂ := eq1489031 y
       grind)
    | exact superpose eq1489031 eq1303952
    | exact resolve eq1303952 eq1489031
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1303952 eq1489031
  have eq1489141 : False := by grind
  exact eq1489141
