import equational_theories.Definability.AutBox3
import equational_theories.Definability.Lw6_00

/-!
# Structurality from `Equation2290` through a three-guard companion, by replay

Generated by `defwork/itautcreplay3.py`.  `Equation2290` is `x = (y ◇ (x ◇ (x ◇ x))) ◇ x`, and the companion is
`x □ y = if (M.op a b) = b then (M.op b a) else if (M.op b a) = a then a else if (M.op a b) = a then b else (M.op a b)`.  Its automorphism half is `GuardAut3_pxy_y_pyx_x_pxy_x_pyx_x_y_pxy_Equation2290`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches it on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation1020` from `Equation2290`: `x = (y ◇ (x ◇ (x ◇ x))) ◇ x` ⊢ `x = x ◇ ((x ◇ (x ◇ x)) ◇ x)`, through the
companion `x □ y = if (M.op a b) = b then (M.op b a) else if (M.op b a) = a then a else if (M.op a b) = a then b else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation1020_StructuralFromFin_Equation2290 : Law1020.StructuralFromFin Law2290 := by
  classical
  refine AutBox.structuralFromFin_iteOf3 ((Lf 0) ⋆ (Lf 1)) (Lf 1) ((Lf 1) ⋆ (Lf 0)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 1))
    GuardAut3_pxy_y_pyx_x_pxy_x_pyx_x_y_pxy_Equation2290 (fun {G} M hM ↦ ?_)
  have hm := (@Law2290.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ b ∨ N.op a b = (M.op b a)) →
      (∀ a b : G, (M.op a b) = b ∨ (M.op b a) ≠ a ∨ N.op a b = a) →
      (∀ a b : G, (M.op a b) = b ∨ (M.op b a) = a ∨ (M.op a b) ≠ a ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = b ∨ (M.op b a) = a ∨ (M.op a b) = a ∨ N.op a b = (M.op a b)) →
        @satisfies _ G N Law1020 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) ((Lf 1) ⋆ (Lf 0)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) ((Lf 1) ⋆ (Lf 0)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne ((M.op b a)) (a)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) ((Lf 1) ⋆ (Lf 0)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne ((M.op b a)) (a)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a b)) (a)).symm.imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_pos hg3))))
    · rw [AutBox.iteOf3_apply ((Lf 0) ⋆ (Lf 1)) (Lf 1) ((Lf 1) ⋆ (Lf 0)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 1) ⋆ (Lf 0)) (Lf 0) (Lf 1) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (b)).imp id (fun hg ↦
        (eq_or_ne ((M.op b a)) (a)).imp id (fun hg2 ↦
          (eq_or_ne ((M.op a b)) (a)).imp id (fun hg3 ↦
            ((if_neg hg).trans (if_neg hg2)).trans (if_neg hg3))))
  intro N ht hu hv hw
  rw [@Law1020.models_iff G N]
  intro x
  by_contra nh
  have eq7 : ∀ X0 X1 : G, (M.op (M.op X1 (M.op X0 (M.op X0 X0))) X0) = X0 := by
    intro X0 X1
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (N.op X0 X1) = (M.op X1 X0) := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X1 X0) ≠ X0 ∨ (M.op X0 X1) = X1 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq11 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X1 X0) = X0 ∨ (M.op X0 X1) = X0 ∨ (M.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq12 : x ≠ (N.op x (N.op (N.op x (N.op x x)) x)) := by grind
  clear hm ht hu hv hw nh hM
  have eq13 : ∀ X0 : G, (M.op (M.op X0 (M.op X0 X0)) X0) = X0 := by
    intro X0
    first
    | (have i₁ := eq7 X0 (M.op x (M.op (M.op X0 (M.op X0 X0)) (M.op (M.op X0 (M.op X0 X0)) (M.op X0 (M.op X0 X0)))))
       have i₂ := eq7 (M.op X0 (M.op X0 X0)) x
       grind)
    | exact superpose eq7 eq7
    | exact resolve eq7 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq16 : ∀ X0 : G, X0 ≠ X0 ∨ (N.op (M.op X0 (M.op X0 X0)) X0) = (M.op X0 (M.op X0 (M.op X0 X0))) := by
    intro X0
    first
    | (have i₁ := eq8 (M.op X0 (M.op X0 X0)) X0
       have i₂ := eq13 X0
       grind)
    | exact superpose eq13 eq8
    | (have j0 := eq8 (M.op X0 (M.op X0 X0)) X0
       grind)
    | (have r₁ := eq8 (M.op X0 (M.op X0 X0)) X0
       have r₂ := eq13 X0
       grind)
    | exact resolve eq8 eq13
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq17 : ∀ X0 : G, (N.op (M.op X0 (M.op X0 X0)) X0) = (M.op X0 (M.op X0 (M.op X0 X0))) := by
    intro X0
    first
    | (have j0 := eq16 X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq16
  have eq19 : ∀ X0 X1 : G, X0 ≠ X0 ∨ (M.op X1 (M.op X0 (M.op X0 X0))) = (M.op X0 (M.op X1 (M.op X0 (M.op X0 X0)))) ∨ (N.op X0 (M.op X1 (M.op X0 (M.op X0 X0)))) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq9 X0 (M.op X1 (M.op X0 (M.op X0 X0)))
       have i₂ := eq7 X0 X1
       grind)
    | exact superpose eq7 eq9
    | (have j0 := eq9 X0 (M.op X1 (M.op X0 (M.op X0 X0)))
       grind)
    | (have r₁ := eq9 X0 (M.op X1 (M.op X0 (M.op X0 X0)))
       have r₂ := eq7 X0 X1
       grind)
    | exact resolve eq9 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq22 : ∀ X0 X1 : G, (N.op X0 (M.op X1 (M.op X0 (M.op X0 X0)))) = X0 ∨ (M.op X1 (M.op X0 (M.op X0 X0))) = (M.op X0 (M.op X1 (M.op X0 (M.op X0 X0)))) := by
    intro X0 X1
    first
    | (have j0 := eq19 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq26 : x ≠ (N.op x (N.op (N.op x (M.op x x)) x)) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq12
       have i₂ := eq11 x x
       grind)
    | exact superpose eq11 eq12
    | (have j1 := eq11 x x
       grind)
    | exact resolve eq12 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq29 : x ≠ (N.op x (N.op (N.op x (M.op x x)) x)) ∨ x = (M.op x x) := by grind
  clear eq26
  have eq30 : x ≠ (N.op x (N.op (M.op x (M.op x x)) x)) ∨ x = (M.op x x) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq29
       have i₂ := eq11 x (M.op x x)
       grind)
    | exact superpose eq11 eq29
    | (have j1 := eq11 x x
       grind)
    | exact resolve eq29 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq31 : x ≠ (N.op x (M.op (N.op x (M.op x x)) x)) ∨ x = (M.op x x) ∨ (N.op x (M.op x x)) = (M.op x (N.op x (M.op x x))) ∨ (N.op x (M.op x x)) = (M.op (N.op x (M.op x x)) x) ∨ x = (M.op (N.op x (M.op x x)) x) := by
    first
    | (have i₁ := eq29
       have i₂ := eq11 (N.op x (M.op x x)) x
       grind)
    | exact superpose eq11 eq29
    | (have j1 := eq11 x x
       grind)
    | exact resolve eq29 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq33 : x ≠ (N.op x (M.op x (M.op x (M.op x x)))) ∨ x = (M.op x x) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq30
       have i₂ := eq17 x
       grind)
    | exact superpose eq17 eq30
    | exact resolve eq30 eq17
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq30
  have eq57 : x ≠ x ∨ x = (M.op x x) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ (M.op x (M.op x (M.op x x))) = (M.op x (M.op x (M.op x (M.op x x)))) := by
    first
    | (have i₁ := eq33
       have i₂ := eq22 x x
       grind)
    | exact superpose eq22 eq33
    | (have j1 := eq22 x x
       grind)
    | (have r₁ := eq33
       have r₂ := eq22 x x
       grind)
    | exact resolve eq33 eq22
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq22
  have eq59 : (M.op x (M.op x (M.op x x))) = (M.op x (M.op x (M.op x (M.op x x)))) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq57
  have eq63 : (M.op x (M.op x (M.op x x))) ≠ (M.op x (M.op x (M.op x x))) ∨ (N.op x (M.op x (M.op x (M.op x x)))) = (M.op (M.op x (M.op x (M.op x x))) x) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq8 x (M.op x (M.op x (M.op x x)))
       have i₂ := eq59
       grind)
    | exact superpose eq59 eq8
    | (have j0 := eq8 x (M.op x (M.op x (M.op x x)))
       grind)
    | (have r₁ := eq8 x (M.op x (M.op x (M.op x x)))
       have r₂ := eq59
       grind)
    | (have r₁ := eq8 (M.op x x) x
       have r₂ := eq59
       grind)
    | (have r₁ := eq8 x (M.op x x)
       have r₂ := eq59
       grind)
    | exact resolve eq8 eq59
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq59
  have eq64 : (N.op x (M.op x (M.op x (M.op x x)))) = (M.op (M.op x (M.op x (M.op x x))) x) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq63
  have eq66 : x = (N.op x (M.op x (M.op x (M.op x x)))) ∨ x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq64
       have i₂ := eq7 x x
       grind)
    | exact superpose eq7 eq64
    | exact resolve eq64 eq7
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq64
  have eq67 : x = (M.op (M.op x x) x) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have r₁ := eq66
       have r₂ := eq33
       grind)
    | exact resolve eq66 eq33
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq33 eq66
  have eq71 : x ≠ x ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (N.op x (M.op x x)) ∨ x = (M.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq9 x (M.op x x)
       have i₂ := eq67
       grind)
    | exact superpose eq67 eq9
    | (have j0 := eq9 x (M.op x x)
       grind)
    | (have r₁ := eq9 x (M.op x x)
       have r₂ := eq67
       grind)
    | (have r₁ := eq9 (M.op x x) x
       have r₂ := eq67
       grind)
    | (have r₁ := eq9 x x
       have r₂ := eq67
       grind)
    | exact resolve eq9 eq67
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq67
  have eq74 : x ≠ x ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (N.op x (M.op x x)) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq71
  have eq75 : x = (N.op x (M.op x x)) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq74
  have eq77 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq31
       have i₂ := eq75
       grind)
    | exact superpose eq75 eq31
    | exact resolve eq31 eq75
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq31
  have eq82 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) ∨ (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq77
  have eq84 : (M.op x x) = (M.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have r₁ := eq82
       have r₂ := eq75
       grind)
    | exact resolve eq82 eq75
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq75 eq82
  have eq89 : x = (M.op (M.op x x) x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq13 x
       have i₂ := eq84
       grind)
    | exact superpose eq84 eq13
    | exact resolve eq13 eq84
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq92 : (M.op x x) ≠ (M.op x x) ∨ (N.op x (M.op x x)) = (M.op (M.op x x) x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq8 x (M.op x x)
       have i₂ := eq84
       grind)
    | exact superpose eq84 eq8
    | (have j0 := eq8 x (M.op x x)
       grind)
    | (have r₁ := eq8 x (M.op x x)
       have r₂ := eq84
       grind)
    | (have r₁ := eq8 x x
       have r₂ := eq84
       grind)
    | exact resolve eq8 eq84
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq84
  have eq94 : (N.op x (M.op x x)) = (M.op (M.op x x) x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq92
  have eq121 : x ≠ (N.op x (N.op (M.op (M.op x x) x) x)) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq29
       have i₂ := eq94
       grind)
    | exact superpose eq94 eq29
    | exact resolve eq29 eq94
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq29
  have eq124 : x ≠ (N.op x (N.op (M.op (M.op x x) x) x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq121
  have eq135 : x ≠ (N.op x (N.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq124
       have i₂ := eq89
       grind)
    | exact superpose eq89 eq124
    | exact resolve eq124 eq89
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq124
  have eq140 : x ≠ (N.op x (N.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq135
  have eq153 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq140
       have i₂ := eq11 x x
       grind)
    | exact superpose eq11 eq140
    | (have j1 := eq11 x x
       grind)
    | exact resolve eq140 eq11
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq140
  have eq155 : x ≠ (N.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq153
  have eq164 : x ≠ (M.op (M.op x x) x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by
    first
    | (have i₁ := eq155
       have i₂ := eq94
       grind)
    | exact superpose eq94 eq155
    | exact resolve eq155 eq94
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq94 eq155
  have eq170 : x ≠ (M.op (M.op x x) x) ∨ x = (M.op x x) ∨ x = (M.op x (M.op x x)) := by grind
  clear eq164
  have eq171 : x = (M.op x (M.op x x)) ∨ x = (M.op x x) := by
    first
    | (have r₁ := eq170
       have r₂ := eq89
       grind)
    | exact resolve eq170 eq89
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq89 eq170
  have eq181 : (N.op x x) = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq17 x
       have i₂ := eq171
       grind)
    | exact superpose eq171 eq17
    | exact resolve eq17 eq171
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq17
  have eq182 : x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq13 x
       have i₂ := eq171
       grind)
    | exact superpose eq171 eq13
    | exact resolve eq13 eq171
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq13 eq171
  have eq189 : x = (M.op x x) := by grind
  clear eq182
  have eq192 : (N.op x x) = (M.op x x) := by
    first
    | (have j1 := eq8 x x
       grind)
    | (have r₁ := eq181
       have r₂ := eq8 x x
       grind)
    | exact resolve eq181 eq8
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq181
  have eq193 : x = (N.op x x) := by
    first
    | (have i₁ := eq192
       have i₂ := eq189
       grind)
    | exact superpose eq189 eq192
    | exact resolve eq192 eq189
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq189 eq192
  have eq211 : x ≠ (N.op x (N.op (N.op x x) x)) := by
    first
    | (have i₁ := eq12
       have i₂ := eq193
       grind)
    | exact superpose eq193 eq12
    | exact resolve eq12 eq193
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq223 : x ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq211
       have i₂ := eq193
       grind)
    | exact superpose eq193 eq211
    | exact resolve eq211 eq193
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq211
  have eq225 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq223
       have i₂ := eq193
       grind)
    | exact superpose eq193 eq223
    | exact resolve eq223 eq193
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq223
  have eq227 : False := by grind
  exact eq227
