import equational_theories.Definability.AutBox2
import equational_theories.Definability.Lw_00

/-!
# Structurality from `Equation2623` through a two-guard companion, by replay

Generated by `defwork/itautcreplay2.py`.  `Equation2623` is `x = (y ◇ ((z ◇ w) ◇ y)) ◇ x`, and the companion is
`x □ y = if (M.op a b) = a then b else if (M.op a b) = b then a else (M.op a b)`.  Its automorphism half is `GuardAut2_pxy_x_pxy_y_y_x_pxy_Equation2623`, proved
elsewhere; each cell below is one more law the companion satisfies, written out one superposition
step at a time because `grind` reaches none of these on its own.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation3660` from `Equation2623`: `x = (y ◇ ((z ◇ w) ◇ y)) ◇ x` ⊢ `x ◇ x = (x ◇ x) ◇ (x ◇ y)`, through the
companion `x □ y = if (M.op a b) = a then b else if (M.op a b) = b then a else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation3660_StructuralFromFin_Equation2623 : Law3660.StructuralFromFin Law2623 := by
  classical
  refine AutBox.structuralFromFin_iteOf2 ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1))
    GuardAut2_pxy_x_pxy_y_y_x_pxy_Equation2623 (fun {G} M hM ↦ ?_)
  have hm := (@Law2623.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ a ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) ≠ b ∨ N.op a b = a) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law3660 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).imp id (fun hg2 ↦ (if_neg hg).trans (if_neg hg2)))
  intro N ht hu hv
  rw [@Law3660.models_iff G N]
  intro x y
  by_contra nh
  have eq6 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X1 (M.op (M.op X2 X3) X1)) X0) = X0 := by
    intro X0 X1 X2 X3
    grind
  have eq7 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X0 ∨ (N.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (M.op X0 X1) = X0 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = X1 ∨ (M.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq10 : (N.op x x) ≠ (N.op (N.op x x) (N.op x y)) := by grind
  clear hm ht hu hv nh hM
  have eq12 : ∀ X0 X4 : G, (M.op (M.op X0 X0) X4) = X4 := by
    intro X0 X4
    first
    | (have i₁ := eq6 X4 X0 x (M.op (M.op x x) x)
       have i₂ := eq6 X0 x x x
       grind)
    | exact superpose eq6 eq6
    | exact resolve eq6 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq19 : ∀ X0 X1 : G, (M.op X1 X1) ≠ X0 ∨ (N.op (M.op X1 X1) X0) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq7 (M.op X1 X1) X0
       have i₂ := eq12 X1 X0
       grind)
    | exact superpose eq12 eq7
    | (have j0 := eq7 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq7 (M.op X0 X0) (M.op X0 X0)
       have r₂ := eq12 X0 (M.op X0 X0)
       grind)
    | exact resolve eq7 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq34 : ∀ X0 X1 : G, X0 ≠ X0 ∨ (M.op X1 X1) = X0 ∨ (M.op X1 X1) = (N.op (M.op X1 X1) X0) := by
    intro X0 X1
    first
    | (have i₁ := eq8 (M.op X0 X0) x
       have i₂ := eq12 X0 x
       grind)
    | exact superpose eq12 eq8
    | (have j0 := eq8 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq8 (M.op X0 X0) x
       have r₂ := eq12 X0 x
       grind)
    | exact resolve eq8 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12
  have eq35 : ∀ X0 X1 : G, (M.op X1 X1) = (N.op (M.op X1 X1) X0) ∨ (M.op X1 X1) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq34 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq34
  have eq55 : (M.op x x) ≠ (N.op (M.op x x) (N.op x y)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq10
       have i₂ := eq9 x x
       grind)
    | exact superpose eq9 eq10
    | (have j1 := eq9 x x
       grind)
    | exact resolve eq10 eq9
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq58 : (M.op x x) ≠ (N.op (M.op x x) (N.op x y)) ∨ x = (M.op x x) := by grind
  clear eq55
  have eq250 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) (M.op X0 X0)) := by
    intro X0
    first
    | (have j0 := eq19 (M.op X0 X0) X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq417 : (M.op x x) ≠ (M.op x x) ∨ x = (M.op x x) ∨ (N.op x y) = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq35 (N.op x y) x
       grind)
    | exact superpose eq35 eq58
    | (have j1 := eq35 x x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op x y) x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op (M.op x x) (N.op x y)) x
       grind)
    | exact resolve eq58 eq35
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq420 : (N.op x y) = (M.op x x) ∨ x = (M.op x x) := by grind
  clear eq417
  have eq423 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq420
       grind)
    | exact superpose eq420 eq58
    | exact resolve eq58 eq420
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq58 eq420
  have eq426 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq423
  have eq427 : x = (M.op x x) := by
    first
    | (have r₁ := eq426
       have r₂ := eq250 x
       grind)
    | exact resolve eq426 eq250
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq426
  have eq464 : ∀ X0 : G, x = (N.op x X0) ∨ x = X0 := by
    intro X0
    first
    | (have i₁ := eq35 X0 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq35
    | exact resolve eq35 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq35
  have eq467 : x = (N.op x x) := by
    first
    | (have i₁ := eq250 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq250
    | exact resolve eq250 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq250 eq427
  have eq649 : x ≠ (N.op x (N.op x y)) := by
    first
    | (have i₁ := eq10
       have i₂ := eq467
       grind)
    | exact superpose eq467 eq10
    | exact resolve eq10 eq467
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1019 : x ≠ (N.op x x) ∨ x = y := by
    first
    | (have i₁ := eq649
       have i₂ := eq464 y
       grind)
    | exact superpose eq464 eq649
    | (have j1 := eq464 y
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op x y)
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op x (N.op x y))
       grind)
    | exact resolve eq649 eq464
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq464
  have eq1030 : x = y := by
    first
    | (have r₁ := eq1019
       have r₂ := eq467
       grind)
    | exact resolve eq1019 eq467
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1019
  have eq1136 : x ≠ (N.op x (N.op x x)) := by
    first
    | (have i₁ := eq649
       have i₂ := eq1030
       grind)
    | exact superpose eq1030 eq649
    | exact resolve eq649 eq1030
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq649 eq1030
  have eq1139 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq1136
       have i₂ := eq467
       grind)
    | exact superpose eq467 eq1136
    | exact resolve eq1136 eq467
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq1136
  have eq1141 : False := by grind
  exact eq1141

/-- `Equation3661` from `Equation2623`: `x = (y ◇ ((z ◇ w) ◇ y)) ◇ x` ⊢ `x ◇ x = (x ◇ x) ◇ (y ◇ x)`, through the
companion `x □ y = if (M.op a b) = a then b else if (M.op a b) = b then a else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation3661_StructuralFromFin_Equation2623 : Law3661.StructuralFromFin Law2623 := by
  classical
  refine AutBox.structuralFromFin_iteOf2 ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1))
    GuardAut2_pxy_x_pxy_y_y_x_pxy_Equation2623 (fun {G} M hM ↦ ?_)
  have hm := (@Law2623.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ a ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) ≠ b ∨ N.op a b = a) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law3661 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).imp id (fun hg2 ↦ (if_neg hg).trans (if_neg hg2)))
  intro N ht hu hv
  rw [@Law3661.models_iff G N]
  intro x y
  by_contra nh
  have eq6 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X1 (M.op (M.op X2 X3) X1)) X0) = X0 := by
    intro X0 X1 X2 X3
    grind
  have eq7 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X0 ∨ (N.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (M.op X0 X1) = X0 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = X1 ∨ (M.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq10 : (N.op x x) ≠ (N.op (N.op x x) (N.op y x)) := by grind
  clear hm ht hu hv nh hM
  have eq12 : ∀ X0 X4 : G, (M.op (M.op X0 X0) X4) = X4 := by
    intro X0 X4
    first
    | (have i₁ := eq6 X4 X0 x (M.op (M.op x x) x)
       have i₂ := eq6 X0 x x x
       grind)
    | exact superpose eq6 eq6
    | exact resolve eq6 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq19 : ∀ X0 X1 : G, (M.op X1 X1) ≠ X0 ∨ (N.op (M.op X1 X1) X0) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq7 (M.op X1 X1) X0
       have i₂ := eq12 X1 X0
       grind)
    | exact superpose eq12 eq7
    | (have j0 := eq7 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq7 (M.op X0 X0) (M.op X0 X0)
       have r₂ := eq12 X0 (M.op X0 X0)
       grind)
    | exact resolve eq7 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq34 : ∀ X0 X1 : G, X0 ≠ X0 ∨ (M.op X1 X1) = X0 ∨ (M.op X1 X1) = (N.op (M.op X1 X1) X0) := by
    intro X0 X1
    first
    | (have i₁ := eq8 (M.op X0 X0) x
       have i₂ := eq12 X0 x
       grind)
    | exact superpose eq12 eq8
    | (have j0 := eq8 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq8 (M.op X0 X0) x
       have r₂ := eq12 X0 x
       grind)
    | exact resolve eq8 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12
  have eq35 : ∀ X0 X1 : G, (M.op X1 X1) = (N.op (M.op X1 X1) X0) ∨ (M.op X1 X1) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq34 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq34
  have eq55 : (M.op x x) ≠ (N.op (M.op x x) (N.op y x)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq10
       have i₂ := eq9 x x
       grind)
    | exact superpose eq9 eq10
    | (have j1 := eq9 x x
       grind)
    | exact resolve eq10 eq9
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq58 : (M.op x x) ≠ (N.op (M.op x x) (N.op y x)) ∨ x = (M.op x x) := by grind
  clear eq55
  have eq250 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) (M.op X0 X0)) := by
    intro X0
    first
    | (have j0 := eq19 (M.op X0 X0) X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq418 : (M.op x x) ≠ (M.op x x) ∨ x = (M.op x x) ∨ (N.op y x) = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq35 (N.op y x) x
       grind)
    | exact superpose eq35 eq58
    | (have j1 := eq35 x x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op y x) x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op (M.op x x) (N.op y x)) x
       grind)
    | exact resolve eq58 eq35
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq419 : (N.op y x) = (M.op x x) ∨ x = (M.op x x) := by grind
  clear eq418
  have eq423 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq419
       grind)
    | exact superpose eq419 eq58
    | exact resolve eq58 eq419
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq58 eq419
  have eq426 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq423
  have eq427 : x = (M.op x x) := by
    first
    | (have r₁ := eq426
       have r₂ := eq250 x
       grind)
    | exact resolve eq426 eq250
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq426
  have eq464 : ∀ X0 : G, x = (N.op x X0) ∨ x = X0 := by
    intro X0
    first
    | (have i₁ := eq35 X0 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq35
    | exact resolve eq35 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq35
  have eq467 : x = (N.op x x) := by
    first
    | (have i₁ := eq250 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq250
    | exact resolve eq250 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq250 eq427
  have eq649 : x ≠ (N.op x (N.op y x)) := by
    first
    | (have i₁ := eq10
       have i₂ := eq467
       grind)
    | exact superpose eq467 eq10
    | exact resolve eq10 eq467
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1019 : x ≠ x ∨ x = (N.op y x) := by
    first
    | (have i₁ := eq649
       have i₂ := eq464 (N.op y x)
       grind)
    | exact superpose eq464 eq649
    | (have j1 := eq464 (N.op y x)
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op y x)
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op x (N.op y x))
       grind)
    | exact resolve eq649 eq464
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq464
  have eq1020 : x = (N.op y x) := by grind
  clear eq1019
  have eq1124 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq649
       have i₂ := eq1020
       grind)
    | exact superpose eq1020 eq649
    | exact resolve eq649 eq1020
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq649 eq1020
  have eq1134 : False := by grind
  exact eq1134

/-- `Equation3663` from `Equation2623`: `x = (y ◇ ((z ◇ w) ◇ y)) ◇ x` ⊢ `x ◇ x = (x ◇ x) ◇ (y ◇ z)`, through the
companion `x □ y = if (M.op a b) = a then b else if (M.op a b) = b then a else (M.op a b)`, writing `a`, `b` for `x`, `y`.
Vampire refutation replayed step by step. -/
theorem Equation3663_StructuralFromFin_Equation2623 : Law3663.StructuralFromFin Law2623 := by
  classical
  refine AutBox.structuralFromFin_iteOf2 ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1))
    GuardAut2_pxy_x_pxy_y_y_x_pxy_Equation2623 (fun {G} M hM ↦ ?_)
  have hm := (@Law2623.models_iff G M).mp hM
  suffices h : ∀ N : Magma G,
      (∀ a b : G, (M.op a b) ≠ a ∨ N.op a b = b) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) ≠ b ∨ N.op a b = a) →
      (∀ a b : G, (M.op a b) = a ∨ (M.op a b) = b ∨ N.op a b = (M.op a b)) → @satisfies _ G N Law3663 by
    refine h _ (fun a b ↦ ?_) (fun a b ↦ ?_) (fun a b ↦ ?_)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).symm.imp id (fun hg ↦ if_pos hg)
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).symm.imp id (fun hg2 ↦ (if_neg hg).trans (if_pos hg2)))
    · rw [AutBox.iteOf2_apply ((Lf 0) ⋆ (Lf 1)) (Lf 0) ((Lf 0) ⋆ (Lf 1)) (Lf 1) (Lf 1) (Lf 0) ((Lf 0) ⋆ (Lf 1)) M a b]
      simp only [evalInMagma, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_fin_one]
      exact (eq_or_ne ((M.op a b)) (a)).imp id (fun hg ↦
        (eq_or_ne ((M.op a b)) (b)).imp id (fun hg2 ↦ (if_neg hg).trans (if_neg hg2)))
  intro N ht hu hv
  rw [@Law3663.models_iff G N]
  intro x y z
  by_contra nh
  have eq6 : ∀ X0 X1 X2 X3 : G, (M.op (M.op X1 (M.op (M.op X2 X3) X1)) X0) = X0 := by
    intro X0 X1 X2 X3
    grind
  have eq7 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X0 ∨ (N.op X0 X1) = X1 := by
    intro X0 X1
    grind
  have eq8 : ∀ X0 X1 : G, (M.op X0 X1) ≠ X1 ∨ (M.op X0 X1) = X0 ∨ (N.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq9 : ∀ X0 X1 : G, (M.op X0 X1) = (N.op X0 X1) ∨ (M.op X0 X1) = X1 ∨ (M.op X0 X1) = X0 := by
    intro X0 X1
    grind
  have eq10 : (N.op x x) ≠ (N.op (N.op x x) (N.op y z)) := by grind
  clear hm ht hu hv nh hM
  have eq12 : ∀ X0 X4 : G, (M.op (M.op X0 X0) X4) = X4 := by
    intro X0 X4
    first
    | (have i₁ := eq6 X4 X0 x (M.op (M.op x x) x)
       have i₂ := eq6 X0 x x x
       grind)
    | exact superpose eq6 eq6
    | exact resolve eq6 eq6
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq19 : ∀ X0 X1 : G, (M.op X1 X1) ≠ X0 ∨ (N.op (M.op X1 X1) X0) = X0 := by
    intro X0 X1
    first
    | (have i₁ := eq7 (M.op X1 X1) X0
       have i₂ := eq12 X1 X0
       grind)
    | exact superpose eq12 eq7
    | (have j0 := eq7 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq7 (M.op X0 X0) (M.op X0 X0)
       have r₂ := eq12 X0 (M.op X0 X0)
       grind)
    | exact resolve eq7 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq34 : ∀ X0 X1 : G, X0 ≠ X0 ∨ (M.op X1 X1) = X0 ∨ (M.op X1 X1) = (N.op (M.op X1 X1) X0) := by
    intro X0 X1
    first
    | (have i₁ := eq8 (M.op X0 X0) x
       have i₂ := eq12 X0 x
       grind)
    | exact superpose eq12 eq8
    | (have j0 := eq8 (M.op X1 X1) X0
       grind)
    | (have r₁ := eq8 (M.op X0 X0) x
       have r₂ := eq12 X0 x
       grind)
    | exact resolve eq8 eq12
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq12
  have eq35 : ∀ X0 X1 : G, (M.op X1 X1) = (N.op (M.op X1 X1) X0) ∨ (M.op X1 X1) = X0 := by
    intro X0 X1
    first
    | (have j0 := eq34 X0 X1
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq34
  have eq56 : (M.op x x) ≠ (N.op (M.op x x) (N.op y z)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq10
       have i₂ := eq9 x x
       grind)
    | exact superpose eq9 eq10
    | (have j1 := eq9 x x
       grind)
    | exact resolve eq10 eq9
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq58 : (M.op x x) ≠ (N.op (M.op x x) (N.op y z)) ∨ x = (M.op x x) := by grind
  clear eq56
  have eq250 : ∀ X0 : G, (M.op X0 X0) = (N.op (M.op X0 X0) (M.op X0 X0)) := by
    intro X0
    first
    | (have j0 := eq19 (M.op X0 X0) X0
       grind)
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq19
  have eq417 : (M.op x x) ≠ (M.op x x) ∨ x = (M.op x x) ∨ (N.op y z) = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq35 (N.op y z) x
       grind)
    | exact superpose eq35 eq58
    | (have j1 := eq35 x x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op y z) x
       grind)
    | (have r₁ := eq58
       have r₂ := eq35 (N.op (M.op x x) (N.op y z)) x
       grind)
    | exact resolve eq58 eq35
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq420 : (N.op y z) = (M.op x x) ∨ x = (M.op x x) := by grind
  clear eq417
  have eq423 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) ∨ x = (M.op x x) := by
    first
    | (have i₁ := eq58
       have i₂ := eq420
       grind)
    | exact superpose eq420 eq58
    | exact resolve eq58 eq420
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq58 eq420
  have eq426 : (M.op x x) ≠ (N.op (M.op x x) (M.op x x)) ∨ x = (M.op x x) := by grind
  clear eq423
  have eq427 : x = (M.op x x) := by
    first
    | (have r₁ := eq426
       have r₂ := eq250 x
       grind)
    | exact resolve eq426 eq250
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq426
  have eq464 : ∀ X0 : G, x = (N.op x X0) ∨ x = X0 := by
    intro X0
    first
    | (have i₁ := eq35 X0 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq35
    | exact resolve eq35 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq35
  have eq467 : x = (N.op x x) := by
    first
    | (have i₁ := eq250 x
       have i₂ := eq427
       grind)
    | exact superpose eq427 eq250
    | exact resolve eq250 eq427
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq250 eq427
  have eq649 : x ≠ (N.op x (N.op y z)) := by
    first
    | (have i₁ := eq10
       have i₂ := eq467
       grind)
    | exact superpose eq467 eq10
    | exact resolve eq10 eq467
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq1017 : x ≠ x ∨ x = (N.op y z) := by
    first
    | (have i₁ := eq649
       have i₂ := eq464 (N.op y z)
       grind)
    | exact superpose eq464 eq649
    | (have j1 := eq464 (N.op y z)
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op y z)
       grind)
    | (have r₁ := eq649
       have r₂ := eq464 (N.op x (N.op y z))
       grind)
    | exact resolve eq649 eq464
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq464
  have eq1020 : x = (N.op y z) := by grind
  clear eq1017
  have eq1123 : x ≠ (N.op x x) := by
    first
    | (have i₁ := eq649
       have i₂ := eq1020
       grind)
    | exact superpose eq1020 eq649
    | exact resolve eq649 eq1020
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq649 eq1020
  have eq1131 : False := by grind
  exact eq1131
