import equational_theories.Definability.Linear

/-!
# The cyclic linear certificates

The linear magmas `x ◇ y = a * x + b * y` over `ZMod m` that settle open cells of the definability
board, each with the congruence modulus `d = gcd(a + b - 1, m)` that `Magma.LinShift` needs. For
every model here the congruence class `{(α, β) : α + β ≡ 1 mod d}` is *exactly* the clone, so
nothing is given away by using the invariant in place of the closure — and the invariant is what
makes a refutation a scan over `m ^ 2` coefficient pairs instead of a closure computation, which is
what lets the moduli run into three figures.

Each `FamilyRefutesBasis` block depends only on `(m, d)`, so it is shared by every model with that
pair; each `Satisfies` block is particular to its model. Both are `native_decide`.

The refutations use `FamilyRefutesBasis` rather than `FamilyRefutes` because a linear operation
satisfies a law iff it satisfies it at the `k` basis assignments — both sides are linear forms, and
the basis reads their coefficients off one at a time. So refuting a target costs `m ^ 2` coefficient
pairs times `k` law evaluations rather than `m ^ 2` times `m ^ k`; for `ZMod 487` and the
three-variable targets that is the difference between a minute and a week. Nothing is lost: the
implication a certificate needs runs the easy way, from the law to its basis instances.

`Definability/LinearZModCover.lean` reads off the non-definability facts. These refute
`TermDefinableFrom`; the models are finite, so unlike `Definability/LinearInt.lean` they bear on
the finite-magma variant as well, and like every clone argument they say nothing about
`DefinableFrom`.

This file is generated by `genzcong.py`.
-/

open Law Law.MagmaLaw

/-! ### The refutations, one family per modulus and congruence -/

/-- Part 1 of the targets no linear operation over `ZMod 9` satisfies. -/
theorem zr9_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 9)) [
      66, 115, 170, 177, 219, 281, 873, 880
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 9` satisfies. -/
theorem zr9_1_1 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 9)) [
      1719, 1888, 2707, 2734
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 25` with coefficient sum `1` modulo `5`
satisfies. -/
theorem zr25_5_0 :
    FamilyRefutesBasis (Magma.linFam (5 : ZMod 25)) [
      335, 384, 3352, 3748, 3761, 4164, 4408, 4479
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 29` satisfies. -/
theorem zr29_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 29)) [
      115, 219, 873, 880, 2707, 2734
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 31` satisfies. -/
theorem zr31_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 31)) [
      467, 667, 2900, 3140
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 31` with coefficient sum `1` modulo `31`
satisfies. -/
theorem zr31_31_0 :
    FamilyRefutesBasis (Magma.linFam (31 : ZMod 31)) [
      464, 511, 714, 1120, 1289, 2338, 2507, 2913
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 31` with coefficient sum `1` modulo `31`
satisfies. -/
theorem zr31_31_1 :
    FamilyRefutesBasis (Magma.linFam (31 : ZMod 31)) [
      3103, 3116, 3345, 3548, 3954, 4157
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 47` satisfies. -/
theorem zr47_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 47)) [
      1110, 2497
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 71` satisfies. -/
theorem zr71_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 71)) [
      66, 115, 170, 177, 219, 281, 873, 880
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 71` satisfies. -/
theorem zr71_1_1 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 71)) [
      1083, 1719, 1888, 2504, 2707, 2734
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 131` satisfies. -/
theorem zr131_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 131)) [
      63, 73, 118, 125, 222, 229, 271, 274
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 131` satisfies. -/
theorem zr131_1_1 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 131)) [
      467, 667, 704, 883, 1323, 1489, 1516, 1526
    ] := by native_decide

/-- Part 3 of the targets no linear operation over `ZMod 131` satisfies. -/
theorem zr131_1_2 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 131)) [
      1685, 1692, 1895, 1922, 2091, 2098, 2101, 2304
    ] := by native_decide

/-- Part 4 of the targets no linear operation over `ZMod 131` satisfies. -/
theorem zr131_1_3 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 131)) [
      2744, 2900, 2903, 3140
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 193` satisfies. -/
theorem zr193_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 193)) [
      883, 1323, 1526, 2101, 2304, 2744
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 197` satisfies. -/
theorem zr197_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 197)) [
      63, 73, 118, 125, 222, 229, 271, 274
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 197` satisfies. -/
theorem zr197_1_1 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 197)) [
      883, 1110, 1279, 1323, 1489, 1516, 1526, 1685
    ] := by native_decide

/-- Part 3 of the targets no linear operation over `ZMod 197` satisfies. -/
theorem zr197_1_2 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 197)) [
      1692, 1895, 1922, 2091, 2098, 2101, 2304, 2328
    ] := by native_decide

/-- Part 4 of the targets no linear operation over `ZMod 197` satisfies. -/
theorem zr197_1_3 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 197)) [
      2497, 2744
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 277` satisfies. -/
theorem zr277_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 277)) [
      704, 2903
    ] := by native_decide

/-- Part 1 of the targets no linear operation over `ZMod 487` satisfies. -/
theorem zr487_1_0 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 487)) [
      467, 667, 883, 1110, 1279, 1323, 1526, 2101
    ] := by native_decide

/-- Part 2 of the targets no linear operation over `ZMod 487` satisfies. -/
theorem zr487_1_1 :
    FamilyRefutesBasis (Magma.linFam (1 : ZMod 487)) [
      2304, 2328, 2497, 2744, 2900, 3140
    ] := by native_decide

/-! ### The models -/

/-- Part 1 of the source list satisfied by `18 * x + 18 * y` over `ZMod 25`. -/
theorem zc0_sat_0 :
    Satisfies (Magma.lin (18 : ZMod 25) 18) [
      556, 749, 775, 1117, 1131, 1301, 1355, 2370
    ] := by native_decide

/-- Part 2 of the source list satisfied by `18 * x + 18 * y` over `ZMod 25`. -/
theorem zc0_sat_1 :
    Satisfies (Magma.lin (18 : ZMod 25) 18) [
      2383, 2511, 2538, 2928, 2982, 3128
    ] := by native_decide

/-- The certificate of the model `18 * x + 18 * y` over `ZMod 25`: its coefficient sum is `1` modulo
`5`, so `Magma.LinShift 5` bounds its clone. -/
theorem zc0_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 25) (Magma.lin 18 18) L')
    (hL : ∀ α γ : ZMod 25, ¬ @satisfies _ (ZMod 25) (Magma.linFam 5 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 18 18 5 2 (by decide) hM hL

/-- Part 1 of the source list satisfied by `112 * x + 112 * y` over `ZMod 193`. -/
theorem zc1_sat_0 :
    Satisfies (Magma.lin (112 : ZMod 193) 112) [
      556, 667, 749, 775, 1131, 1301, 1355, 2370
    ] := by native_decide

/-- Part 2 of the source list satisfied by `112 * x + 112 * y` over `ZMod 193`. -/
theorem zc1_sat_1 :
    Satisfies (Magma.lin (112 : ZMod 193) 112) [
      2383, 2511, 2900, 2928, 2982, 3128
    ] := by native_decide

/-- The certificate of the model `112 * x + 112 * y` over `ZMod 193`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc1_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 193) (Magma.lin 112 112) L')
    (hL : ∀ α γ : ZMod 193, ¬ @satisfies _ (ZMod 193) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 112 112 1 30 (by decide) hM hL

/-- Part 1 of the source list satisfied by `24 * x + 7 * y` over `ZMod 25`. -/
theorem zc2_sat_0 :
    Satisfies (Magma.lin (24 : ZMod 25) 7) [
      546, 949, 962, 1790, 1967, 2586, 3558, 3607
    ] := by native_decide

/-- Part 2 of the source list satisfied by `24 * x + 7 * y` over `ZMod 25`. -/
theorem zc2_sat_1 :
    Satisfies (Magma.lin (24 : ZMod 25) 7) [
      4290, 4369
    ] := by native_decide

/-- The certificate of the model `24 * x + 7 * y` over `ZMod 25`: its coefficient sum is `1` modulo
`5`, so `Magma.LinShift 5` bounds its clone. -/
theorem zc2_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 25) (Magma.lin 24 7) L')
    (hL : ∀ α γ : ZMod 25, ¬ @satisfies _ (ZMod 25) (Magma.linFam 5 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 24 7 5 1 (by decide) hM hL

/-- Part 1 of the source list satisfied by `7 * x + 24 * y` over `ZMod 25`. -/
theorem zc3_sat_0 :
    Satisfies (Magma.lin (7 : ZMod 25) 24) [
      1098, 1764, 1913, 2722, 2776, 3185, 3951, 3973
    ] := by native_decide

/-- Part 2 of the source list satisfied by `7 * x + 24 * y` over `ZMod 25`. -/
theorem zc3_sat_1 :
    Satisfies (Magma.lin (7 : ZMod 25) 24) [
      4605, 4684
    ] := by native_decide

/-- The certificate of the model `7 * x + 24 * y` over `ZMod 25`: its coefficient sum is `1` modulo
`5`, so `Magma.LinShift 5` bounds its clone. -/
theorem zc3_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 25) (Magma.lin 7 24) L')
    (hL : ∀ α γ : ZMod 25, ¬ @satisfies _ (ZMod 25) (Magma.linFam 5 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 7 24 5 1 (by decide) hM hL

/-- Part 1 of the source list satisfied by `192 * x + 112 * y` over `ZMod 193`. -/
theorem zc4_sat_0 :
    Satisfies (Magma.lin (192 : ZMod 193) 112) [
      546, 949, 962, 1790, 1967, 2586
    ] := by native_decide

/-- The certificate of the model `192 * x + 112 * y` over `ZMod 193`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc4_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 193) (Magma.lin 192 112) L')
    (hL : ∀ α γ : ZMod 193, ¬ @satisfies _ (ZMod 193) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 192 112 1 110 (by decide) hM hL

/-- Part 1 of the source list satisfied by `112 * x + 192 * y` over `ZMod 193`. -/
theorem zc5_sat_0 :
    Satisfies (Magma.lin (112 : ZMod 193) 192) [
      1098, 1764, 1913, 2722, 2776, 3185
    ] := by native_decide

/-- The certificate of the model `112 * x + 192 * y` over `ZMod 193`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc5_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 193) (Magma.lin 112 192) L')
    (hL : ∀ α γ : ZMod 193, ¬ @satisfies _ (ZMod 193) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 112 192 1 110 (by decide) hM hL

/-- Part 1 of the source list satisfied by `95 * x + 9 * y` over `ZMod 131`. -/
theorem zc6_sat_0 :
    Satisfies (Magma.lin (95 : ZMod 131) 9) [
      2328
    ] := by native_decide

/-- The certificate of the model `95 * x + 9 * y` over `ZMod 131`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc6_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 131) (Magma.lin 95 9) L')
    (hL : ∀ α γ : ZMod 131, ¬ @satisfies _ (ZMod 131) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 95 9 1 103 (by decide) hM hL

/-- Part 1 of the source list satisfied by `57 * x + 45 * y` over `ZMod 131`. -/
theorem zc7_sat_0 :
    Satisfies (Magma.lin (57 : ZMod 131) 45) [
      1279
    ] := by native_decide

/-- The certificate of the model `57 * x + 45 * y` over `ZMod 131`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc7_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 131) (Magma.lin 57 45) L')
    (hL : ∀ α γ : ZMod 131, ¬ @satisfies _ (ZMod 131) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 57 45 1 101 (by decide) hM hL

/-- Part 1 of the source list satisfied by `193 * x + 110 * y` over `ZMod 197`. -/
theorem zc8_sat_0 :
    Satisfies (Magma.lin (193 : ZMod 197) 110) [
      2903
    ] := by native_decide

/-- The certificate of the model `193 * x + 110 * y` over `ZMod 197`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc8_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 197) (Magma.lin 193 110) L')
    (hL : ∀ α γ : ZMod 197, ¬ @satisfies _ (ZMod 197) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 193 110 1 105 (by decide) hM hL

/-- Part 1 of the source list satisfied by `183 * x + 105 * y` over `ZMod 197`. -/
theorem zc9_sat_0 :
    Satisfies (Magma.lin (183 : ZMod 197) 105) [
      3140
    ] := by native_decide

/-- The certificate of the model `183 * x + 105 * y` over `ZMod 197`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc9_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 197) (Magma.lin 183 105) L')
    (hL : ∀ α γ : ZMod 197, ¬ @satisfies _ (ZMod 197) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 183 105 1 90 (by decide) hM hL

/-- Part 1 of the source list satisfied by `162 * x + 8 * y` over `ZMod 197`. -/
theorem zc10_sat_0 :
    Satisfies (Magma.lin (162 : ZMod 197) 8) [
      704
    ] := by native_decide

/-- The certificate of the model `162 * x + 8 * y` over `ZMod 197`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc10_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 197) (Magma.lin 162 8) L')
    (hL : ∀ α γ : ZMod 197, ¬ @satisfies _ (ZMod 197) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 162 8 1 169 (by decide) hM hL

/-- Part 1 of the source list satisfied by `105 * x + 183 * y` over `ZMod 197`. -/
theorem zc11_sat_0 :
    Satisfies (Magma.lin (105 : ZMod 197) 183) [
      467
    ] := by native_decide

/-- The certificate of the model `105 * x + 183 * y` over `ZMod 197`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc11_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 197) (Magma.lin 105 183) L')
    (hL : ∀ α γ : ZMod 197, ¬ @satisfies _ (ZMod 197) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 105 183 1 90 (by decide) hM hL

/-- Part 1 of the source list satisfied by `112 * x + 81 * y` over `ZMod 193`. -/
theorem zc12_sat_0 :
    Satisfies (Magma.lin (112 : ZMod 193) 81) [
      481, 1496, 2146, 3161
    ] := by native_decide

/-- The certificate of the model `112 * x + 81 * y` over `ZMod 193`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc12_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 193) (Magma.lin 112 81) L')
    (hL : ∀ α γ : ZMod 193, ¬ @satisfies _ (ZMod 193) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 112 81 1 192 (by decide) hM hL

/-- Part 1 of the source list satisfied by `130 * x + 120 * y` over `ZMod 131`. -/
theorem zc13_sat_0 :
    Satisfies (Magma.lin (130 : ZMod 131) 120) [
      2497
    ] := by native_decide

/-- The certificate of the model `130 * x + 120 * y` over `ZMod 131`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc13_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 131) (Magma.lin 130 120) L')
    (hL : ∀ α γ : ZMod 131, ¬ @satisfies _ (ZMod 131) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 130 120 1 118 (by decide) hM hL

/-- Part 1 of the source list satisfied by `120 * x + 130 * y` over `ZMod 131`. -/
theorem zc14_sat_0 :
    Satisfies (Magma.lin (120 : ZMod 131) 130) [
      1110
    ] := by native_decide

/-- The certificate of the model `120 * x + 130 * y` over `ZMod 131`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc14_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 131) (Magma.lin 120 130) L')
    (hL : ∀ α γ : ZMod 131, ¬ @satisfies _ (ZMod 131) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 120 130 1 118 (by decide) hM hL

/-- Part 1 of the source list satisfied by `27 * x + 5 * y` over `ZMod 31`. -/
theorem zc15_sat_0 :
    Satisfies (Magma.lin (27 : ZMod 31) 5) [
      2910, 4658
    ] := by native_decide

/-- The certificate of the model `27 * x + 5 * y` over `ZMod 31`: its coefficient sum is `1` modulo
`31`, so `Magma.LinShift 31` bounds its clone. -/
theorem zc15_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 31) (Magma.lin 27 5) L')
    (hL : ∀ α γ : ZMod 31, ¬ @satisfies _ (ZMod 31) (Magma.linFam 31 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 27 5 31 0 (by decide) hM hL

/-- Part 1 of the source list satisfied by `5 * x + 27 * y` over `ZMod 31`. -/
theorem zc16_sat_0 :
    Satisfies (Magma.lin (5 : ZMod 31) 27) [
      677, 4293
    ] := by native_decide

/-- The certificate of the model `5 * x + 27 * y` over `ZMod 31`: its coefficient sum is `1` modulo
`31`, so `Magma.LinShift 31` bounds its clone. -/
theorem zc16_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 31) (Magma.lin 5 27) L')
    (hL : ∀ α γ : ZMod 31, ¬ @satisfies _ (ZMod 31) (Magma.linFam 31 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 5 27 31 0 (by decide) hM hL

/-- Part 1 of the source list satisfied by `30 * x + 19 * y` over `ZMod 71`. -/
theorem zc17_sat_0 :
    Satisfies (Magma.lin (30 : ZMod 71) 19) [
      2301
    ] := by native_decide

/-- The certificate of the model `30 * x + 19 * y` over `ZMod 71`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc17_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 71) (Magma.lin 30 19) L')
    (hL : ∀ α γ : ZMod 71, ¬ @satisfies _ (ZMod 71) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 30 19 1 48 (by decide) hM hL

/-- Part 1 of the source list satisfied by `19 * x + 30 * y` over `ZMod 71`. -/
theorem zc18_sat_0 :
    Satisfies (Magma.lin (19 : ZMod 71) 30) [
      1286
    ] := by native_decide

/-- The certificate of the model `19 * x + 30 * y` over `ZMod 71`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc18_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 71) (Magma.lin 19 30) L')
    (hL : ∀ α γ : ZMod 71, ¬ @satisfies _ (ZMod 71) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 19 30 1 48 (by decide) hM hL

/-- Part 1 of the source list satisfied by `272 * x + 254 * y` over `ZMod 487`. -/
theorem zc19_sat_0 :
    Satisfies (Magma.lin (272 : ZMod 487) 254) [
      2091
    ] := by native_decide

/-- The certificate of the model `272 * x + 254 * y` over `ZMod 487`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc19_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 487) (Magma.lin 272 254) L')
    (hL : ∀ α γ : ZMod 487, ¬ @satisfies _ (ZMod 487) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 272 254 1 38 (by decide) hM hL

/-- Part 1 of the source list satisfied by `254 * x + 272 * y` over `ZMod 487`. -/
theorem zc20_sat_0 :
    Satisfies (Magma.lin (254 : ZMod 487) 272) [
      1516
    ] := by native_decide

/-- The certificate of the model `254 * x + 272 * y` over `ZMod 487`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc20_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 487) (Magma.lin 254 272) L')
    (hL : ∀ α γ : ZMod 487, ¬ @satisfies _ (ZMod 487) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 254 272 1 38 (by decide) hM hL

/-- Part 1 of the source list satisfied by `7 * x + 2 * y` over `ZMod 9`. -/
theorem zc21_sat_0 :
    Satisfies (Magma.lin (7 : ZMod 9) 2) [
      1083
    ] := by native_decide

/-- The certificate of the model `7 * x + 2 * y` over `ZMod 9`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc21_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 9) (Magma.lin 7 2) L')
    (hL : ∀ α γ : ZMod 9, ¬ @satisfies _ (ZMod 9) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 7 2 1 8 (by decide) hM hL

/-- Part 1 of the source list satisfied by `2 * x + 7 * y` over `ZMod 9`. -/
theorem zc22_sat_0 :
    Satisfies (Magma.lin (2 : ZMod 9) 7) [
      2504
    ] := by native_decide

/-- The certificate of the model `2 * x + 7 * y` over `ZMod 9`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc22_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 9) (Magma.lin 2 7) L')
    (hL : ∀ α γ : ZMod 9, ¬ @satisfies _ (ZMod 9) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 2 7 1 8 (by decide) hM hL

/-- Part 1 of the source list satisfied by `24 * x + 12 * y` over `ZMod 25`. -/
theorem zc23_sat_0 :
    Satisfies (Magma.lin (24 : ZMod 25) 12) [
      3113
    ] := by native_decide

/-- The certificate of the model `24 * x + 12 * y` over `ZMod 25`: its coefficient sum is `1` modulo
`5`, so `Magma.LinShift 5` bounds its clone. -/
theorem zc23_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 25) (Magma.lin 24 12) L')
    (hL : ∀ α γ : ZMod 25, ¬ @satisfies _ (ZMod 25) (Magma.linFam 5 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 24 12 5 2 (by decide) hM hL

/-- Part 1 of the source list satisfied by `22 * x + 14 * y` over `ZMod 25`. -/
theorem zc24_sat_0 :
    Satisfies (Magma.lin (22 : ZMod 25) 14) [
      474
    ] := by native_decide

/-- The certificate of the model `22 * x + 14 * y` over `ZMod 25`: its coefficient sum is `1` modulo
`5`, so `Magma.LinShift 5` bounds its clone. -/
theorem zc24_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 25) (Magma.lin 22 14) L')
    (hL : ∀ α γ : ZMod 25, ¬ @satisfies _ (ZMod 25) (Magma.linFam 5 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 22 14 5 2 (by decide) hM hL

/-- Part 1 of the source list satisfied by `20 * x + 12 * y` over `ZMod 29`. -/
theorem zc25_sat_0 :
    Satisfies (Magma.lin (20 : ZMod 29) 12) [
      501
    ] := by native_decide

/-- The certificate of the model `20 * x + 12 * y` over `ZMod 29`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc25_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 29) (Magma.lin 20 12) L')
    (hL : ∀ α γ : ZMod 29, ¬ @satisfies _ (ZMod 29) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 20 12 1 2 (by decide) hM hL

/-- Part 1 of the source list satisfied by `17 * x + 8 * y` over `ZMod 29`. -/
theorem zc26_sat_0 :
    Satisfies (Magma.lin (17 : ZMod 29) 8) [
      3106
    ] := by native_decide

/-- The certificate of the model `17 * x + 8 * y` over `ZMod 29`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc26_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 29) (Magma.lin 17 8) L')
    (hL : ∀ α γ : ZMod 29, ¬ @satisfies _ (ZMod 29) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 17 8 1 24 (by decide) hM hL

/-- Part 1 of the source list satisfied by `12 * x + 3 * y` over `ZMod 31`. -/
theorem zc27_sat_0 :
    Satisfies (Magma.lin (12 : ZMod 31) 3) [
      2903
    ] := by native_decide

/-- The certificate of the model `12 * x + 3 * y` over `ZMod 31`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc27_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 31) (Magma.lin 12 3) L')
    (hL : ∀ α γ : ZMod 31, ¬ @satisfies _ (ZMod 31) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 12 3 1 14 (by decide) hM hL

/-- Part 1 of the source list satisfied by `3 * x + 12 * y` over `ZMod 31`. -/
theorem zc28_sat_0 :
    Satisfies (Magma.lin (3 : ZMod 31) 12) [
      704
    ] := by native_decide

/-- The certificate of the model `3 * x + 12 * y` over `ZMod 31`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc28_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 31) (Magma.lin 3 12) L')
    (hL : ∀ α γ : ZMod 31, ¬ @satisfies _ (ZMod 31) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 3 12 1 14 (by decide) hM hL

/-- Part 1 of the source list satisfied by `42 * x + 38 * y` over `ZMod 47`. -/
theorem zc29_sat_0 :
    Satisfies (Magma.lin (42 : ZMod 47) 38) [
      1279
    ] := by native_decide

/-- The certificate of the model `42 * x + 38 * y` over `ZMod 47`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc29_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 47) (Magma.lin 42 38) L')
    (hL : ∀ α γ : ZMod 47, ¬ @satisfies _ (ZMod 47) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 42 38 1 32 (by decide) hM hL

/-- Part 1 of the source list satisfied by `38 * x + 42 * y` over `ZMod 47`. -/
theorem zc30_sat_0 :
    Satisfies (Magma.lin (38 : ZMod 47) 42) [
      2328
    ] := by native_decide

/-- The certificate of the model `38 * x + 42 * y` over `ZMod 47`: its coefficient sum is `1` modulo
`1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc30_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 47) (Magma.lin 38 42) L')
    (hL : ∀ α γ : ZMod 47, ¬ @satisfies _ (ZMod 47) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 38 42 1 32 (by decide) hM hL

/-- Part 1 of the source list satisfied by `217 * x + 168 * y` over `ZMod 277`. -/
theorem zc31_sat_0 :
    Satisfies (Magma.lin (217 : ZMod 277) 168) [
      3140
    ] := by native_decide

/-- The certificate of the model `217 * x + 168 * y` over `ZMod 277`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc31_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 277) (Magma.lin 217 168) L')
    (hL : ∀ α γ : ZMod 277, ¬ @satisfies _ (ZMod 277) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 217 168 1 107 (by decide) hM hL

/-- Part 1 of the source list satisfied by `201 * x + 116 * y` over `ZMod 277`. -/
theorem zc32_sat_0 :
    Satisfies (Magma.lin (201 : ZMod 277) 116) [
      2091
    ] := by native_decide

/-- The certificate of the model `201 * x + 116 * y` over `ZMod 277`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc32_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 277) (Magma.lin 201 116) L')
    (hL : ∀ α γ : ZMod 277, ¬ @satisfies _ (ZMod 277) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 201 116 1 39 (by decide) hM hL

/-- Part 1 of the source list satisfied by `168 * x + 217 * y` over `ZMod 277`. -/
theorem zc33_sat_0 :
    Satisfies (Magma.lin (168 : ZMod 277) 217) [
      467
    ] := by native_decide

/-- The certificate of the model `168 * x + 217 * y` over `ZMod 277`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc33_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 277) (Magma.lin 168 217) L')
    (hL : ∀ α γ : ZMod 277, ¬ @satisfies _ (ZMod 277) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 168 217 1 107 (by decide) hM hL

/-- Part 1 of the source list satisfied by `160 * x + 156 * y` over `ZMod 277`. -/
theorem zc34_sat_0 :
    Satisfies (Magma.lin (160 : ZMod 277) 156) [
      1516
    ] := by native_decide

/-- The certificate of the model `160 * x + 156 * y` over `ZMod 277`: its coefficient sum is `1`
modulo `1`, so `Magma.LinShift 1` bounds its clone. -/
theorem zc34_cert {L L' : Law.MagmaLaw ℕ}
    (hM : @satisfies _ (ZMod 277) (Magma.lin 160 156) L')
    (hL : ∀ α γ : ZMod 277, ¬ @satisfies _ (ZMod 277) (Magma.linFam 1 α γ) L) :
    ¬ L.TermDefinableFrom L' :=
  not_termDefinableFrom_of_lin 160 156 1 38 (by decide) hM hL
