import equational_theories.Definability.Rev2739a_data

/-!
# Targets `414`-`4090` against equation `2739`

Each target is refuted by every member of `Magma.rev2739aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem rev2739a_kill414 : ∀ b : Fin 2, ¬ @Equation414 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation414_not_termStructuralFromFin_Equation2739 :
    ¬ Law414.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill414 b
        ((@Law414.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill823 : ∀ b : Fin 2, ¬ @Equation823 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation823_not_termStructuralFromFin_Equation2739 :
    ¬ Law823.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill823 b
        ((@Law823.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill842 : ∀ b : Fin 2, ¬ @Equation842 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation842_not_termStructuralFromFin_Equation2739 :
    ¬ Law842.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill842 b
        ((@Law842.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill1023 : ∀ b : Fin 2, ¬ @Equation1023 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation1023_not_termStructuralFromFin_Equation2739 :
    ¬ Law1023.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill1023 b
        ((@Law1023.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill1036 : ∀ b : Fin 2, ¬ @Equation1036 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation1036_not_termStructuralFromFin_Equation2739 :
    ¬ Law1036.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill1036 b
        ((@Law1036.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill2496 : ∀ b : Fin 2, ¬ @Equation2496 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation2496_not_termStructuralFromFin_Equation2739 :
    ¬ Law2496.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill2496 b
        ((@Law2496.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill2530 : ∀ b : Fin 2, ¬ @Equation2530 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation2530_not_termStructuralFromFin_Equation2739 :
    ¬ Law2530.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill2530 b
        ((@Law2530.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill2652 : ∀ b : Fin 2, ¬ @Equation2652 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation2652_not_termStructuralFromFin_Equation2739 :
    ¬ Law2652.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill2652 b
        ((@Law2652.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill2706 : ∀ b : Fin 2, ¬ @Equation2706 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation2706_not_termStructuralFromFin_Equation2739 :
    ¬ Law2706.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill2706 b
        ((@Law2706.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill3139 : ∀ b : Fin 2, ¬ @Equation3139 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation3139_not_termStructuralFromFin_Equation2739 :
    ¬ Law3139.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill3139 b
        ((@Law3139.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill3256 : ∀ b : Fin 2, ¬ @Equation3256 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation3256_not_termStructuralFromFin_Equation2739 :
    ¬ Law3256.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill3256 b
        ((@Law3256.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))

theorem rev2739a_kill4090 : ∀ b : Fin 2, ¬ @Equation4090 (Fin 3) (Magma.rev2739aBad b) := by decideFin!

theorem Equation4090_not_termStructuralFromFin_Equation2739 :
    ¬ Law4090.TermStructuralFromFin Law2739 :=
  not_termStructuralFromFin_of_subclones Magma.rev2739a
    ((@Law2739.models_iff (Fin 3) Magma.rev2739a).mpr rev2739a_sat)
    Magma.rev2739a_isCloneFamily Magma.rev2739a_isSubclone Magma.rev2739a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2739aSub k) u)
      Magma.rev2739a_split fun b h ↦ rev2739a_kill4090 b
        ((@Law4090.models_iff (Fin 3) (Magma.rev2739aBad b)).mp h))
