import equational_theories.Definability.Rev2399a_data

/-!
# Targets `817`-`2644` against equation `2399`

Each target is refuted by every member of `Magma.rev2399aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem rev2399a_kill817 : ∀ b : Fin 2, ¬ @Equation817 (Fin 3) (Magma.rev2399aBad b) := by decideFin!

theorem Equation817_not_termStructuralFromFin_Equation2399 :
    ¬ Law817.TermStructuralFromFin Law2399 :=
  not_termStructuralFromFin_of_subclones Magma.rev2399a
    ((@Law2399.models_iff (Fin 3) Magma.rev2399a).mpr rev2399a_sat)
    Magma.rev2399a_isCloneFamily Magma.rev2399a_isSubclone Magma.rev2399a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2399aSub k) u)
      Magma.rev2399a_split fun b h ↦ rev2399a_kill817 b
        ((@Law817.models_iff (Fin 3) (Magma.rev2399aBad b)).mp h))

theorem rev2399a_kill2644 : ∀ b : Fin 2, ¬ @Equation2644 (Fin 3) (Magma.rev2399aBad b) := by decideFin!

theorem Equation2644_not_termStructuralFromFin_Equation2399 :
    ¬ Law2644.TermStructuralFromFin Law2399 :=
  not_termStructuralFromFin_of_subclones Magma.rev2399a
    ((@Law2399.models_iff (Fin 3) Magma.rev2399a).mpr rev2399a_sat)
    Magma.rev2399a_isCloneFamily Magma.rev2399a_isSubclone Magma.rev2399a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2399aSub k) u)
      Magma.rev2399a_split fun b h ↦ rev2399a_kill2644 b
        ((@Law2644.models_iff (Fin 3) (Magma.rev2399aBad b)).mp h))
