import equational_theories.Definability.Rev2364a_data

/-!
# Targets `414`-`4090` against equation `2364`

Each target is refuted by every member of `Magma.rev2364aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem rev2364a_kill414 : ∀ b : Fin 2, ¬ @Equation414 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation414_not_termStructuralFromFin_Equation2364 :
    ¬ Law414.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill414 b
        ((@Law414.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill823 : ∀ b : Fin 2, ¬ @Equation823 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation823_not_termStructuralFromFin_Equation2364 :
    ¬ Law823.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill823 b
        ((@Law823.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill1028 : ∀ b : Fin 2, ¬ @Equation1028 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation1028_not_termStructuralFromFin_Equation2364 :
    ¬ Law1028.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill1028 b
        ((@Law1028.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill1248 : ∀ b : Fin 2, ¬ @Equation1248 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation1248_not_termStructuralFromFin_Equation2364 :
    ¬ Law1248.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill1248 b
        ((@Law1248.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill2246 : ∀ b : Fin 2, ¬ @Equation2246 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation2246_not_termStructuralFromFin_Equation2364 :
    ¬ Law2246.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill2246 b
        ((@Law2246.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill2466 : ∀ b : Fin 2, ¬ @Equation2466 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation2466_not_termStructuralFromFin_Equation2364 :
    ¬ Law2466.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill2466 b
        ((@Law2466.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill2706 : ∀ b : Fin 2, ¬ @Equation2706 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation2706_not_termStructuralFromFin_Equation2364 :
    ¬ Law2706.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill2706 b
        ((@Law2706.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill3139 : ∀ b : Fin 2, ¬ @Equation3139 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation3139_not_termStructuralFromFin_Equation2364 :
    ¬ Law3139.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill3139 b
        ((@Law3139.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill3256 : ∀ b : Fin 2, ¬ @Equation3256 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation3256_not_termStructuralFromFin_Equation2364 :
    ¬ Law3256.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill3256 b
        ((@Law3256.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))

theorem rev2364a_kill4090 : ∀ b : Fin 2, ¬ @Equation4090 (Fin 3) (Magma.rev2364aBad b) := by decideFin!

theorem Equation4090_not_termStructuralFromFin_Equation2364 :
    ¬ Law4090.TermStructuralFromFin Law2364 :=
  not_termStructuralFromFin_of_subclones Magma.rev2364a
    ((@Law2364.models_iff (Fin 3) Magma.rev2364a).mpr rev2364a_sat)
    Magma.rev2364a_isCloneFamily Magma.rev2364a_isSubclone Magma.rev2364a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev2364aSub k) u)
      Magma.rev2364a_split fun b h ↦ rev2364a_kill4090 b
        ((@Law4090.models_iff (Fin 3) (Magma.rev2364aBad b)).mp h))
