import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 4375 that its own realisations cannot rebuild

`Magma.rev4375b` is a model of equation `4375` on `Fin 3`, and its binary clone has
`5` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.rev4375bSub` lists the `1` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.rev4375bBad` holds the `2` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `4375`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `4375` on `Fin 3` whose binary clone has `5` members. -/
def rev4375bt : Array (Array Nat) :=
  #[#[0, 0, 0], #[0, 0, 0], #[0, 2, 0]]

@[implicit_reducible]
def rev4375b : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((rev4375bt[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The `5` operations term-definable from `Magma.rev4375b`. -/
def rev4375bcl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 0]], #[#[0, 0, 0], #[0, 0, 0], #[0, 2, 0]], #[#[0, 0, 0], #[0, 0, 2], #[0, 0, 0]]]

@[implicit_reducible]
def rev4375bClone (i : Fin 5) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((rev4375bcl[i.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.rev4375bClone` lands. -/
def rev4375bcp : Array (Array Nat) :=
  #[#[2, 3, 2, 2, 2], #[4, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 3, 2, 2, 2], #[4, 2, 2, 2, 2]]

def rev4375bComp (i j : Fin 5) : Fin 5 :=
  ⟨((rev4375bcp[i.1]!)[j.1]!) % 5, Nat.mod_lt _ (by decide)⟩

theorem rev4375b_cloneFacts :
    (∀ x y, (rev4375bClone 0).op x y = x) ∧ (∀ x y, (rev4375bClone 1).op x y = y) ∧
      ∀ i j x y, (rev4375bClone (rev4375bComp i j)).op x y =
        rev4375b.op ((rev4375bClone i).op x y) ((rev4375bClone j).op x y) := by
  decideFin!

theorem rev4375b_isCloneFamily :
    rev4375b.IsCloneFamily rev4375bClone 0 1 rev4375bComp :=
  ⟨rev4375b_cloneFacts.1, rev4375b_cloneFacts.2.1, rev4375b_cloneFacts.2.2⟩

/-- The `1` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def rev4375bsb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 0]]]]

@[implicit_reducible]
def rev4375bSub (k : Fin 1) (j : Fin 3) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((((rev4375bsb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def rev4375bpr : Array (Array Nat) :=
  #[#[0], #[1]]

def rev4375bP (t : Fin 2) (k : Fin 1) : Fin 3 :=
  ⟨((rev4375bpr[t.1]!)[k.1]!) % 3, Nat.mod_lt _ (by decide)⟩

def rev4375bsc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[2, 2, 2], #[2, 2, 2], #[2, 2, 2]]]]

def rev4375bSc (k : Fin 1) (i j l : Fin 3) : Fin 3 :=
  ⟨((((rev4375bsc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 3, Nat.mod_lt _ (by decide)⟩

theorem rev4375b_subFacts :
    (∀ k x y, (rev4375bSub k (rev4375bP 0 k)).op x y = x) ∧
      (∀ k x y, (rev4375bSub k (rev4375bP 1 k)).op x y = y) ∧
      (∀ k i j l x y, (rev4375bSub k (rev4375bSc k i j l)).op x y =
        (rev4375bSub k i).op ((rev4375bSub k j).op x y) ((rev4375bSub k l).op x y)) ∧
      ∀ k j, ¬ ∀ x y, (rev4375bSub k j).op x y = rev4375b.op x y := by
  decideFin!

theorem rev4375b_isSubclone (k : Fin 1) : IsSubclone (rev4375bSub k) :=
  IsSubclone.of_table (rev4375bP 0 k) (rev4375bP 1 k) (rev4375bSc k)
    (rev4375b_subFacts.1 k) (rev4375b_subFacts.2.1 k) (rev4375b_subFacts.2.2.1 k)

theorem rev4375b_notInSub (k : Fin 1) : ¬ InClone (rev4375bSub k) rev4375b.op :=
  notInClone_of (rev4375b_subFacts.2.2.2 k)

/-- The `2` clone members left over: those that do generate `◇`. -/
def rev4375bbd : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0], #[0, 0, 0], #[0, 2, 0]], #[#[0, 0, 0], #[0, 0, 2], #[0, 0, 0]]]

@[implicit_reducible]
def rev4375bBad (b : Fin 2) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((rev4375bbd[b.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def rev4375bw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0], #[0, 1, 2, 0, 0], #[0, 0, 0, 0, 1]]

def rev4375bWk (i : Fin 5) : Fin 1 := ⟨((rev4375bw[0]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

def rev4375bWe (i : Fin 5) : Fin 3 := ⟨((rev4375bw[1]!)[i.1]!) % 3, Nat.mod_lt _ (by decide)⟩

def rev4375bWb (i : Fin 5) : Fin 2 := ⟨((rev4375bw[2]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

theorem rev4375b_splitFacts : ∀ i : Fin 5,
    (∀ x y, (rev4375bSub (rev4375bWk i) (rev4375bWe i)).op x y = (rev4375bClone i).op x y) ∨
      (∀ x y, (rev4375bClone i).op x y = (rev4375bBad (rev4375bWb i)).op x y) := by
  decideFin!

theorem rev4375b_split (i : Fin 5) :
    (∃ k, InClone (rev4375bSub k) (rev4375bClone i).op) ∨
      ∃ b, (rev4375bClone i).op = (rev4375bBad b).op :=
  split_of_witnesses rev4375bWk rev4375bWe rev4375bWb rev4375b_splitFacts i

end Magma

theorem rev4375b_sat : @Equation4375 (Fin 3) Magma.rev4375b := by decideFin!
