import equational_theories.Definability.Rev4449b_data

/-!
# Targets `4405`-`4405` against equation `4449`

Each target is refuted by every member of `Magma.rev4449bBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem rev4449b_kill4405 : ∀ b : Fin 2, ¬ @Equation4405 (Fin 3) (Magma.rev4449bBad b) := by decideFin!

theorem Equation4405_not_termStructuralFromFin_Equation4449 :
    ¬ Law4405.TermStructuralFromFin Law4449 :=
  not_termStructuralFromFin_of_subclones Magma.rev4449b
    ((@Law4449.models_iff (Fin 3) Magma.rev4449b).mpr rev4449b_sat)
    Magma.rev4449b_isCloneFamily Magma.rev4449b_isSubclone Magma.rev4449b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.rev4449bSub k) u)
      Magma.rev4449b_split fun b h ↦ rev4449b_kill4405 b
        ((@Law4405.models_iff (Fin 3) (Magma.rev4449bBad b)).mp h))
