import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 4373 that its own realisations cannot rebuild

`Magma.rev4373a` is a model of equation `4373` on `Fin 3`, and its binary clone has
`6` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.rev4373aSub` lists the `1` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.rev4373aBad` holds the `1` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `4373`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `4373` on `Fin 3` whose binary clone has `6` members. -/
def rev4373at : Array (Array Nat) :=
  #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 1]]

@[implicit_reducible]
def rev4373a : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((rev4373at[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The `6` operations term-definable from `Magma.rev4373a`. -/
def rev4373acl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[0, 0, 0], #[0, 0, 0], #[1, 1, 1]], #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 1]], #[#[0, 0, 1], #[0, 0, 1], #[0, 0, 1]], #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 0]]]

@[implicit_reducible]
def rev4373aClone (i : Fin 6) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((rev4373acl[i.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.rev4373aClone` lands. -/
def rev4373acp : Array (Array Nat) :=
  #[#[2, 3, 5, 5, 5, 5], #[3, 4, 5, 5, 5, 5], #[5, 5, 5, 5, 5, 5], #[5, 5, 5, 5, 5, 5], #[5, 5, 5, 5, 5, 5], #[5, 5, 5, 5, 5, 5]]

def rev4373aComp (i j : Fin 6) : Fin 6 :=
  ⟨((rev4373acp[i.1]!)[j.1]!) % 6, Nat.mod_lt _ (by decide)⟩

theorem rev4373a_cloneFacts :
    (∀ x y, (rev4373aClone 0).op x y = x) ∧ (∀ x y, (rev4373aClone 1).op x y = y) ∧
      ∀ i j x y, (rev4373aClone (rev4373aComp i j)).op x y =
        rev4373a.op ((rev4373aClone i).op x y) ((rev4373aClone j).op x y) := by
  decideFin!

theorem rev4373a_isCloneFamily :
    rev4373a.IsCloneFamily rev4373aClone 0 1 rev4373aComp :=
  ⟨rev4373a_cloneFacts.1, rev4373a_cloneFacts.2.1, rev4373a_cloneFacts.2.2⟩

/-- The `1` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def rev4373asb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[0, 0, 0], #[0, 0, 0], #[1, 1, 1]], #[#[0, 0, 1], #[0, 0, 1], #[0, 0, 1]], #[#[0, 0, 0], #[0, 0, 0], #[0, 0, 0]]]]

@[implicit_reducible]
def rev4373aSub (k : Fin 1) (j : Fin 5) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((((rev4373asb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def rev4373apr : Array (Array Nat) :=
  #[#[0], #[1]]

def rev4373aP (t : Fin 2) (k : Fin 1) : Fin 5 :=
  ⟨((rev4373apr[t.1]!)[k.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def rev4373asc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4]], #[#[2, 3, 4, 4, 4], #[2, 3, 4, 4, 4], #[2, 3, 4, 4, 4], #[2, 3, 4, 4, 4], #[2, 3, 4, 4, 4]], #[#[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4], #[4, 4, 4, 4, 4]]]]

def rev4373aSc (k : Fin 1) (i j l : Fin 5) : Fin 5 :=
  ⟨((((rev4373asc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 5, Nat.mod_lt _ (by decide)⟩

theorem rev4373a_subFacts :
    (∀ k x y, (rev4373aSub k (rev4373aP 0 k)).op x y = x) ∧
      (∀ k x y, (rev4373aSub k (rev4373aP 1 k)).op x y = y) ∧
      (∀ k i j l x y, (rev4373aSub k (rev4373aSc k i j l)).op x y =
        (rev4373aSub k i).op ((rev4373aSub k j).op x y) ((rev4373aSub k l).op x y)) ∧
      ∀ k j, ¬ ∀ x y, (rev4373aSub k j).op x y = rev4373a.op x y := by
  decideFin!

theorem rev4373a_isSubclone (k : Fin 1) : IsSubclone (rev4373aSub k) :=
  IsSubclone.of_table (rev4373aP 0 k) (rev4373aP 1 k) (rev4373aSc k)
    (rev4373a_subFacts.1 k) (rev4373a_subFacts.2.1 k) (rev4373a_subFacts.2.2.1 k)

theorem rev4373a_notInSub (k : Fin 1) : ¬ InClone (rev4373aSub k) rev4373a.op :=
  notInClone_of (rev4373a_subFacts.2.2.2 k)

/-- The `1` clone members left over: those that do generate `◇`. -/
def rev4373abd : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0], #[0, 0, 0], #[0, 0, 1]]]

@[implicit_reducible]
def rev4373aBad (b : Fin 1) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((rev4373abd[b.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def rev4373aw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0, 0], #[0, 1, 2, 0, 3, 4], #[0, 0, 0, 0, 0, 0]]

def rev4373aWk (i : Fin 6) : Fin 1 := ⟨((rev4373aw[0]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

def rev4373aWe (i : Fin 6) : Fin 5 := ⟨((rev4373aw[1]!)[i.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def rev4373aWb (i : Fin 6) : Fin 1 := ⟨((rev4373aw[2]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

theorem rev4373a_splitFacts : ∀ i : Fin 6,
    (∀ x y, (rev4373aSub (rev4373aWk i) (rev4373aWe i)).op x y = (rev4373aClone i).op x y) ∨
      (∀ x y, (rev4373aClone i).op x y = (rev4373aBad (rev4373aWb i)).op x y) := by
  decideFin!

theorem rev4373a_split (i : Fin 6) :
    (∃ k, InClone (rev4373aSub k) (rev4373aClone i).op) ∨
      ∃ b, (rev4373aClone i).op = (rev4373aBad b).op :=
  split_of_witnesses rev4373aWk rev4373aWe rev4373aWb rev4373a_splitFacts i

end Magma

theorem rev4373a_sat : @Equation4373 (Fin 3) Magma.rev4373a := by decideFin!
