import equational_theories.Definability.RevF3860c_data

/-!
# Targets `3316`-`4128` against equation `860`

Each target is refuted by every member of `Magma.revF3860cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF3860c_kill3316 : ∀ b : Fin 4, ¬ @Equation3316 (Fin 4) (Magma.revF3860cBad b) := by native_decide

theorem Equation3316_not_termStructuralFromFin_Equation860 :
    ¬ Law3316.TermStructuralFromFin Law860 :=
  not_termStructuralFromFin_of_subclones Magma.revF3860c
    ((@Law860.models_iff (Fin 4) Magma.revF3860c).mpr revF3860c_sat)
    Magma.revF3860c_isCloneFamily Magma.revF3860c_isSubclone Magma.revF3860c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3860cSub k) u)
      Magma.revF3860c_split fun b h ↦ revF3860c_kill3316 b
        ((@Law3316.models_iff (Fin 4) (Magma.revF3860cBad b)).mp h))

theorem revF3860c_kill3519 : ∀ b : Fin 4, ¬ @Equation3519 (Fin 4) (Magma.revF3860cBad b) := by native_decide

theorem Equation3519_not_termStructuralFromFin_Equation860 :
    ¬ Law3519.TermStructuralFromFin Law860 :=
  not_termStructuralFromFin_of_subclones Magma.revF3860c
    ((@Law860.models_iff (Fin 4) Magma.revF3860c).mpr revF3860c_sat)
    Magma.revF3860c_isCloneFamily Magma.revF3860c_isSubclone Magma.revF3860c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3860cSub k) u)
      Magma.revF3860c_split fun b h ↦ revF3860c_kill3519 b
        ((@Law3519.models_iff (Fin 4) (Magma.revF3860cBad b)).mp h))

theorem revF3860c_kill3925 : ∀ b : Fin 4, ¬ @Equation3925 (Fin 4) (Magma.revF3860cBad b) := by native_decide

theorem Equation3925_not_termStructuralFromFin_Equation860 :
    ¬ Law3925.TermStructuralFromFin Law860 :=
  not_termStructuralFromFin_of_subclones Magma.revF3860c
    ((@Law860.models_iff (Fin 4) Magma.revF3860c).mpr revF3860c_sat)
    Magma.revF3860c_isCloneFamily Magma.revF3860c_isSubclone Magma.revF3860c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3860cSub k) u)
      Magma.revF3860c_split fun b h ↦ revF3860c_kill3925 b
        ((@Law3925.models_iff (Fin 4) (Magma.revF3860cBad b)).mp h))

theorem revF3860c_kill4128 : ∀ b : Fin 4, ¬ @Equation4128 (Fin 4) (Magma.revF3860cBad b) := by native_decide

theorem Equation4128_not_termStructuralFromFin_Equation860 :
    ¬ Law4128.TermStructuralFromFin Law860 :=
  not_termStructuralFromFin_of_subclones Magma.revF3860c
    ((@Law860.models_iff (Fin 4) Magma.revF3860c).mpr revF3860c_sat)
    Magma.revF3860c_isCloneFamily Magma.revF3860c_isSubclone Magma.revF3860c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3860cSub k) u)
      Magma.revF3860c_split fun b h ↦ revF3860c_kill4128 b
        ((@Law4128.models_iff (Fin 4) (Magma.revF3860cBad b)).mp h))
