import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 3896 that its own realisations cannot rebuild

`Magma.revF33896b` is a model of equation `3896` on `Fin 4`, and its binary clone has
`9` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.revF33896bSub` lists the `2` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.revF33896bBad` holds the `2` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `3896`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `3896` on `Fin 4` whose binary clone has `9` members. -/
def revF33896bt : Array (Array Nat) :=
  #[#[1, 1, 0, 1], #[1, 1, 1, 1], #[1, 1, 1, 0], #[1, 1, 3, 1]]

@[implicit_reducible]
def revF33896b : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((revF33896bt[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The `9` operations term-definable from `Magma.revF33896b`. -/
def revF33896bcl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1]], #[#[1, 1, 0, 1], #[1, 1, 1, 1], #[1, 1, 1, 0], #[1, 1, 3, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[0, 1, 1, 3], #[1, 1, 0, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 0], #[1, 1, 1, 1]], #[#[1, 1, 0, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 3, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 0, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[0, 1, 1, 3], #[1, 1, 1, 1]]]

@[implicit_reducible]
def revF33896bClone (i : Fin 9) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF33896bcl[i.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.revF33896bClone` lands. -/
def revF33896bcp : Array (Array Nat) :=
  #[#[2, 3, 2, 2, 5, 2, 2, 2, 5], #[4, 2, 2, 7, 2, 2, 7, 2, 2], #[2, 2, 2, 2, 2, 2, 2, 2, 2], #[5, 6, 2, 2, 2, 2, 2, 2, 2], #[8, 7, 2, 2, 2, 2, 2, 2, 2], #[5, 2, 2, 2, 2, 2, 2, 2, 2], #[2, 6, 2, 2, 2, 2, 2, 2, 2], #[2, 7, 2, 2, 2, 2, 2, 2, 2], #[8, 2, 2, 2, 2, 2, 2, 2, 2]]

def revF33896bComp (i j : Fin 9) : Fin 9 :=
  ⟨((revF33896bcp[i.1]!)[j.1]!) % 9, Nat.mod_lt _ (by decide)⟩

theorem revF33896b_cloneProj :
    (∀ x y, (revF33896bClone 0).op x y = x) ∧ (∀ x y, (revF33896bClone 1).op x y = y) := by
  native_decide

theorem revF33896b_cloneComp :
  ∀ i j x y, (revF33896bClone (revF33896bComp i j)).op x y =
    revF33896b.op ((revF33896bClone i).op x y) ((revF33896bClone j).op x y) := by
  native_decide

theorem revF33896b_isCloneFamily :
    revF33896b.IsCloneFamily revF33896bClone 0 1 revF33896bComp :=
  ⟨revF33896b_cloneProj.1, revF33896b_cloneProj.2, revF33896b_cloneComp⟩

/-- The `2` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def revF33896bsb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 0, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 0], #[1, 1, 1, 1]]], #[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[0, 1, 1, 3], #[1, 1, 1, 1]], #[#[1, 1, 0, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 3, 1]]]]

@[implicit_reducible]
def revF33896bSub (k : Fin 2) (j : Fin 5) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((((revF33896bsb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def revF33896bpr : Array (Array Nat) :=
  #[#[0, 0], #[1, 1]]

def revF33896bP (t : Fin 2) (k : Fin 2) : Fin 5 :=
  ⟨((revF33896bpr[t.1]!)[k.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def revF33896bsc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]], #[#[2, 3, 2, 2, 2], #[4, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]], #[#[2, 4, 2, 2, 2], #[3, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]]], #[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]], #[#[2, 3, 2, 3, 2], #[4, 2, 2, 2, 4], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]], #[#[2, 4, 2, 2, 2], #[3, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[3, 2, 2, 2, 2], #[2, 4, 2, 2, 2]]]]

def revF33896bSc (k : Fin 2) (i j l : Fin 5) : Fin 5 :=
  ⟨((((revF33896bsc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 5, Nat.mod_lt _ (by decide)⟩

theorem revF33896b_subFacts :
    (∀ k x y, (revF33896bSub k (revF33896bP 0 k)).op x y = x) ∧
      (∀ k x y, (revF33896bSub k (revF33896bP 1 k)).op x y = y) ∧
      ∀ k j, ¬ ∀ x y, (revF33896bSub k j).op x y = revF33896b.op x y := by
  native_decide

theorem revF33896b_subComp :
  ∀ k i j l x y, (revF33896bSub k (revF33896bSc k i j l)).op x y =
    (revF33896bSub k i).op ((revF33896bSub k j).op x y) ((revF33896bSub k l).op x y) := by
  native_decide

theorem revF33896b_isSubclone (k : Fin 2) : IsSubclone (revF33896bSub k) :=
  IsSubclone.of_table (revF33896bP 0 k) (revF33896bP 1 k) (revF33896bSc k)
    (revF33896b_subFacts.1 k) (revF33896b_subFacts.2.1 k) (revF33896b_subComp k)

theorem revF33896b_notInSub (k : Fin 2) : ¬ InClone (revF33896bSub k) revF33896b.op :=
  notInClone_of (revF33896b_subFacts.2.2 k)

/-- The `2` clone members left over: those that do generate `◇`. -/
def revF33896bbd : Array (Array (Array Nat)) :=
  #[#[#[1, 1, 0, 1], #[1, 1, 1, 1], #[1, 1, 1, 0], #[1, 1, 3, 1]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[0, 1, 1, 3], #[1, 1, 0, 1]]]

@[implicit_reducible]
def revF33896bBad (b : Fin 2) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF33896bbd[b.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def revF33896bw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0, 0, 1, 0, 1], #[0, 1, 2, 0, 0, 4, 4, 3, 3], #[0, 0, 0, 0, 1, 0, 0, 0, 0]]

def revF33896bWk (i : Fin 9) : Fin 2 := ⟨((revF33896bw[0]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

def revF33896bWe (i : Fin 9) : Fin 5 := ⟨((revF33896bw[1]!)[i.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def revF33896bWb (i : Fin 9) : Fin 2 := ⟨((revF33896bw[2]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

theorem revF33896b_splitFacts : ∀ i : Fin 9,
    (∀ x y, (revF33896bSub (revF33896bWk i) (revF33896bWe i)).op x y = (revF33896bClone i).op x y) ∨
      (∀ x y, (revF33896bClone i).op x y = (revF33896bBad (revF33896bWb i)).op x y) := by
  native_decide

theorem revF33896b_split (i : Fin 9) :
    (∃ k, InClone (revF33896bSub k) (revF33896bClone i).op) ∨
      ∃ b, (revF33896bClone i).op = (revF33896bBad b).op :=
  split_of_witnesses revF33896bWk revF33896bWe revF33896bWb revF33896b_splitFacts i

end Magma

theorem revF33896b_sat : @Equation3896 (Fin 4) Magma.revF33896b := by native_decide
