import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 4574 that its own realisations cannot rebuild

`Magma.revF34574b` is a model of equation `4574` on `Fin 4`, and its binary clone has
`6` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.revF34574bSub` lists the `1` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.revF34574bBad` holds the `2` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `4574`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `4574` on `Fin 4` whose binary clone has `6` members. -/
def revF34574bt : Array (Array Nat) :=
  #[#[3, 1, 0, 3], #[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3]]

@[implicit_reducible]
def revF34574b : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((revF34574bt[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The `6` operations term-definable from `Magma.revF34574b`. -/
def revF34574bcl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[3, 3, 3, 3], #[1, 1, 1, 1], #[3, 3, 3, 3], #[3, 3, 3, 3]], #[#[3, 1, 0, 3], #[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3]], #[#[3, 3, 3, 3], #[1, 1, 1, 1], #[0, 3, 3, 3], #[3, 3, 3, 3]], #[#[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3]]]

@[implicit_reducible]
def revF34574bClone (i : Fin 6) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF34574bcl[i.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.revF34574bClone` lands. -/
def revF34574bcp : Array (Array Nat) :=
  #[#[2, 3, 2, 5, 2, 5], #[4, 5, 2, 5, 2, 5], #[2, 5, 2, 5, 2, 5], #[2, 3, 2, 5, 2, 5], #[4, 5, 2, 5, 2, 5], #[2, 5, 2, 5, 2, 5]]

def revF34574bComp (i j : Fin 6) : Fin 6 :=
  ⟨((revF34574bcp[i.1]!)[j.1]!) % 6, Nat.mod_lt _ (by decide)⟩

theorem revF34574b_cloneProj :
    (∀ x y, (revF34574bClone 0).op x y = x) ∧ (∀ x y, (revF34574bClone 1).op x y = y) := by
  native_decide

theorem revF34574b_cloneComp :
  ∀ i j x y, (revF34574bClone (revF34574bComp i j)).op x y =
    revF34574b.op ((revF34574bClone i).op x y) ((revF34574bClone j).op x y) := by
  native_decide

theorem revF34574b_isCloneFamily :
    revF34574b.IsCloneFamily revF34574bClone 0 1 revF34574bComp :=
  ⟨revF34574b_cloneProj.1, revF34574b_cloneProj.2, revF34574b_cloneComp⟩

/-- The `1` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def revF34574bsb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[3, 3, 3, 3], #[1, 1, 1, 1], #[3, 3, 3, 3], #[3, 3, 3, 3]], #[#[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3]]]]

@[implicit_reducible]
def revF34574bSub (k : Fin 1) (j : Fin 4) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((((revF34574bsb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def revF34574bpr : Array (Array Nat) :=
  #[#[0], #[1]]

def revF34574bP (t : Fin 2) (k : Fin 1) : Fin 4 :=
  ⟨((revF34574bpr[t.1]!)[k.1]!) % 4, Nat.mod_lt _ (by decide)⟩

def revF34574bsc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[2, 2, 2, 2], #[3, 3, 3, 3], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[2, 3, 2, 3], #[2, 3, 2, 3], #[2, 3, 2, 3], #[2, 3, 2, 3]]]]

def revF34574bSc (k : Fin 1) (i j l : Fin 4) : Fin 4 :=
  ⟨((((revF34574bsc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 4, Nat.mod_lt _ (by decide)⟩

theorem revF34574b_subFacts :
    (∀ k x y, (revF34574bSub k (revF34574bP 0 k)).op x y = x) ∧
      (∀ k x y, (revF34574bSub k (revF34574bP 1 k)).op x y = y) ∧
      ∀ k j, ¬ ∀ x y, (revF34574bSub k j).op x y = revF34574b.op x y := by
  native_decide

theorem revF34574b_subComp :
  ∀ k i j l x y, (revF34574bSub k (revF34574bSc k i j l)).op x y =
    (revF34574bSub k i).op ((revF34574bSub k j).op x y) ((revF34574bSub k l).op x y) := by
  native_decide

theorem revF34574b_isSubclone (k : Fin 1) : IsSubclone (revF34574bSub k) :=
  IsSubclone.of_table (revF34574bP 0 k) (revF34574bP 1 k) (revF34574bSc k)
    (revF34574b_subFacts.1 k) (revF34574b_subFacts.2.1 k) (revF34574b_subComp k)

theorem revF34574b_notInSub (k : Fin 1) : ¬ InClone (revF34574bSub k) revF34574b.op :=
  notInClone_of (revF34574b_subFacts.2.2 k)

/-- The `2` clone members left over: those that do generate `◇`. -/
def revF34574bbd : Array (Array (Array Nat)) :=
  #[#[#[3, 1, 0, 3], #[3, 1, 3, 3], #[3, 1, 3, 3], #[3, 1, 3, 3]], #[#[3, 3, 3, 3], #[1, 1, 1, 1], #[0, 3, 3, 3], #[3, 3, 3, 3]]]

@[implicit_reducible]
def revF34574bBad (b : Fin 2) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF34574bbd[b.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def revF34574bw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0, 0], #[0, 1, 2, 0, 0, 3], #[0, 0, 0, 0, 1, 0]]

def revF34574bWk (i : Fin 6) : Fin 1 := ⟨((revF34574bw[0]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

def revF34574bWe (i : Fin 6) : Fin 4 := ⟨((revF34574bw[1]!)[i.1]!) % 4, Nat.mod_lt _ (by decide)⟩

def revF34574bWb (i : Fin 6) : Fin 2 := ⟨((revF34574bw[2]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

theorem revF34574b_splitFacts : ∀ i : Fin 6,
    (∀ x y, (revF34574bSub (revF34574bWk i) (revF34574bWe i)).op x y = (revF34574bClone i).op x y) ∨
      (∀ x y, (revF34574bClone i).op x y = (revF34574bBad (revF34574bWb i)).op x y) := by
  native_decide

theorem revF34574b_split (i : Fin 6) :
    (∃ k, InClone (revF34574bSub k) (revF34574bClone i).op) ∨
      ∃ b, (revF34574bClone i).op = (revF34574bBad b).op :=
  split_of_witnesses revF34574bWk revF34574bWe revF34574bWb revF34574b_splitFacts i

end Magma

theorem revF34574b_sat : @Equation4574 (Fin 4) Magma.revF34574b := by native_decide
