import equational_theories.Definability.RevF31431a_data

/-!
# Targets `3316`-`4128` against equation `1431`

Each target is refuted by every member of `Magma.revF31431aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF31431a_kill3316 : ∀ b : Fin 4, ¬ @Equation3316 (Fin 4) (Magma.revF31431aBad b) := by native_decide

theorem Equation3316_not_termStructuralFromFin_Equation1431 :
    ¬ Law3316.TermStructuralFromFin Law1431 :=
  not_termStructuralFromFin_of_subclones Magma.revF31431a
    ((@Law1431.models_iff (Fin 4) Magma.revF31431a).mpr revF31431a_sat)
    Magma.revF31431a_isCloneFamily Magma.revF31431a_isSubclone Magma.revF31431a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31431aSub k) u)
      Magma.revF31431a_split fun b h ↦ revF31431a_kill3316 b
        ((@Law3316.models_iff (Fin 4) (Magma.revF31431aBad b)).mp h))

theorem revF31431a_kill4128 : ∀ b : Fin 4, ¬ @Equation4128 (Fin 4) (Magma.revF31431aBad b) := by native_decide

theorem Equation4128_not_termStructuralFromFin_Equation1431 :
    ¬ Law4128.TermStructuralFromFin Law1431 :=
  not_termStructuralFromFin_of_subclones Magma.revF31431a
    ((@Law1431.models_iff (Fin 4) Magma.revF31431a).mpr revF31431a_sat)
    Magma.revF31431a_isCloneFamily Magma.revF31431a_isSubclone Magma.revF31431a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31431aSub k) u)
      Magma.revF31431a_split fun b h ↦ revF31431a_kill4128 b
        ((@Law4128.models_iff (Fin 4) (Magma.revF31431aBad b)).mp h))
