import equational_theories.Definability.RevF33480c_data

/-!
# Targets `3669`-`3705` against equation `3480`

Each target is refuted by every member of `Magma.revF33480cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33480c_kill3669 : ∀ b : Fin 2, ¬ @Equation3669 (Fin 5) (Magma.revF33480cBad b) := by native_decide

theorem Equation3669_not_termStructuralFromFin_Equation3480 :
    ¬ Law3669.TermStructuralFromFin Law3480 :=
  not_termStructuralFromFin_of_subclones Magma.revF33480c
    ((@Law3480.models_iff (Fin 5) Magma.revF33480c).mpr revF33480c_sat)
    Magma.revF33480c_isCloneFamily Magma.revF33480c_isSubclone Magma.revF33480c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33480cSub k) u)
      Magma.revF33480c_split fun b h ↦ revF33480c_kill3669 b
        ((@Law3669.models_iff (Fin 5) (Magma.revF33480cBad b)).mp h))

theorem revF33480c_kill3676 : ∀ b : Fin 2, ¬ @Equation3676 (Fin 5) (Magma.revF33480cBad b) := by native_decide

theorem Equation3676_not_termStructuralFromFin_Equation3480 :
    ¬ Law3676.TermStructuralFromFin Law3480 :=
  not_termStructuralFromFin_of_subclones Magma.revF33480c
    ((@Law3480.models_iff (Fin 5) Magma.revF33480c).mpr revF33480c_sat)
    Magma.revF33480c_isCloneFamily Magma.revF33480c_isSubclone Magma.revF33480c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33480cSub k) u)
      Magma.revF33480c_split fun b h ↦ revF33480c_kill3676 b
        ((@Law3676.models_iff (Fin 5) (Magma.revF33480cBad b)).mp h))

theorem revF33480c_kill3702 : ∀ b : Fin 2, ¬ @Equation3702 (Fin 5) (Magma.revF33480cBad b) := by native_decide

theorem Equation3702_not_termStructuralFromFin_Equation3480 :
    ¬ Law3702.TermStructuralFromFin Law3480 :=
  not_termStructuralFromFin_of_subclones Magma.revF33480c
    ((@Law3480.models_iff (Fin 5) Magma.revF33480c).mpr revF33480c_sat)
    Magma.revF33480c_isCloneFamily Magma.revF33480c_isSubclone Magma.revF33480c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33480cSub k) u)
      Magma.revF33480c_split fun b h ↦ revF33480c_kill3702 b
        ((@Law3702.models_iff (Fin 5) (Magma.revF33480cBad b)).mp h))

theorem revF33480c_kill3705 : ∀ b : Fin 2, ¬ @Equation3705 (Fin 5) (Magma.revF33480cBad b) := by native_decide

theorem Equation3705_not_termStructuralFromFin_Equation3480 :
    ¬ Law3705.TermStructuralFromFin Law3480 :=
  not_termStructuralFromFin_of_subclones Magma.revF33480c
    ((@Law3480.models_iff (Fin 5) Magma.revF33480c).mpr revF33480c_sat)
    Magma.revF33480c_isCloneFamily Magma.revF33480c_isSubclone Magma.revF33480c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33480cSub k) u)
      Magma.revF33480c_split fun b h ↦ revF33480c_kill3705 b
        ((@Law3705.models_iff (Fin 5) (Magma.revF33480cBad b)).mp h))
