import equational_theories.Definability.RevF33683d_data

/-!
# Targets `4283`-`4635` against equation `3683`

Each target is refuted by every member of `Magma.revF33683dBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33683d_kill4283 : ∀ b : Fin 2, ¬ @Equation4283 (Fin 4) (Magma.revF33683dBad b) := by native_decide

theorem Equation4283_not_termStructuralFromFin_Equation3683 :
    ¬ Law4283.TermStructuralFromFin Law3683 :=
  not_termStructuralFromFin_of_subclones Magma.revF33683d
    ((@Law3683.models_iff (Fin 4) Magma.revF33683d).mpr revF33683d_sat)
    Magma.revF33683d_isCloneFamily Magma.revF33683d_isSubclone Magma.revF33683d_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33683dSub k) u)
      Magma.revF33683d_split fun b h ↦ revF33683d_kill4283 b
        ((@Law4283.models_iff (Fin 4) (Magma.revF33683dBad b)).mp h))

theorem revF33683d_kill4635 : ∀ b : Fin 2, ¬ @Equation4635 (Fin 4) (Magma.revF33683dBad b) := by native_decide

theorem Equation4635_not_termStructuralFromFin_Equation3683 :
    ¬ Law4635.TermStructuralFromFin Law3683 :=
  not_termStructuralFromFin_of_subclones Magma.revF33683d
    ((@Law3683.models_iff (Fin 4) Magma.revF33683d).mpr revF33683d_sat)
    Magma.revF33683d_isCloneFamily Magma.revF33683d_isSubclone Magma.revF33683d_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33683dSub k) u)
      Magma.revF33683d_split fun b h ↦ revF33683d_kill4635 b
        ((@Law4635.models_iff (Fin 4) (Magma.revF33683dBad b)).mp h))
