import equational_theories.Definability.RevF34529b_data

/-!
# Targets `4283`-`4635` against equation `4529`

Each target is refuted by every member of `Magma.revF34529bBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34529b_kill4283 : ∀ b : Fin 2, ¬ @Equation4283 (Fin 4) (Magma.revF34529bBad b) := by native_decide

theorem Equation4283_not_termStructuralFromFin_Equation4529 :
    ¬ Law4283.TermStructuralFromFin Law4529 :=
  not_termStructuralFromFin_of_subclones Magma.revF34529b
    ((@Law4529.models_iff (Fin 4) Magma.revF34529b).mpr revF34529b_sat)
    Magma.revF34529b_isCloneFamily Magma.revF34529b_isSubclone Magma.revF34529b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34529bSub k) u)
      Magma.revF34529b_split fun b h ↦ revF34529b_kill4283 b
        ((@Law4283.models_iff (Fin 4) (Magma.revF34529bBad b)).mp h))

theorem revF34529b_kill4398 : ∀ b : Fin 2, ¬ @Equation4398 (Fin 4) (Magma.revF34529bBad b) := by native_decide

theorem Equation4398_not_termStructuralFromFin_Equation4529 :
    ¬ Law4398.TermStructuralFromFin Law4529 :=
  not_termStructuralFromFin_of_subclones Magma.revF34529b
    ((@Law4529.models_iff (Fin 4) Magma.revF34529b).mpr revF34529b_sat)
    Magma.revF34529b_isCloneFamily Magma.revF34529b_isSubclone Magma.revF34529b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34529bSub k) u)
      Magma.revF34529b_split fun b h ↦ revF34529b_kill4398 b
        ((@Law4398.models_iff (Fin 4) (Magma.revF34529bBad b)).mp h))

theorem revF34529b_kill4442 : ∀ b : Fin 2, ¬ @Equation4442 (Fin 4) (Magma.revF34529bBad b) := by native_decide

theorem Equation4442_not_termStructuralFromFin_Equation4529 :
    ¬ Law4442.TermStructuralFromFin Law4529 :=
  not_termStructuralFromFin_of_subclones Magma.revF34529b
    ((@Law4529.models_iff (Fin 4) Magma.revF34529b).mpr revF34529b_sat)
    Magma.revF34529b_isCloneFamily Magma.revF34529b_isSubclone Magma.revF34529b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34529bSub k) u)
      Magma.revF34529b_split fun b h ↦ revF34529b_kill4442 b
        ((@Law4442.models_iff (Fin 4) (Magma.revF34529bBad b)).mp h))

theorem revF34529b_kill4635 : ∀ b : Fin 2, ¬ @Equation4635 (Fin 4) (Magma.revF34529bBad b) := by native_decide

theorem Equation4635_not_termStructuralFromFin_Equation4529 :
    ¬ Law4635.TermStructuralFromFin Law4529 :=
  not_termStructuralFromFin_of_subclones Magma.revF34529b
    ((@Law4529.models_iff (Fin 4) Magma.revF34529b).mpr revF34529b_sat)
    Magma.revF34529b_isCloneFamily Magma.revF34529b_isSubclone Magma.revF34529b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34529bSub k) u)
      Magma.revF34529b_split fun b h ↦ revF34529b_kill4635 b
        ((@Law4635.models_iff (Fin 4) (Magma.revF34529bBad b)).mp h))
