import equational_theories.Definability.RevF33728a_data

/-!
# Targets `3456`-`4380` against equation `3728`

Each target is refuted by every member of `Magma.revF33728aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33728a_kill3456 : ∀ b : Fin 2, ¬ @Equation3456 (Fin 3) (Magma.revF33728aBad b) := by native_decide

theorem Equation3456_not_termStructuralFromFin_Equation3728 :
    ¬ Law3456.TermStructuralFromFin Law3728 :=
  not_termStructuralFromFin_of_subclones Magma.revF33728a
    ((@Law3728.models_iff (Fin 3) Magma.revF33728a).mpr revF33728a_sat)
    Magma.revF33728a_isCloneFamily Magma.revF33728a_isSubclone Magma.revF33728a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33728aSub k) u)
      Magma.revF33728a_split fun b h ↦ revF33728a_kill3456 b
        ((@Law3456.models_iff (Fin 3) (Magma.revF33728aBad b)).mp h))

theorem revF33728a_kill3862 : ∀ b : Fin 2, ¬ @Equation3862 (Fin 3) (Magma.revF33728aBad b) := by native_decide

theorem Equation3862_not_termStructuralFromFin_Equation3728 :
    ¬ Law3862.TermStructuralFromFin Law3728 :=
  not_termStructuralFromFin_of_subclones Magma.revF33728a
    ((@Law3728.models_iff (Fin 3) Magma.revF33728a).mpr revF33728a_sat)
    Magma.revF33728a_isCloneFamily Magma.revF33728a_isSubclone Magma.revF33728a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33728aSub k) u)
      Magma.revF33728a_split fun b h ↦ revF33728a_kill3862 b
        ((@Law3862.models_iff (Fin 3) (Magma.revF33728aBad b)).mp h))

theorem revF33728a_kill4380 : ∀ b : Fin 2, ¬ @Equation4380 (Fin 3) (Magma.revF33728aBad b) := by native_decide

theorem Equation4380_not_termStructuralFromFin_Equation3728 :
    ¬ Law4380.TermStructuralFromFin Law3728 :=
  not_termStructuralFromFin_of_subclones Magma.revF33728a
    ((@Law3728.models_iff (Fin 3) Magma.revF33728a).mpr revF33728a_sat)
    Magma.revF33728a_isCloneFamily Magma.revF33728a_isSubclone Magma.revF33728a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33728aSub k) u)
      Magma.revF33728a_split fun b h ↦ revF33728a_kill4380 b
        ((@Law4380.models_iff (Fin 3) (Magma.revF33728aBad b)).mp h))
