import equational_theories.Definability.RevF34112c_data

/-!
# Targets `308`-`4666` against equation `4112`

Each target is refuted by every member of `Magma.revF34112cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34112c_kill308 : ∀ b : Fin 2, ¬ @Equation308 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation308_not_termStructuralFromFin_Equation4112 :
    ¬ Law308.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill308 b
        ((@Law308.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill364 : ∀ b : Fin 2, ¬ @Equation364 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation364_not_termStructuralFromFin_Equation4112 :
    ¬ Law364.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill364 b
        ((@Law364.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4268 : ∀ b : Fin 2, ¬ @Equation4268 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4268_not_termStructuralFromFin_Equation4112 :
    ¬ Law4268.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4268 b
        ((@Law4268.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4282 : ∀ b : Fin 2, ¬ @Equation4282 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4282_not_termStructuralFromFin_Equation4112 :
    ¬ Law4282.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4282 b
        ((@Law4282.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4284 : ∀ b : Fin 2, ¬ @Equation4284 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4284_not_termStructuralFromFin_Equation4112 :
    ¬ Law4284.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4284 b
        ((@Law4284.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4288 : ∀ b : Fin 2, ¬ @Equation4288 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4288_not_termStructuralFromFin_Equation4112 :
    ¬ Law4288.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4288 b
        ((@Law4288.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4587 : ∀ b : Fin 2, ¬ @Equation4587 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4587_not_termStructuralFromFin_Equation4112 :
    ¬ Law4587.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4587 b
        ((@Law4587.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4599 : ∀ b : Fin 2, ¬ @Equation4599 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4599_not_termStructuralFromFin_Equation4112 :
    ¬ Law4599.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4599 b
        ((@Law4599.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4619 : ∀ b : Fin 2, ¬ @Equation4619 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4619_not_termStructuralFromFin_Equation4112 :
    ¬ Law4619.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4619 b
        ((@Law4619.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))

theorem revF34112c_kill4666 : ∀ b : Fin 2, ¬ @Equation4666 (Fin 5) (Magma.revF34112cBad b) := by native_decide

theorem Equation4666_not_termStructuralFromFin_Equation4112 :
    ¬ Law4666.TermStructuralFromFin Law4112 :=
  not_termStructuralFromFin_of_subclones Magma.revF34112c
    ((@Law4112.models_iff (Fin 5) Magma.revF34112c).mpr revF34112c_sat)
    Magma.revF34112c_isCloneFamily Magma.revF34112c_isSubclone Magma.revF34112c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34112cSub k) u)
      Magma.revF34112c_split fun b h ↦ revF34112c_kill4666 b
        ((@Law4666.models_iff (Fin 5) (Magma.revF34112cBad b)).mp h))
