import equational_theories.Definability.RevF32710a_data

/-!
# Targets `3659`-`3659` against equation `2710`

Each target is refuted by every member of `Magma.revF32710aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF32710a_kill3659 : ∀ b : Fin 12, ¬ @Equation3659 (Fin 5) (Magma.revF32710aBad b) := by native_decide

theorem Equation3659_not_termStructuralFromFin_Equation2710 :
    ¬ Law3659.TermStructuralFromFin Law2710 :=
  not_termStructuralFromFin_of_subclones Magma.revF32710a
    ((@Law2710.models_iff (Fin 5) Magma.revF32710a).mpr revF32710a_sat)
    Magma.revF32710a_isCloneFamily Magma.revF32710a_isSubclone Magma.revF32710a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF32710aSub k) u)
      Magma.revF32710a_split fun b h ↦ revF32710a_kill3659 b
        ((@Law3659.models_iff (Fin 5) (Magma.revF32710aBad b)).mp h))
