import equational_theories.Definability.RevF33541c_data

/-!
# Targets `4269`-`4675` against equation `3541`

Each target is refuted by every member of `Magma.revF33541cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33541c_kill4269 : ∀ b : Fin 4, ¬ @Equation4269 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4269_not_termStructuralFromFin_Equation3541 :
    ¬ Law4269.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4269 b
        ((@Law4269.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4287 : ∀ b : Fin 4, ¬ @Equation4287 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4287_not_termStructuralFromFin_Equation3541 :
    ¬ Law4287.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4287 b
        ((@Law4287.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4316 : ∀ b : Fin 4, ¬ @Equation4316 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4316_not_termStructuralFromFin_Equation3541 :
    ¬ Law4316.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4316 b
        ((@Law4316.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4340 : ∀ b : Fin 4, ¬ @Equation4340 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4340_not_termStructuralFromFin_Equation3541 :
    ¬ Law4340.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4340 b
        ((@Law4340.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4360 : ∀ b : Fin 4, ¬ @Equation4360 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4360_not_termStructuralFromFin_Equation3541 :
    ¬ Law4360.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4360 b
        ((@Law4360.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4584 : ∀ b : Fin 4, ¬ @Equation4584 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4584_not_termStructuralFromFin_Equation3541 :
    ¬ Law4584.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4584 b
        ((@Law4584.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4602 : ∀ b : Fin 4, ¬ @Equation4602 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4602_not_termStructuralFromFin_Equation3541 :
    ¬ Law4602.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4602 b
        ((@Law4602.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4631 : ∀ b : Fin 4, ¬ @Equation4631 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4631_not_termStructuralFromFin_Equation3541 :
    ¬ Law4631.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4631 b
        ((@Law4631.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4655 : ∀ b : Fin 4, ¬ @Equation4655 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4655_not_termStructuralFromFin_Equation3541 :
    ¬ Law4655.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4655 b
        ((@Law4655.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))

theorem revF33541c_kill4675 : ∀ b : Fin 4, ¬ @Equation4675 (Fin 4) (Magma.revF33541cBad b) := by native_decide

theorem Equation4675_not_termStructuralFromFin_Equation3541 :
    ¬ Law4675.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541c
    ((@Law3541.models_iff (Fin 4) Magma.revF33541c).mpr revF33541c_sat)
    Magma.revF33541c_isCloneFamily Magma.revF33541c_isSubclone Magma.revF33541c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541cSub k) u)
      Magma.revF33541c_split fun b h ↦ revF33541c_kill4675 b
        ((@Law4675.models_iff (Fin 4) (Magma.revF33541cBad b)).mp h))
