import equational_theories.Definability.RevF31061a_data

/-!
# Targets `4380`-`4469` against equation `1061`

Each target is refuted by every member of `Magma.revF31061aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF31061a_kill4380 : ∀ b : Fin 2, ¬ @Equation4380 (Fin 3) (Magma.revF31061aBad b) := by native_decide

theorem Equation4380_not_termStructuralFromFin_Equation1061 :
    ¬ Law4380.TermStructuralFromFin Law1061 :=
  not_termStructuralFromFin_of_subclones Magma.revF31061a
    ((@Law1061.models_iff (Fin 3) Magma.revF31061a).mpr revF31061a_sat)
    Magma.revF31061a_isCloneFamily Magma.revF31061a_isSubclone Magma.revF31061a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31061aSub k) u)
      Magma.revF31061a_split fun b h ↦ revF31061a_kill4380 b
        ((@Law4380.models_iff (Fin 3) (Magma.revF31061aBad b)).mp h))

theorem revF31061a_kill4388 : ∀ b : Fin 2, ¬ @Equation4388 (Fin 3) (Magma.revF31061aBad b) := by native_decide

theorem Equation4388_not_termStructuralFromFin_Equation1061 :
    ¬ Law4388.TermStructuralFromFin Law1061 :=
  not_termStructuralFromFin_of_subclones Magma.revF31061a
    ((@Law1061.models_iff (Fin 3) Magma.revF31061a).mpr revF31061a_sat)
    Magma.revF31061a_isCloneFamily Magma.revF31061a_isSubclone Magma.revF31061a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31061aSub k) u)
      Magma.revF31061a_split fun b h ↦ revF31061a_kill4388 b
        ((@Law4388.models_iff (Fin 3) (Magma.revF31061aBad b)).mp h))

theorem revF31061a_kill4435 : ∀ b : Fin 2, ¬ @Equation4435 (Fin 3) (Magma.revF31061aBad b) := by native_decide

theorem Equation4435_not_termStructuralFromFin_Equation1061 :
    ¬ Law4435.TermStructuralFromFin Law1061 :=
  not_termStructuralFromFin_of_subclones Magma.revF31061a
    ((@Law1061.models_iff (Fin 3) Magma.revF31061a).mpr revF31061a_sat)
    Magma.revF31061a_isCloneFamily Magma.revF31061a_isSubclone Magma.revF31061a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31061aSub k) u)
      Magma.revF31061a_split fun b h ↦ revF31061a_kill4435 b
        ((@Law4435.models_iff (Fin 3) (Magma.revF31061aBad b)).mp h))

theorem revF31061a_kill4469 : ∀ b : Fin 2, ¬ @Equation4469 (Fin 3) (Magma.revF31061aBad b) := by native_decide

theorem Equation4469_not_termStructuralFromFin_Equation1061 :
    ¬ Law4469.TermStructuralFromFin Law1061 :=
  not_termStructuralFromFin_of_subclones Magma.revF31061a
    ((@Law1061.models_iff (Fin 3) Magma.revF31061a).mpr revF31061a_sat)
    Magma.revF31061a_isCloneFamily Magma.revF31061a_isSubclone Magma.revF31061a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF31061aSub k) u)
      Magma.revF31061a_split fun b h ↦ revF31061a_kill4469 b
        ((@Law4469.models_iff (Fin 3) (Magma.revF31061aBad b)).mp h))
