import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 1233 that its own realisations cannot rebuild

`Magma.revF31233b` is a model of equation `1233` on `Fin 5`, and its binary clone has
`8` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.revF31233bSub` lists the `1` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.revF31233bBad` holds the `2` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `1233`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `1233` on `Fin 5` whose binary clone has `8` members. -/
def revF31233bt : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0], #[1, 1, 0, 1, 3], #[2, 0, 2, 0, 2], #[3, 0, 0, 3, 0], #[4, 3, 4, 4, 4]]

@[implicit_reducible]
def revF31233b : Magma (Fin 5) :=
  ⟨fun x y ↦ ⟨((revF31233bt[x.1]!)[y.1]!) % 5, Nat.mod_lt _ (by decide)⟩⟩

/-- The `8` operations term-definable from `Magma.revF31233b`. -/
def revF31233bcl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[0, 0, 0, 0, 0], #[1, 1, 0, 1, 3], #[2, 0, 2, 0, 2], #[3, 0, 0, 3, 0], #[4, 3, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 0, 0, 3], #[0, 0, 2, 0, 4], #[0, 1, 0, 3, 4], #[0, 3, 2, 0, 4]], #[#[0, 0, 0, 0, 0], #[1, 1, 0, 1, 0], #[2, 0, 2, 0, 2], #[3, 0, 0, 3, 0], #[4, 0, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 0, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 0, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 0, 0, 0], #[0, 0, 2, 0, 4], #[0, 1, 0, 3, 4], #[0, 0, 2, 0, 4]], #[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 0, 3, 3, 0], #[4, 4, 4, 4, 4]]]

@[implicit_reducible]
def revF31233bClone (i : Fin 8) : Magma (Fin 5) :=
  ⟨fun x y ↦ ⟨(((revF31233bcl[i.1]!)[x.1]!)[y.1]!) % 5, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.revF31233bClone` lands. -/
def revF31233bcp : Array (Array Nat) :=
  #[#[0, 2, 0, 7, 0, 2, 7, 0], #[3, 1, 5, 1, 5, 1, 1, 3], #[4, 4, 2, 2, 2, 4, 2, 4], #[6, 6, 3, 3, 3, 6, 3, 6], #[4, 4, 4, 4, 4, 4, 4, 4], #[3, 5, 5, 5, 5, 5, 5, 3], #[6, 6, 6, 6, 6, 6, 6, 6], #[7, 2, 7, 7, 7, 2, 7, 7]]

def revF31233bComp (i j : Fin 8) : Fin 8 :=
  ⟨((revF31233bcp[i.1]!)[j.1]!) % 8, Nat.mod_lt _ (by decide)⟩

theorem revF31233b_cloneProj :
    (∀ x y, (revF31233bClone 0).op x y = x) ∧ (∀ x y, (revF31233bClone 1).op x y = y) := by
  native_decide

theorem revF31233b_cloneComp :
  ∀ i j x y, (revF31233bClone (revF31233bComp i j)).op x y =
    revF31233b.op ((revF31233bClone i).op x y) ((revF31233bClone j).op x y) := by
  native_decide

theorem revF31233b_isCloneFamily :
    revF31233b.IsCloneFamily revF31233bClone 0 1 revF31233bComp :=
  ⟨revF31233b_cloneProj.1, revF31233b_cloneProj.2, revF31233b_cloneComp⟩

/-- The `1` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def revF31233bsb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 0, 0, 0], #[0, 0, 2, 0, 4], #[0, 1, 0, 3, 4], #[0, 0, 2, 0, 4]], #[#[0, 0, 0, 0, 0], #[1, 1, 0, 1, 0], #[2, 0, 2, 0, 2], #[3, 0, 0, 3, 0], #[4, 0, 4, 4, 4]], #[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 0, 3, 3, 0], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 0, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 0, 4]]]]

@[implicit_reducible]
def revF31233bSub (k : Fin 1) (j : Fin 6) : Magma (Fin 5) :=
  ⟨fun x y ↦ ⟨((((revF31233bsb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 5, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def revF31233bpr : Array (Array Nat) :=
  #[#[0], #[1]]

def revF31233bP (t : Fin 2) (k : Fin 1) : Fin 6 :=
  ⟨((revF31233bpr[t.1]!)[k.1]!) % 6, Nat.mod_lt _ (by decide)⟩

def revF31233bsc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0, 0], #[1, 1, 1, 1, 1, 1], #[2, 2, 2, 2, 2, 2], #[3, 3, 3, 3, 3, 3], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5]], #[#[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5]], #[#[0, 2, 2, 3, 4, 2], #[3, 1, 2, 3, 3, 5], #[4, 1, 2, 3, 4, 5], #[0, 5, 2, 3, 4, 5], #[0, 2, 2, 3, 4, 2], #[3, 1, 2, 3, 3, 5]], #[#[0, 3, 4, 0, 0, 3], #[2, 1, 1, 5, 2, 1], #[2, 2, 2, 2, 2, 2], #[3, 3, 3, 3, 3, 3], #[4, 3, 4, 4, 4, 3], #[2, 5, 5, 5, 2, 5]], #[#[0, 4, 4, 0, 0, 4], #[5, 1, 1, 5, 5, 1], #[2, 2, 2, 2, 2, 2], #[3, 3, 3, 3, 3, 3], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5]], #[#[0, 5, 2, 3, 4, 5], #[4, 1, 2, 3, 4, 5], #[4, 1, 2, 3, 4, 5], #[0, 5, 2, 3, 4, 5], #[0, 5, 2, 3, 4, 5], #[4, 1, 2, 3, 4, 5]]]]

def revF31233bSc (k : Fin 1) (i j l : Fin 6) : Fin 6 :=
  ⟨((((revF31233bsc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 6, Nat.mod_lt _ (by decide)⟩

theorem revF31233b_subFacts :
    (∀ k x y, (revF31233bSub k (revF31233bP 0 k)).op x y = x) ∧
      (∀ k x y, (revF31233bSub k (revF31233bP 1 k)).op x y = y) ∧
      ∀ k j, ¬ ∀ x y, (revF31233bSub k j).op x y = revF31233b.op x y := by
  native_decide

theorem revF31233b_subComp :
  ∀ k i j l x y, (revF31233bSub k (revF31233bSc k i j l)).op x y =
    (revF31233bSub k i).op ((revF31233bSub k j).op x y) ((revF31233bSub k l).op x y) := by
  native_decide

theorem revF31233b_isSubclone (k : Fin 1) : IsSubclone (revF31233bSub k) :=
  IsSubclone.of_table (revF31233bP 0 k) (revF31233bP 1 k) (revF31233bSc k)
    (revF31233b_subFacts.1 k) (revF31233b_subFacts.2.1 k) (revF31233b_subComp k)

theorem revF31233b_notInSub (k : Fin 1) : ¬ InClone (revF31233bSub k) revF31233b.op :=
  notInClone_of (revF31233b_subFacts.2.2 k)

/-- The `2` clone members left over: those that do generate `◇`. -/
def revF31233bbd : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0, 0, 0], #[1, 1, 0, 1, 3], #[2, 0, 2, 0, 2], #[3, 0, 0, 3, 0], #[4, 3, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 0, 0, 3], #[0, 0, 2, 0, 4], #[0, 1, 0, 3, 4], #[0, 3, 2, 0, 4]]]

@[implicit_reducible]
def revF31233bBad (b : Fin 2) : Magma (Fin 5) :=
  ⟨fun x y ↦ ⟨(((revF31233bbd[b.1]!)[x.1]!)[y.1]!) % 5, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def revF31233bw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 1, 0, 0, 3, 5, 2, 4], #[0, 0, 0, 1, 0, 0, 0, 0]]

def revF31233bWk (i : Fin 8) : Fin 1 := ⟨((revF31233bw[0]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

def revF31233bWe (i : Fin 8) : Fin 6 := ⟨((revF31233bw[1]!)[i.1]!) % 6, Nat.mod_lt _ (by decide)⟩

def revF31233bWb (i : Fin 8) : Fin 2 := ⟨((revF31233bw[2]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

theorem revF31233b_splitFacts : ∀ i : Fin 8,
    (∀ x y, (revF31233bSub (revF31233bWk i) (revF31233bWe i)).op x y = (revF31233bClone i).op x y) ∨
      (∀ x y, (revF31233bClone i).op x y = (revF31233bBad (revF31233bWb i)).op x y) := by
  native_decide

theorem revF31233b_split (i : Fin 8) :
    (∃ k, InClone (revF31233bSub k) (revF31233bClone i).op) ∨
      ∃ b, (revF31233bClone i).op = (revF31233bBad b).op :=
  split_of_witnesses revF31233bWk revF31233bWe revF31233bWb revF31233b_splitFacts i

end Magma

theorem revF31233b_sat : @Equation1233 (Fin 5) Magma.revF31233b := by native_decide
