import equational_theories.Definability.RevF34443a_data

/-!
# Targets `4435`-`4435` against equation `4443`

Each target is refuted by every member of `Magma.revF34443aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34443a_kill4435 : ∀ b : Fin 2, ¬ @Equation4435 (Fin 4) (Magma.revF34443aBad b) := by native_decide

theorem Equation4435_not_termStructuralFromFin_Equation4443 :
    ¬ Law4435.TermStructuralFromFin Law4443 :=
  not_termStructuralFromFin_of_subclones Magma.revF34443a
    ((@Law4443.models_iff (Fin 4) Magma.revF34443a).mpr revF34443a_sat)
    Magma.revF34443a_isCloneFamily Magma.revF34443a_isSubclone Magma.revF34443a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34443aSub k) u)
      Magma.revF34443a_split fun b h ↦ revF34443a_kill4435 b
        ((@Law4435.models_iff (Fin 4) (Magma.revF34443aBad b)).mp h))
