import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 4603 that its own realisations cannot rebuild

`Magma.revF34603b` is a model of equation `4603` on `Fin 4`, and its binary clone has
`8` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.revF34603bSub` lists the `1` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.revF34603bBad` holds the `2` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `4603`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `4603` on `Fin 4` whose binary clone has `8` members. -/
def revF34603bt : Array (Array Nat) :=
  #[#[2, 2, 2, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]]

@[implicit_reducible]
def revF34603b : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((revF34603bt[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The `8` operations term-definable from `Magma.revF34603b`. -/
def revF34603bcl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[2, 2, 2, 2], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[2, 2, 2, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3], #[1, 1, 1, 3]], #[#[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[1, 1, 1, 3], #[1, 1, 1, 3], #[1, 1, 1, 3], #[1, 1, 1, 3]]]

@[implicit_reducible]
def revF34603bClone (i : Fin 8) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF34603bcl[i.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.revF34603bClone` lands. -/
def revF34603bcp : Array (Array Nat) :=
  #[#[2, 3, 2, 2, 3, 3, 2, 3], #[4, 5, 4, 4, 5, 5, 4, 5], #[6, 6, 6, 6, 6, 6, 6, 6], #[6, 6, 6, 6, 6, 6, 6, 6], #[7, 7, 7, 7, 7, 7, 7, 7], #[7, 7, 7, 7, 7, 7, 7, 7], #[6, 6, 6, 6, 6, 6, 6, 6], #[7, 7, 7, 7, 7, 7, 7, 7]]

def revF34603bComp (i j : Fin 8) : Fin 8 :=
  ⟨((revF34603bcp[i.1]!)[j.1]!) % 8, Nat.mod_lt _ (by decide)⟩

theorem revF34603b_cloneProj :
    (∀ x y, (revF34603bClone 0).op x y = x) ∧ (∀ x y, (revF34603bClone 1).op x y = y) := by
  native_decide

theorem revF34603b_cloneComp :
  ∀ i j x y, (revF34603bClone (revF34603bComp i j)).op x y =
    revF34603b.op ((revF34603bClone i).op x y) ((revF34603bClone j).op x y) := by
  native_decide

theorem revF34603b_isCloneFamily :
    revF34603b.IsCloneFamily revF34603bClone 0 1 revF34603bComp :=
  ⟨revF34603b_cloneProj.1, revF34603b_cloneProj.2, revF34603b_cloneComp⟩

/-- The `1` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def revF34603bsb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0], #[1, 1, 1, 1], #[2, 2, 2, 2], #[3, 3, 3, 3]], #[#[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3], #[0, 1, 2, 3]], #[#[2, 2, 2, 2], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3]], #[#[1, 1, 1, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[1, 1, 1, 3], #[1, 1, 1, 3], #[1, 1, 1, 3], #[1, 1, 1, 3]]]]

@[implicit_reducible]
def revF34603bSub (k : Fin 1) (j : Fin 6) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨((((revF34603bsb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def revF34603bpr : Array (Array Nat) :=
  #[#[0], #[1]]

def revF34603bP (t : Fin 2) (k : Fin 1) : Fin 6 :=
  ⟨((revF34603bpr[t.1]!)[k.1]!) % 6, Nat.mod_lt _ (by decide)⟩

def revF34603bsc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0, 0], #[1, 1, 1, 1, 1, 1], #[2, 2, 2, 2, 2, 2], #[3, 3, 3, 3, 3, 3], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5]], #[#[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5], #[0, 1, 2, 3, 4, 5]], #[#[2, 2, 2, 2, 2, 2], #[3, 3, 3, 3, 3, 3], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5]], #[#[2, 3, 4, 5, 4, 5], #[2, 3, 4, 5, 4, 5], #[2, 3, 4, 5, 4, 5], #[2, 3, 4, 5, 4, 5], #[2, 3, 4, 5, 4, 5], #[2, 3, 4, 5, 4, 5]], #[#[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5], #[4, 4, 4, 4, 4, 4], #[5, 5, 5, 5, 5, 5]], #[#[4, 5, 4, 5, 4, 5], #[4, 5, 4, 5, 4, 5], #[4, 5, 4, 5, 4, 5], #[4, 5, 4, 5, 4, 5], #[4, 5, 4, 5, 4, 5], #[4, 5, 4, 5, 4, 5]]]]

def revF34603bSc (k : Fin 1) (i j l : Fin 6) : Fin 6 :=
  ⟨((((revF34603bsc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 6, Nat.mod_lt _ (by decide)⟩

theorem revF34603b_subFacts :
    (∀ k x y, (revF34603bSub k (revF34603bP 0 k)).op x y = x) ∧
      (∀ k x y, (revF34603bSub k (revF34603bP 1 k)).op x y = y) ∧
      ∀ k j, ¬ ∀ x y, (revF34603bSub k j).op x y = revF34603b.op x y := by
  native_decide

theorem revF34603b_subComp :
  ∀ k i j l x y, (revF34603bSub k (revF34603bSc k i j l)).op x y =
    (revF34603bSub k i).op ((revF34603bSub k j).op x y) ((revF34603bSub k l).op x y) := by
  native_decide

theorem revF34603b_isSubclone (k : Fin 1) : IsSubclone (revF34603bSub k) :=
  IsSubclone.of_table (revF34603bP 0 k) (revF34603bP 1 k) (revF34603bSc k)
    (revF34603b_subFacts.1 k) (revF34603b_subFacts.2.1 k) (revF34603b_subComp k)

theorem revF34603b_notInSub (k : Fin 1) : ¬ InClone (revF34603bSub k) revF34603b.op :=
  notInClone_of (revF34603b_subFacts.2.2 k)

/-- The `2` clone members left over: those that do generate `◇`. -/
def revF34603bbd : Array (Array (Array Nat)) :=
  #[#[#[2, 2, 2, 1], #[1, 1, 1, 1], #[1, 1, 1, 1], #[3, 3, 3, 3]], #[#[2, 1, 1, 3], #[2, 1, 1, 3], #[2, 1, 1, 3], #[1, 1, 1, 3]]]

@[implicit_reducible]
def revF34603bBad (b : Fin 2) : Magma (Fin 4) :=
  ⟨fun x y ↦ ⟨(((revF34603bbd[b.1]!)[x.1]!)[y.1]!) % 4, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def revF34603bw : Array (Array Nat) :=
  #[#[0, 0, 0, 0, 0, 0, 0, 0], #[0, 1, 2, 0, 0, 3, 4, 5], #[0, 0, 0, 0, 1, 0, 0, 0]]

def revF34603bWk (i : Fin 8) : Fin 1 := ⟨((revF34603bw[0]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

def revF34603bWe (i : Fin 8) : Fin 6 := ⟨((revF34603bw[1]!)[i.1]!) % 6, Nat.mod_lt _ (by decide)⟩

def revF34603bWb (i : Fin 8) : Fin 2 := ⟨((revF34603bw[2]!)[i.1]!) % 2, Nat.mod_lt _ (by decide)⟩

theorem revF34603b_splitFacts : ∀ i : Fin 8,
    (∀ x y, (revF34603bSub (revF34603bWk i) (revF34603bWe i)).op x y = (revF34603bClone i).op x y) ∨
      (∀ x y, (revF34603bClone i).op x y = (revF34603bBad (revF34603bWb i)).op x y) := by
  native_decide

theorem revF34603b_split (i : Fin 8) :
    (∃ k, InClone (revF34603bSub k) (revF34603bClone i).op) ∨
      ∃ b, (revF34603bClone i).op = (revF34603bBad b).op :=
  split_of_witnesses revF34603bWk revF34603bWe revF34603bWb revF34603b_splitFacts i

end Magma

theorem revF34603b_sat : @Equation4603 (Fin 4) Magma.revF34603b := by native_decide
