import equational_theories.Definability.RevF33901c_data

/-!
# Targets `3264`-`4076` against equation `3901`

Each target is refuted by every member of `Magma.revF33901cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33901c_kill3264 : ∀ b : Fin 2, ¬ @Equation3264 (Fin 4) (Magma.revF33901cBad b) := by native_decide

theorem Equation3264_not_termStructuralFromFin_Equation3901 :
    ¬ Law3264.TermStructuralFromFin Law3901 :=
  not_termStructuralFromFin_of_subclones Magma.revF33901c
    ((@Law3901.models_iff (Fin 4) Magma.revF33901c).mpr revF33901c_sat)
    Magma.revF33901c_isCloneFamily Magma.revF33901c_isSubclone Magma.revF33901c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33901cSub k) u)
      Magma.revF33901c_split fun b h ↦ revF33901c_kill3264 b
        ((@Law3264.models_iff (Fin 4) (Magma.revF33901cBad b)).mp h))

theorem revF33901c_kill4076 : ∀ b : Fin 2, ¬ @Equation4076 (Fin 4) (Magma.revF33901cBad b) := by native_decide

theorem Equation4076_not_termStructuralFromFin_Equation3901 :
    ¬ Law4076.TermStructuralFromFin Law3901 :=
  not_termStructuralFromFin_of_subclones Magma.revF33901c
    ((@Law3901.models_iff (Fin 4) Magma.revF33901c).mpr revF33901c_sat)
    Magma.revF33901c_isCloneFamily Magma.revF33901c_isSubclone Magma.revF33901c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33901cSub k) u)
      Magma.revF33901c_split fun b h ↦ revF33901c_kill4076 b
        ((@Law4076.models_iff (Fin 4) (Magma.revF33901cBad b)).mp h))
