import equational_theories.Definability.RevF34078c_data

/-!
# Targets `3256`-`4090` against equation `4078`

Each target is refuted by every member of `Magma.revF34078cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34078c_kill3256 : ∀ b : Fin 2, ¬ @Equation3256 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3256_not_termStructuralFromFin_Equation4078 :
    ¬ Law3256.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3256 b
        ((@Law3256.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3456 : ∀ b : Fin 2, ¬ @Equation3456 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3456_not_termStructuralFromFin_Equation4078 :
    ¬ Law3456.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3456 b
        ((@Law3456.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3457 : ∀ b : Fin 2, ¬ @Equation3457 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3457_not_termStructuralFromFin_Equation4078 :
    ¬ Law3457.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3457 b
        ((@Law3457.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3459 : ∀ b : Fin 2, ¬ @Equation3459 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3459_not_termStructuralFromFin_Equation4078 :
    ¬ Law3459.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3459 b
        ((@Law3459.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3862 : ∀ b : Fin 2, ¬ @Equation3862 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3862_not_termStructuralFromFin_Equation4078 :
    ¬ Law3862.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3862 b
        ((@Law3862.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3877 : ∀ b : Fin 2, ¬ @Equation3877 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3877_not_termStructuralFromFin_Equation4078 :
    ¬ Law3877.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3877 b
        ((@Law3877.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill3887 : ∀ b : Fin 2, ¬ @Equation3887 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation3887_not_termStructuralFromFin_Equation4078 :
    ¬ Law3887.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill3887 b
        ((@Law3887.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))

theorem revF34078c_kill4090 : ∀ b : Fin 2, ¬ @Equation4090 (Fin 5) (Magma.revF34078cBad b) := by native_decide

theorem Equation4090_not_termStructuralFromFin_Equation4078 :
    ¬ Law4090.TermStructuralFromFin Law4078 :=
  not_termStructuralFromFin_of_subclones Magma.revF34078c
    ((@Law4078.models_iff (Fin 5) Magma.revF34078c).mpr revF34078c_sat)
    Magma.revF34078c_isCloneFamily Magma.revF34078c_isSubclone Magma.revF34078c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34078cSub k) u)
      Magma.revF34078c_split fun b h ↦ revF34078c_kill4090 b
        ((@Law4090.models_iff (Fin 5) (Magma.revF34078cBad b)).mp h))
