import equational_theories.Definability.RevF34129d_data

/-!
# Targets `4314`-`4606` against equation `4129`

Each target is refuted by every member of `Magma.revF34129dBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34129d_kill4314 : ∀ b : Fin 2, ¬ @Equation4314 (Fin 4) (Magma.revF34129dBad b) := by native_decide

theorem Equation4314_not_termStructuralFromFin_Equation4129 :
    ¬ Law4314.TermStructuralFromFin Law4129 :=
  not_termStructuralFromFin_of_subclones Magma.revF34129d
    ((@Law4129.models_iff (Fin 4) Magma.revF34129d).mpr revF34129d_sat)
    Magma.revF34129d_isCloneFamily Magma.revF34129d_isSubclone Magma.revF34129d_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34129dSub k) u)
      Magma.revF34129d_split fun b h ↦ revF34129d_kill4314 b
        ((@Law4314.models_iff (Fin 4) (Magma.revF34129dBad b)).mp h))

theorem revF34129d_kill4606 : ∀ b : Fin 2, ¬ @Equation4606 (Fin 4) (Magma.revF34129dBad b) := by native_decide

theorem Equation4606_not_termStructuralFromFin_Equation4129 :
    ¬ Law4606.TermStructuralFromFin Law4129 :=
  not_termStructuralFromFin_of_subclones Magma.revF34129d
    ((@Law4129.models_iff (Fin 4) Magma.revF34129d).mpr revF34129d_sat)
    Magma.revF34129d_isCloneFamily Magma.revF34129d_isSubclone Magma.revF34129d_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34129dSub k) u)
      Magma.revF34129d_split fun b h ↦ revF34129d_kill4606 b
        ((@Law4606.models_iff (Fin 4) (Magma.revF34129dBad b)).mp h))
