import equational_theories.Definability.RevF3834c_data

/-!
# Targets `3461`-`3864` against equation `834`

Each target is refuted by every member of `Magma.revF3834cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF3834c_kill3461 : ∀ b : Fin 2, ¬ @Equation3461 (Fin 4) (Magma.revF3834cBad b) := by native_decide

theorem Equation3461_not_termStructuralFromFin_Equation834 :
    ¬ Law3461.TermStructuralFromFin Law834 :=
  not_termStructuralFromFin_of_subclones Magma.revF3834c
    ((@Law834.models_iff (Fin 4) Magma.revF3834c).mpr revF3834c_sat)
    Magma.revF3834c_isCloneFamily Magma.revF3834c_isSubclone Magma.revF3834c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3834cSub k) u)
      Magma.revF3834c_split fun b h ↦ revF3834c_kill3461 b
        ((@Law3461.models_iff (Fin 4) (Magma.revF3834cBad b)).mp h))

theorem revF3834c_kill3864 : ∀ b : Fin 2, ¬ @Equation3864 (Fin 4) (Magma.revF3834cBad b) := by native_decide

theorem Equation3864_not_termStructuralFromFin_Equation834 :
    ¬ Law3864.TermStructuralFromFin Law834 :=
  not_termStructuralFromFin_of_subclones Magma.revF3834c
    ((@Law834.models_iff (Fin 4) Magma.revF3834c).mpr revF3834c_sat)
    Magma.revF3834c_isCloneFamily Magma.revF3834c_isSubclone Magma.revF3834c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF3834cSub k) u)
      Magma.revF3834c_split fun b h ↦ revF3834c_kill3864 b
        ((@Law3864.models_iff (Fin 4) (Magma.revF3834cBad b)).mp h))
