import equational_theories.Definability.RevF34133a_data

/-!
# Targets `3511`-`3955` against equation `4133`

Each target is refuted by every member of `Magma.revF34133aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34133a_kill3511 : ∀ b : Fin 2, ¬ @Equation3511 (Fin 4) (Magma.revF34133aBad b) := by native_decide

theorem Equation3511_not_termStructuralFromFin_Equation4133 :
    ¬ Law3511.TermStructuralFromFin Law4133 :=
  not_termStructuralFromFin_of_subclones Magma.revF34133a
    ((@Law4133.models_iff (Fin 4) Magma.revF34133a).mpr revF34133a_sat)
    Magma.revF34133a_isCloneFamily Magma.revF34133a_isSubclone Magma.revF34133a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34133aSub k) u)
      Magma.revF34133a_split fun b h ↦ revF34133a_kill3511 b
        ((@Law3511.models_iff (Fin 4) (Magma.revF34133aBad b)).mp h))

theorem revF34133a_kill3512 : ∀ b : Fin 2, ¬ @Equation3512 (Fin 4) (Magma.revF34133aBad b) := by native_decide

theorem Equation3512_not_termStructuralFromFin_Equation4133 :
    ¬ Law3512.TermStructuralFromFin Law4133 :=
  not_termStructuralFromFin_of_subclones Magma.revF34133a
    ((@Law4133.models_iff (Fin 4) Magma.revF34133a).mpr revF34133a_sat)
    Magma.revF34133a_isCloneFamily Magma.revF34133a_isSubclone Magma.revF34133a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34133aSub k) u)
      Magma.revF34133a_split fun b h ↦ revF34133a_kill3512 b
        ((@Law3512.models_iff (Fin 4) (Magma.revF34133aBad b)).mp h))

theorem revF34133a_kill3918 : ∀ b : Fin 2, ¬ @Equation3918 (Fin 4) (Magma.revF34133aBad b) := by native_decide

theorem Equation3918_not_termStructuralFromFin_Equation4133 :
    ¬ Law3918.TermStructuralFromFin Law4133 :=
  not_termStructuralFromFin_of_subclones Magma.revF34133a
    ((@Law4133.models_iff (Fin 4) Magma.revF34133a).mpr revF34133a_sat)
    Magma.revF34133a_isCloneFamily Magma.revF34133a_isSubclone Magma.revF34133a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34133aSub k) u)
      Magma.revF34133a_split fun b h ↦ revF34133a_kill3918 b
        ((@Law3918.models_iff (Fin 4) (Magma.revF34133aBad b)).mp h))

theorem revF34133a_kill3955 : ∀ b : Fin 2, ¬ @Equation3955 (Fin 4) (Magma.revF34133aBad b) := by native_decide

theorem Equation3955_not_termStructuralFromFin_Equation4133 :
    ¬ Law3955.TermStructuralFromFin Law4133 :=
  not_termStructuralFromFin_of_subclones Magma.revF34133a
    ((@Law4133.models_iff (Fin 4) Magma.revF34133a).mpr revF34133a_sat)
    Magma.revF34133a_isCloneFamily Magma.revF34133a_isSubclone Magma.revF34133a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34133aSub k) u)
      Magma.revF34133a_split fun b h ↦ revF34133a_kill3955 b
        ((@Law3955.models_iff (Fin 4) (Magma.revF34133aBad b)).mp h))
