import equational_theories.Definability.RevF34165b_data

/-!
# Targets `3456`-`3862` against equation `4165`

Each target is refuted by every member of `Magma.revF34165bBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF34165b_kill3456 : ∀ b : Fin 4, ¬ @Equation3456 (Fin 3) (Magma.revF34165bBad b) := by native_decide

theorem Equation3456_not_termStructuralFromFin_Equation4165 :
    ¬ Law3456.TermStructuralFromFin Law4165 :=
  not_termStructuralFromFin_of_subclones Magma.revF34165b
    ((@Law4165.models_iff (Fin 3) Magma.revF34165b).mpr revF34165b_sat)
    Magma.revF34165b_isCloneFamily Magma.revF34165b_isSubclone Magma.revF34165b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34165bSub k) u)
      Magma.revF34165b_split fun b h ↦ revF34165b_kill3456 b
        ((@Law3456.models_iff (Fin 3) (Magma.revF34165bBad b)).mp h))

theorem revF34165b_kill3862 : ∀ b : Fin 4, ¬ @Equation3862 (Fin 3) (Magma.revF34165bBad b) := by native_decide

theorem Equation3862_not_termStructuralFromFin_Equation4165 :
    ¬ Law3862.TermStructuralFromFin Law4165 :=
  not_termStructuralFromFin_of_subclones Magma.revF34165b
    ((@Law4165.models_iff (Fin 3) Magma.revF34165b).mpr revF34165b_sat)
    Magma.revF34165b_isCloneFamily Magma.revF34165b_isSubclone Magma.revF34165b_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF34165bSub k) u)
      Magma.revF34165b_split fun b h ↦ revF34165b_kill3862 b
        ((@Law3862.models_iff (Fin 3) (Magma.revF34165bBad b)).mp h))
