import equational_theories.Definability.RevF33541a_data

/-!
# Targets `307`-`359` against equation `3541`

Each target is refuted by every member of `Magma.revF33541aBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33541a_kill307 : ∀ b : Fin 4, ¬ @Equation307 (Fin 3) (Magma.revF33541aBad b) := by native_decide

theorem Equation307_not_termStructuralFromFin_Equation3541 :
    ¬ Law307.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541a
    ((@Law3541.models_iff (Fin 3) Magma.revF33541a).mpr revF33541a_sat)
    Magma.revF33541a_isCloneFamily Magma.revF33541a_isSubclone Magma.revF33541a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541aSub k) u)
      Magma.revF33541a_split fun b h ↦ revF33541a_kill307 b
        ((@Law307.models_iff (Fin 3) (Magma.revF33541aBad b)).mp h))

theorem revF33541a_kill359 : ∀ b : Fin 4, ¬ @Equation359 (Fin 3) (Magma.revF33541aBad b) := by native_decide

theorem Equation359_not_termStructuralFromFin_Equation3541 :
    ¬ Law359.TermStructuralFromFin Law3541 :=
  not_termStructuralFromFin_of_subclones Magma.revF33541a
    ((@Law3541.models_iff (Fin 3) Magma.revF33541a).mpr revF33541a_sat)
    Magma.revF33541a_isCloneFamily Magma.revF33541a_isSubclone Magma.revF33541a_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33541aSub k) u)
      Magma.revF33541a_split fun b h ↦ revF33541a_kill359 b
        ((@Law359.models_iff (Fin 3) (Magma.revF33541aBad b)).mp h))
