import equational_theories.Definability.RevF33583c_data

/-!
# Targets `4314`-`4606` against equation `3583`

Each target is refuted by every member of `Magma.revF33583cBad`, so the only clone members
realising it are trapped in a subclone that misses `◇`.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

theorem revF33583c_kill4314 : ∀ b : Fin 4, ¬ @Equation4314 (Fin 5) (Magma.revF33583cBad b) := by native_decide

theorem Equation4314_not_termStructuralFromFin_Equation3583 :
    ¬ Law4314.TermStructuralFromFin Law3583 :=
  not_termStructuralFromFin_of_subclones Magma.revF33583c
    ((@Law3583.models_iff (Fin 5) Magma.revF33583c).mpr revF33583c_sat)
    Magma.revF33583c_isCloneFamily Magma.revF33583c_isSubclone Magma.revF33583c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33583cSub k) u)
      Magma.revF33583c_split fun b h ↦ revF33583c_kill4314 b
        ((@Law4314.models_iff (Fin 5) (Magma.revF33583cBad b)).mp h))

theorem revF33583c_kill4606 : ∀ b : Fin 4, ¬ @Equation4606 (Fin 5) (Magma.revF33583cBad b) := by native_decide

theorem Equation4606_not_termStructuralFromFin_Equation3583 :
    ¬ Law4606.TermStructuralFromFin Law3583 :=
  not_termStructuralFromFin_of_subclones Magma.revF33583c
    ((@Law3583.models_iff (Fin 5) Magma.revF33583c).mpr revF33583c_sat)
    Magma.revF33583c_isCloneFamily Magma.revF33583c_isSubclone Magma.revF33583c_notInSub
    (cover_of_split (P := fun u ↦ ∃ k, Magma.InClone (Magma.revF33583cSub k) u)
      Magma.revF33583c_split fun b h ↦ revF33583c_kill4606 b
        ((@Law4606.models_iff (Fin 5) (Magma.revF33583cBad b)).mp h))
