import equational_theories.Definability.Subclone
import equational_theories.Equations.All
import equational_theories.DecideBang

/-!
# A model of equation 4336 that its own realisations cannot rebuild

`Magma.revF34336a` is a model of equation `4336` on `Fin 3`, and its binary clone has
`9` members. Every target settled in the companion files *is* realised in that clone,
so no clone certificate refutes term-definability. What fails is the other half of
term-structurality: the members realising those targets generate only a proper subclone,
and `Magma.revF34336aSub` lists the `3` subclones that contain all of them. `◇` is in none
of the subclones, so none of those members can define `◇` back.

`Magma.revF34336aBad` holds the `1` clone members the subclones miss -- exactly the ones
that do generate `◇`. A target refuted by all of them is therefore not term-structural
from `4336`, over finite magmas and hence over all of them.

This file is generated by `revemit.py`.
-/

set_option maxHeartbeats 1000000

open Law Law.MagmaLaw

namespace Magma

/-- A model of equation `4336` on `Fin 3` whose binary clone has `9` members. -/
def revF34336at : Array (Array Nat) :=
  #[#[1, 2, 2], #[2, 0, 2], #[2, 2, 2]]

@[implicit_reducible]
def revF34336a : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((revF34336at[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The `9` operations term-definable from `Magma.revF34336a`. -/
def revF34336acl : Array (Array (Array Nat)) :=
  #[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[1, 1, 1], #[0, 0, 0], #[2, 2, 2]], #[#[1, 2, 2], #[2, 0, 2], #[2, 2, 2]], #[#[1, 0, 2], #[1, 0, 2], #[1, 0, 2]], #[#[2, 2, 2], #[2, 2, 2], #[2, 2, 2]], #[#[2, 0, 2], #[1, 2, 2], #[2, 2, 2]], #[#[0, 2, 2], #[2, 1, 2], #[2, 2, 2]], #[#[2, 1, 2], #[0, 2, 2], #[2, 2, 2]]]

@[implicit_reducible]
def revF34336aClone (i : Fin 9) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((revF34336acl[i.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- Where each composite of two members of `Magma.revF34336aClone` lands. -/
def revF34336acp : Array (Array Nat) :=
  #[#[2, 3, 5, 5, 8, 5, 8, 3, 5], #[3, 4, 6, 5, 5, 5, 5, 3, 6], #[5, 6, 0, 7, 7, 5, 5, 5, 6], #[5, 5, 7, 7, 7, 5, 5, 5, 5], #[8, 5, 7, 7, 1, 5, 8, 5, 5], #[5, 5, 5, 5, 5, 5, 5, 5, 5], #[8, 5, 5, 5, 8, 5, 8, 5, 5], #[3, 3, 5, 5, 5, 5, 5, 3, 5], #[5, 6, 6, 5, 5, 5, 5, 5, 6]]

def revF34336aComp (i j : Fin 9) : Fin 9 :=
  ⟨((revF34336acp[i.1]!)[j.1]!) % 9, Nat.mod_lt _ (by decide)⟩

theorem revF34336a_cloneProj :
    (∀ x y, (revF34336aClone 0).op x y = x) ∧ (∀ x y, (revF34336aClone 1).op x y = y) := by
  native_decide

theorem revF34336a_cloneComp :
  ∀ i j x y, (revF34336aClone (revF34336aComp i j)).op x y =
    revF34336a.op ((revF34336aClone i).op x y) ((revF34336aClone j).op x y) := by
  native_decide

theorem revF34336a_isCloneFamily :
    revF34336a.IsCloneFamily revF34336aClone 0 1 revF34336aComp :=
  ⟨revF34336a_cloneProj.1, revF34336a_cloneProj.2, revF34336a_cloneComp⟩

/-- The `3` proper subclones that trap every clone member failing to generate `◇`. A
short list is padded by repeating its first entry, which membership and closure do not
see. -/
def revF34336asb : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[2, 2, 2], #[2, 2, 2], #[2, 2, 2]], #[#[2, 1, 2], #[0, 2, 2], #[2, 2, 2]], #[#[2, 0, 2], #[1, 2, 2], #[2, 2, 2]]], #[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[1, 1, 1], #[0, 0, 0], #[2, 2, 2]], #[#[1, 0, 2], #[1, 0, 2], #[1, 0, 2]], #[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]]], #[#[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 1, 2], #[0, 1, 2], #[0, 1, 2]], #[#[0, 2, 2], #[2, 1, 2], #[2, 2, 2]], #[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]], #[#[0, 0, 0], #[1, 1, 1], #[2, 2, 2]]]]

@[implicit_reducible]
def revF34336aSub (k : Fin 3) (j : Fin 5) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨((((revF34336asb[k.1]!)[j.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- The projections of each subclone, and where each superposition inside it lands. -/
def revF34336apr : Array (Array Nat) :=
  #[#[0, 0, 0], #[1, 1, 1]]

def revF34336aP (t : Fin 2) (k : Fin 3) : Fin 5 :=
  ⟨((revF34336apr[t.1]!)[k.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def revF34336asc : Array (Array (Array (Array Nat))) :=
  #[#[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[4, 4, 4, 4, 4]], #[#[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4], #[0, 1, 2, 3, 4]], #[#[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2], #[2, 2, 2, 2, 2]], #[#[2, 3, 2, 3, 2], #[4, 2, 2, 2, 4], #[2, 2, 2, 2, 2], #[4, 2, 2, 2, 4], #[2, 3, 2, 3, 2]], #[#[2, 4, 2, 4, 2], #[3, 2, 2, 2, 3], #[2, 2, 2, 2, 2], #[3, 2, 2, 2, 3], #[2, 4, 2, 4, 2]]], #[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[0, 0, 0, 0, 0]], #[#[0, 1, 2, 3, 0], #[0, 1, 2, 3, 0], #[0, 1, 2, 3, 0], #[0, 1, 2, 3, 0], #[0, 1, 2, 3, 0]], #[#[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2]], #[#[2, 3, 0, 1, 2], #[2, 3, 0, 1, 2], #[2, 3, 0, 1, 2], #[2, 3, 0, 1, 2], #[2, 3, 0, 1, 2]], #[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[3, 3, 3, 3, 3], #[0, 0, 0, 0, 0]]], #[#[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[0, 0, 0, 0, 0], #[0, 0, 0, 0, 0]], #[#[0, 1, 2, 0, 0], #[0, 1, 2, 0, 0], #[0, 1, 2, 0, 0], #[0, 1, 2, 0, 0], #[0, 1, 2, 0, 0]], #[#[0, 2, 2, 0, 0], #[2, 1, 2, 2, 2], #[2, 2, 2, 2, 2], #[0, 2, 2, 0, 0], #[0, 2, 2, 0, 0]], #[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[0, 0, 0, 0, 0], #[0, 0, 0, 0, 0]], #[#[0, 0, 0, 0, 0], #[1, 1, 1, 1, 1], #[2, 2, 2, 2, 2], #[0, 0, 0, 0, 0], #[0, 0, 0, 0, 0]]]]

def revF34336aSc (k : Fin 3) (i j l : Fin 5) : Fin 5 :=
  ⟨((((revF34336asc[k.1]!)[i.1]!)[j.1]!)[l.1]!) % 5, Nat.mod_lt _ (by decide)⟩

theorem revF34336a_subFacts :
    (∀ k x y, (revF34336aSub k (revF34336aP 0 k)).op x y = x) ∧
      (∀ k x y, (revF34336aSub k (revF34336aP 1 k)).op x y = y) ∧
      ∀ k j, ¬ ∀ x y, (revF34336aSub k j).op x y = revF34336a.op x y := by
  native_decide

theorem revF34336a_subComp :
  ∀ k i j l x y, (revF34336aSub k (revF34336aSc k i j l)).op x y =
    (revF34336aSub k i).op ((revF34336aSub k j).op x y) ((revF34336aSub k l).op x y) := by
  native_decide

theorem revF34336a_isSubclone (k : Fin 3) : IsSubclone (revF34336aSub k) :=
  IsSubclone.of_table (revF34336aP 0 k) (revF34336aP 1 k) (revF34336aSc k)
    (revF34336a_subFacts.1 k) (revF34336a_subFacts.2.1 k) (revF34336a_subComp k)

theorem revF34336a_notInSub (k : Fin 3) : ¬ InClone (revF34336aSub k) revF34336a.op :=
  notInClone_of (revF34336a_subFacts.2.2 k)

/-- The `1` clone members left over: those that do generate `◇`. -/
def revF34336abd : Array (Array (Array Nat)) :=
  #[#[#[1, 2, 2], #[2, 0, 2], #[2, 2, 2]]]

@[implicit_reducible]
def revF34336aBad (b : Fin 1) : Magma (Fin 3) :=
  ⟨fun x y ↦ ⟨(((revF34336abd[b.1]!)[x.1]!)[y.1]!) % 3, Nat.mod_lt _ (by decide)⟩⟩

/-- For each clone member, the subclone member it equals, or else the leftover it is. -/
def revF34336aw : Array (Array Nat) :=
  #[#[0, 0, 1, 0, 1, 0, 0, 2, 0], #[0, 1, 2, 0, 3, 2, 4, 2, 3], #[0, 0, 0, 0, 0, 0, 0, 0, 0]]

def revF34336aWk (i : Fin 9) : Fin 3 := ⟨((revF34336aw[0]!)[i.1]!) % 3, Nat.mod_lt _ (by decide)⟩

def revF34336aWe (i : Fin 9) : Fin 5 := ⟨((revF34336aw[1]!)[i.1]!) % 5, Nat.mod_lt _ (by decide)⟩

def revF34336aWb (i : Fin 9) : Fin 1 := ⟨((revF34336aw[2]!)[i.1]!) % 1, Nat.mod_lt _ (by decide)⟩

theorem revF34336a_splitFacts : ∀ i : Fin 9,
    (∀ x y, (revF34336aSub (revF34336aWk i) (revF34336aWe i)).op x y = (revF34336aClone i).op x y) ∨
      (∀ x y, (revF34336aClone i).op x y = (revF34336aBad (revF34336aWb i)).op x y) := by
  native_decide

theorem revF34336a_split (i : Fin 9) :
    (∃ k, InClone (revF34336aSub k) (revF34336aClone i).op) ∨
      ∃ b, (revF34336aClone i).op = (revF34336aBad b).op :=
  split_of_witnesses revF34336aWk revF34336aWe revF34336aWb revF34336a_splitFacts i

end Magma

theorem revF34336a_sat : @Equation4336 (Fin 3) Magma.revF34336a := by native_decide
