import equational_theories.Definability.DiagRow

/-!
# `Equation2917` is a quasigroup on one side, over every carrier

Generated by `defwork/rowqg.py`.  `Equation2917` is `x = ((y ◇ (x ◇ y)) ◇ z) ◇ z`.

The law divides -- the division term is read off the law's own syntax tree -- and the row (or
column) through the diagonal is injective; together those say the row is a permutation, which is
what `AutBox`'s finite device was really using.  So `DiagRow.structuralFrom_idem_row` promotes the
`Equation3` cell from `StructuralFromFin` to `StructuralFrom`.
-/

open FirstOrder FirstOrder.Language Law Law.MagmaLaw FreeMagma

set_option maxHeartbeats 1000000
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unusedTactic false
set_option linter.unreachableTactic false

/-- `Equation2917`: `x = ((y ◇ (x ◇ y)) ◇ z) ◇ z`.  Columns are permutations -- the law itself divides, and the
diagonal is injective by a Vampire refutation replayed one superposition step at a time. -/
theorem ColQG_Equation2917 : DiagRow.ColQG Law2917 := by
  classical
  refine DiagRow.colQG_of (fun {G} M hM ↦ ?_)
  have hm := (@Law2917.models_iff G M).mp hM
  refine ⟨fun x y hxy ↦ ?_, fun u z ↦ ⟨(M.op (M.op u (M.op z u)) u), (hm z u u).symm⟩⟩
  by_contra nh
  have eq4 : ∀ X0 X1 X2 : G, (M.op (M.op (M.op X1 (M.op X0 X1)) X2) X2) = X0 := by
    intro X0 X1 X2
    grind
  have eq5 : (M.op y x) = (M.op x x) := by grind
  have eq6 : y ≠ x := by grind
  clear hm hxy nh hM
  have eq7 : ∀ X0 : G, y = (M.op (M.op (M.op x (M.op x x)) X0) X0) := by
    intro X0
    first
    | (have i₁ := eq4 y x X0
       have i₂ := eq5
       grind)
    | exact superpose eq5 eq4
    | exact resolve eq4 eq5
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  have eq10 : y = x := by
    first
    | (have i₁ := eq7 x
       have i₂ := eq4 x x x
       grind)
    | exact superpose eq4 eq7
    | exact resolve eq7 eq4
    | grind
    | grind (splits := 40)
    | grind (splits := 40) (ematch := 20)
  clear eq7
  have eq11 : False := by grind
  exact eq11

/-- The `Equation3` companion: `x □ y = if x = y then x ◇ x else x ◇ y` is idempotent, agrees with
`◇` off the diagonal, and by `ColQG_Equation2917` its diagonal is recoverable from the rest of
its column -- so the two magmas define each other. -/
theorem Equation3_StructuralFrom_Equation2917 : Law3.StructuralFrom Law2917 :=
  DiagRow.structuralFrom_idem_col ColQG_Equation2917
