import equational_theories.Definability.ExactPrune

/-!
# A searched exact-automorphism class on `Fin 9`: data

The group is `21` permutations of `Fin 9`, the excess permutations that pin it from above are `5`,
and the invariant family it acts on has `314,928` members. How many of those have this group as
their automorphism group *exactly* is not computed and does not need to be: the family is indexed by
the subtype `Magma.tup9R700` of transport tuples passing `Magma.tupOK`, and both sides of the
rectangle are decided by search rather than by enumeration. See `Definability/ExactPrune.lean` for
the device and `Definability/Srch_S9R700.lean` for the data lemmas.

This file is generated by `genrect.py`; it holds only tables, so that `native_decide` -- which
recompiles its whole enclosing module on each invocation -- never has to compile them twice.
-/

-- an array literal elaborates one recursive step per entry, and the group is one of the arrays, so
-- the depth has to grow with it: `10000` was fine up to a few hundred permutations and is not fine
-- at `1152`.  The heartbeat bump is for `tupOK` on the source exhibits below, which the kernel
-- checks: it is `|H|` endomorphism tests of `n^2` cells each.
set_option maxRecDepth 10000
set_option maxHeartbeats 1000000

namespace S9R700

/-- The `21` elements of the group, and their inverses. -/
def Ed : Array (Array Nat) := #[#[0, 1, 2, 3, 4, 5, 6, 7, 8], #[0, 6, 2, 3, 5, 7, 8, 4, 1], #[0, 8, 2, 3, 7, 4, 1, 5, 6], #[1, 4, 2, 3, 0, 5, 7, 8, 6], #[1, 6, 2, 3, 8, 0, 4, 5, 7], #[1, 7, 2, 3, 5, 8, 6, 0, 4], #[4, 0, 2, 3, 1, 5, 8, 6, 7], #[4, 7, 2, 3, 6, 1, 0, 5, 8], #[4, 8, 2, 3, 5, 6, 7, 1, 0], #[5, 0, 2, 3, 6, 7, 1, 8, 4], #[5, 1, 2, 3, 7, 8, 4, 6, 0], #[5, 4, 2, 3, 8, 6, 0, 7, 1], #[6, 4, 2, 3, 7, 1, 8, 0, 5], #[6, 5, 2, 3, 0, 7, 4, 1, 8], #[6, 8, 2, 3, 1, 0, 5, 7, 4], #[7, 0, 2, 3, 8, 4, 6, 1, 5], #[7, 5, 2, 3, 1, 8, 0, 4, 6], #[7, 6, 2, 3, 4, 1, 5, 8, 0], #[8, 1, 2, 3, 6, 0, 7, 4, 5], #[8, 5, 2, 3, 4, 6, 1, 0, 7], #[8, 7, 2, 3, 0, 4, 5, 6, 1]]

def Eid : Array (Array Nat) := #[#[0, 1, 2, 3, 4, 5, 6, 7, 8], #[0, 8, 2, 3, 7, 4, 1, 5, 6], #[0, 6, 2, 3, 5, 7, 8, 4, 1], #[4, 0, 2, 3, 1, 5, 8, 6, 7], #[5, 0, 2, 3, 6, 7, 1, 8, 4], #[7, 0, 2, 3, 8, 4, 6, 1, 5], #[1, 4, 2, 3, 0, 5, 7, 8, 6], #[6, 5, 2, 3, 0, 7, 4, 1, 8], #[8, 7, 2, 3, 0, 4, 5, 6, 1], #[1, 6, 2, 3, 8, 0, 4, 5, 7], #[8, 1, 2, 3, 6, 0, 7, 4, 5], #[6, 8, 2, 3, 1, 0, 5, 7, 4], #[7, 5, 2, 3, 1, 8, 0, 4, 6], #[4, 7, 2, 3, 6, 1, 0, 5, 8], #[5, 4, 2, 3, 8, 6, 0, 7, 1], #[1, 7, 2, 3, 5, 8, 6, 0, 4], #[6, 4, 2, 3, 7, 1, 8, 0, 5], #[8, 5, 2, 3, 4, 6, 1, 0, 7], #[5, 1, 2, 3, 7, 8, 4, 6, 0], #[7, 6, 2, 3, 4, 1, 5, 8, 0], #[4, 8, 2, 3, 5, 6, 7, 1, 0]]

def E (i : Fin 21) (x : Fin 9) : Fin 9 := ⟨(Ed[i.1]!)[x.1]! % 9, Nat.mod_lt _ (by decide)⟩

def Einv (i : Fin 21) (x : Fin 9) : Fin 9 := ⟨(Eid[i.1]!)[x.1]! % 9, Nat.mod_lt _ (by decide)⟩

/-- The `5` excess permutations: one element of each minimal overgroup of the group, so that a table
admitting none of them has the group as its automorphism group exactly. Chosen and checked in
`autsearch.py`. -/
def Xd : Array (Array Nat) := #[#[0, 4, 2, 3, 6, 8, 5, 1, 7], #[0, 1, 2, 3, 4, 6, 5, 8, 7], #[0, 1, 2, 3, 5, 4, 8, 7, 6], #[0, 1, 3, 2, 4, 5, 6, 7, 8], #[0, 4, 3, 2, 6, 8, 5, 1, 7]]

def Xid : Array (Array Nat) := #[#[0, 7, 2, 3, 1, 6, 4, 8, 5], #[0, 1, 2, 3, 4, 6, 5, 8, 7], #[0, 1, 2, 3, 5, 4, 8, 7, 6], #[0, 1, 3, 2, 4, 5, 6, 7, 8], #[0, 7, 3, 2, 1, 6, 4, 8, 5]]

def X (j : Fin 5) (x : Fin 9) : Fin 9 := ⟨(Xd[j.1]!)[x.1]! % 9, Nat.mod_lt _ (by decide)⟩

def Xinv (j : Fin 5) (x : Fin 9) : Fin 9 := ⟨(Xid[j.1]!)[x.1]! % 9, Nat.mod_lt _ (by decide)⟩

/-- One ordered pair per orbit (11 of them), and for each pair the orbit it lies in together with
a permutation carrying that orbit's representative to it. -/
def repd : Array (Array Nat) := #[#[0, 0], #[0, 1], #[0, 2], #[0, 3], #[0, 4], #[2, 0], #[2, 2], #[2, 3], #[3, 0], #[3, 2], #[3, 3]]

def rep (i : Fin 11) : Fin 9 × Fin 9 :=
  (⟨(repd[i.1]!)[0]! % 9, Nat.mod_lt _ (by decide)⟩, ⟨(repd[i.1]!)[1]! % 9, Nat.mod_lt _ (by decide)⟩)

def trd : Array (Array (Array Nat)) := #[#[#[0, 0], #[1, 0], #[2, 0], #[3, 0], #[4, 0], #[4, 1], #[1, 1], #[4, 2], #[1, 2]], #[#[4, 3], #[0, 3], #[2, 3], #[3, 3], #[1, 3], #[4, 5], #[1, 4], #[1, 5], #[4, 4]], #[#[5, 0], #[5, 3], #[6, 0], #[7, 0], #[5, 6], #[5, 9], #[5, 12], #[5, 15], #[5, 18]], #[#[8, 0], #[8, 3], #[9, 0], #[10, 0], #[8, 6], #[8, 9], #[8, 12], #[8, 15], #[8, 18]], #[#[1, 6], #[4, 6], #[2, 6], #[3, 6], #[0, 6], #[4, 8], #[4, 7], #[1, 7], #[1, 8]], #[#[1, 9], #[1, 10], #[2, 9], #[3, 9], #[1, 11], #[0, 9], #[4, 9], #[4, 10], #[4, 11]], #[#[4, 13], #[4, 14], #[2, 12], #[3, 12], #[1, 12], #[1, 13], #[0, 12], #[4, 12], #[1, 14]], #[#[1, 15], #[4, 16], #[2, 15], #[3, 15], #[4, 17], #[1, 16], #[1, 17], #[0, 15], #[4, 15]], #[#[4, 20], #[1, 18], #[2, 18], #[3, 18], #[4, 19], #[1, 19], #[4, 18], #[1, 20], #[0, 18]]]

def tr (x y : Fin 9) : Fin 11 × Fin 21 :=
  (⟨((trd[x.1]!)[y.1]!)[0]! % 11, Nat.mod_lt _ (by decide)⟩, ⟨((trd[x.1]!)[y.1]!)[1]! % 21, Nat.mod_lt _ (by decide)⟩)

/-- For each orbit, the permutation `tr` records at its representative, and the one it records at
that representative's image under each `E j`. -/
def zd : Array Nat := #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

def z (i : Fin 11) : Fin 21 := ⟨zd[i.1]! % 21, Nat.mod_lt _ (by decide)⟩

def std : Array (Array Nat) := #[#[0, 0, 0, 3, 3, 3, 6, 6, 6, 9, 9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18], #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], #[0, 0, 0, 3, 3, 3, 6, 6, 6, 9, 9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18], #[0, 0, 0, 3, 3, 3, 6, 6, 6, 9, 9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18], #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], #[0, 0, 0, 3, 3, 3, 6, 6, 6, 9, 9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18], #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 3, 3, 3, 6, 6, 6, 9, 9, 9, 12, 12, 12, 15, 15, 15, 18, 18, 18], #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

def st (i : Fin 11) (j : Fin 21) : Fin 21 := ⟨(std[i.1]!)[j.1]! % 21, Nat.mod_lt _ (by decide)⟩

end S9R700

namespace Magma

/-- A member of the class, as the `11` orbit values it takes together with the proof that they name
one. `Magma.tupOK` is three tests: every orbit value is one the group's action allows, the operation
the tuple builds really is invariant, and no excess permutation is an automorphism of it. -/
@[reducible] def tup9R700 : Type := {w : Fin 11 → Fin 9 // Magma.tupOK S9R700.E S9R700.tr S9R700.z S9R700.st S9R700.X w = true}

/-- The class, as a family of magmas indexed by its own membership test. -/
@[implicit_reducible]
def srch9R700 (v : tup9R700) : Magma (Fin 9) :=
  Magma.mk (Magma.transport S9R700.E S9R700.tr v.1)

end Magma

/-! ### The source exhibits

`5` members of the class, chosen by greedy cover so that between them they model all `303` equations
that have a model in the class at all. Each check is `Magma.tupOK`: the tuple names a member of the
class. It is `decide!` rather than `decide` because the invariance test is `81` cells times the `21`
group elements, which the elaborator will not walk inside its heartbeat limit.
-/

def vdsrch9R7000 : Array Nat := #[2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2]

def vsrch9R7000 : Magma.tup9R700 :=
  ⟨fun i ↦ ⟨vdsrch9R7000[i.1]! % 9, Nat.mod_lt _ (by decide)⟩, by decide!⟩

def vdsrch9R7001 : Array Nat := #[2, 2, 0, 0, 3, 2, 2, 2, 3, 3, 3]

def vsrch9R7001 : Magma.tup9R700 :=
  ⟨fun i ↦ ⟨vdsrch9R7001[i.1]! % 9, Nat.mod_lt _ (by decide)⟩, by decide!⟩

def vdsrch9R7002 : Array Nat := #[2, 2, 2, 3, 3, 0, 2, 3, 0, 2, 3]

def vsrch9R7002 : Magma.tup9R700 :=
  ⟨fun i ↦ ⟨vdsrch9R7002[i.1]! % 9, Nat.mod_lt _ (by decide)⟩, by decide!⟩

def vdsrch9R7003 : Array Nat := #[2, 2, 2, 3, 3, 2, 2, 2, 3, 3, 3]

def vsrch9R7003 : Magma.tup9R700 :=
  ⟨fun i ↦ ⟨vdsrch9R7003[i.1]! % 9, Nat.mod_lt _ (by decide)⟩, by decide!⟩

def vdsrch9R7004 : Array Nat := #[2, 2, 2, 3, 3, 2, 2, 3, 3, 2, 3]

def vsrch9R7004 : Magma.tup9R700 :=
  ⟨fun i ↦ ⟨vdsrch9R7004[i.1]! % 9, Nat.mod_lt _ (by decide)⟩, by decide!⟩
