import equational_theories.Definability.UnaryFine463

/-!
# `StructuralFrom Law463` by the four-way split, batch 1

Generated by `defwork/emitfine463.py`. See `Definability/UnaryFine463.lean` for the device.
-/

open Law Law.MagmaLaw UnaryFine463

namespace Law.MagmaLaw

/-- `x = x ◇ (((x ◇ y) ◇ y) ◇ y)` -/
theorem Equation1232_StructuralFrom_Equation463 : Law1232.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law1232 := by
    rw [@Law1232.models_iff]
    intro x y
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

/-- `x = x ◇ (((x ◇ y) ◇ y) ◇ z)` -/
theorem Equation1233_StructuralFrom_Equation463 : Law1233.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law1233 := by
    rw [@Law1233.models_iff]
    intro x y z
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

/-- `x = x ◇ (((x ◇ y) ◇ z) ◇ y)` -/
theorem Equation1235_StructuralFrom_Equation463 : Law1235.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law1235 := by
    rw [@Law1235.models_iff]
    intro x y z
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

/-- `x = x ◇ (((x ◇ y) ◇ z) ◇ z)` -/
theorem Equation1236_StructuralFrom_Equation463 : Law1236.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law1236 := by
    rw [@Law1236.models_iff]
    intro x y z
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

/-- `x ◇ y = y ◇ ((y ◇ x) ◇ y)` -/
theorem Equation3556_StructuralFrom_Equation463 : Law3556.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s2 : @satisfies _ G (t2.magma M) Law3556 := by
    rw [@Law3556.models_iff]
    intro x y
    simp only [t2_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t2 (fun a b ↦ (hsop a b).trans (hid b)) s2
    · push Not at hid
      exact Unary.structuralOnMagma_img M t2 (Lf 1 ⋆ Lf 0) hsop
        (t2_mix M h hfx hid) s2
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t2 (Lf 0) (Lf 1 ⋆ Lf 0) hsop
        (t2_inv M h hfx hin) s2
    · push Not at hin
      exact Unary.structuralOnMagma_img M t2 (Lf 1 ⋆ Lf 0) hsop
        (t2_deep M h hfx hin) s2

/-- `x ◇ y = (x ◇ x) ◇ (y ◇ x)` -/
theorem Equation3714_StructuralFrom_Equation463 : Law3714.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law3714 := by
    rw [@Law3714.models_iff]
    intro x y
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

/-- `x ◇ y = (x ◇ y) ◇ (x ◇ z)` -/
theorem Equation3723_StructuralFrom_Equation463 : Law3723.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s1 : @satisfies _ G (t1.magma M) Law3723 := by
    rw [@Law3723.models_iff]
    intro x y z
    simp only [t1_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t1 (fun a b ↦ (hsop a b).trans (hid b)) s1
    · push Not at hid
      exact Unary.structuralOnMagma_img M t1 (Lf 0 ⋆ Lf 1) hsop
        (t1_mix M h hfx hid) s1
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t1 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t1_inv M h hfx hin) s1
    · push Not at hin
      exact Unary.structuralOnMagma_img M t1 (Lf 0 ⋆ Lf 1) hsop
        (t1_deep M h hfx hin) s1

/-- `x ◇ (y ◇ x) = (x ◇ x) ◇ y` -/
theorem Equation4433_StructuralFrom_Equation463 : Law4433.StructuralFrom Law463 := by
  intro G M hM
  classical
  have h : Equation463 G := Law463.models_iff.mp hM
  have hsop := Unary463.sop M h
  obtain ⟨s, hs, hss⟩ := Unary463.name_s M h
  have s0 : @satisfies _ G (t0.magma M) Law4433 := by
    rw [@Law4433.models_iff]
    intro x y
    simp only [t0_apply M, hs]
    grind (splits := 24)
  by_cases hfx : ∃ q : G, M.op q q = q
  · by_cases hid : ∀ q : G, M.op q q = q
    · exact Unary.structuralOnMagma_rproj M t0 (fun a b ↦ (hsop a b).trans (hid b)) s0
    · push Not at hid
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_mix M h hfx hid) s0
  · push Not at hfx
    by_cases hin : ∀ v : G, M.op (M.op v v) (M.op v v) = v
    · exact Unary.structuralOnMagma_pair M t0 (Lf 0) (Lf 0 ⋆ Lf 1) hsop
        (t0_inv M h hfx hin) s0
    · push Not at hin
      exact Unary.structuralOnMagma_img M t0 (Lf 0 ⋆ Lf 1) hsop
        (t0_deep M h hfx hin) s0

end Law.MagmaLaw
