import equational_theories.Spectrum.Basic
import equational_theories.Spectrum.Definability
import equational_theories.Spectrum.Full
import equational_theories.Spectrum.Generated
import equational_theories.Spectrum.Exact
import equational_theories.Spectrum.Transfer
import equational_theories.Spectrum.Catalogue
import equational_theories.Spectrum.AxiomAudit
import equational_theories.Spectrum.BookendCardinality
import equational_theories.Spectrum.PendingDefinability
import equational_theories.Spectrum.CentralComparisons
import equational_theories.Spectrum.WeakCentralSpectrum
import equational_theories.Spectrum.Equation1483.SharpCoordinates
import equational_theories.Spectrum.Equation1483.RetractionCounterexample
import equational_theories.Spectrum.Equation1483.NoCubicUntwist
import equational_theories.Spectrum.Equation1483.ConstantDefinability
import equational_theories.Spectrum.Equation1483.PermutationDefinability.Companion
import equational_theories.Spectrum.Equation1483.WeakCentralCover
import equational_theories.Spectrum.Equation1483.CentralCover
import equational_theories.Spectrum.Equation1483.PermutationShadow
import equational_theories.Spectrum.Equation1483.CubicBaseSubalgebras
import equational_theories.Spectrum.QuarticSeeds
import equational_theories.Spectrum.WeakCentralIdempotent
import equational_theories.Spectrum.Equation907
import equational_theories.Spectrum.Equation907.OddTail
import equational_theories.Spectrum.Equation907.GroupAffine
import equational_theories.Spectrum.Equation907.PointedCycles
import equational_theories.Spectrum.Equation677.ConstructionLimits
import equational_theories.Spectrum.Equation677.EffectiveBounds
import equational_theories.Spectrum.Equation1083_1286.EffectiveBounds
import equational_theories.Spectrum.Equation1083_1286.BinaryHalves
import equational_theories.Spectrum.Equation63.OrderTen.Separation
import equational_theories.Spectrum.SmallPairs.Separation
import equational_theories.Spectrum.Equation467Translations
import equational_theories.Spectrum.Equation467.OrderSixteen.Separation
import equational_theories.Spectrum.FiniteSearch.FirstUse
import equational_theories.Spectrum.Equation467Counting
import equational_theories.Spectrum.Equation467AffineSixteen
import equational_theories.Spectrum.Equation667SimpleTwelve
import equational_theories.Spectrum.Equation667Twelve.Separation
import equational_theories.Spectrum.Equation667SimpleFifteen
import equational_theories.Spectrum.Equation667TwentyFourRestrictions
import equational_theories.Spectrum.Equation667CommutativeFifteen.Certificate
import equational_theories.Spectrum.Equation667IdempotentFifteen.Certificate
import equational_theories.Spectrum.Equation667AutomorphismTwist
import equational_theories.Spectrum.Equation667BinaryFive
import equational_theories.Spectrum.Equation667BinaryFiveClassification
import equational_theories.Spectrum.Equation667BinaryFiveAutomorphisms
import equational_theories.Spectrum.Equation667BinaryDesignCount
import equational_theories.Spectrum.Equation667BinaryDesignExistence
import equational_theories.Spectrum.Equation667GroupMendelsohn
import equational_theories.Spectrum.Equation667LatinTriangles
import equational_theories.Spectrum.Equation667Frobenius21
import equational_theories.Spectrum.Equation667AffineDecomposition
import equational_theories.Spectrum.Equation667AffineThree
import equational_theories.Spectrum.Equation667AffineCyclic
import equational_theories.Spectrum.Equation667AffineUniversal
import equational_theories.Spectrum.Equation667MedialAffine
import equational_theories.Spectrum.Equation667SubmagmaBound
import equational_theories.Spectrum.Equation667RegularParity
import equational_theories.Spectrum.Equation667Subclasses
import equational_theories.Spectrum.Equation667NonclosedIdempotents
import equational_theories.Spectrum.Equation667RetractCounterexample
import equational_theories.Spectrum.Equation667IdempotentTwelve.Certificate
import equational_theories.Spectrum.Equation667IdempotentThirteen
import equational_theories.Spectrum.Equation667RightIdentityTwelve.Certificate
import equational_theories.Spectrum.Equation667Quotients
import equational_theories.Spectrum.Equation667FiberThree

/-!
Finite spectra for the original 4694 equations. See `docs/spectrum_status.md` for
coverage, conventions, theorem names, explicit proof gaps, and genuinely UNKNOWN
exact spectra. The complete PDF catalogue includes named `sorry` obligations;
import the individual constructive modules for a sorry-free dependency graph.
-/
