import equational_theories.Spectrum.Basic
import equational_theories.Spectrum.Definability
import equational_theories.Spectrum.Full
import equational_theories.Spectrum.Generated
import equational_theories.Spectrum.Exact
import equational_theories.Spectrum.Transfer
import equational_theories.Spectrum.Catalogue
import equational_theories.Spectrum.AxiomAudit
import equational_theories.Spectrum.BookendCardinality
import equational_theories.Spectrum.PendingDefinability
import equational_theories.Spectrum.CentralComparisons
import equational_theories.Spectrum.WeakCentralSpectrum
import equational_theories.Spectrum.Equation1483.SharpCoordinates
import equational_theories.Spectrum.Equation1483.RetractionCounterexample
import equational_theories.Spectrum.Equation1483.NoCubicUntwist
import equational_theories.Spectrum.Equation1483.ConstantDefinability
import equational_theories.Spectrum.Equation1483.PermutationDefinability.Companion
import equational_theories.Spectrum.Equation1483.WeakCentralCover
import equational_theories.Spectrum.Equation1483.CentralCover
import equational_theories.Spectrum.Equation1483.PermutationShadow
import equational_theories.Spectrum.Equation1483.CubicBaseSubalgebras
import equational_theories.Spectrum.QuarticSeeds
import equational_theories.Spectrum.WeakCentralIdempotent
import equational_theories.Spectrum.Equation907
import equational_theories.Spectrum.Equation907.OddTail
import equational_theories.Spectrum.Equation907.GroupAffine
import equational_theories.Spectrum.Equation907.PointedCycles
import equational_theories.Spectrum.Equation677.ConstructionLimits
import equational_theories.Spectrum.Equation677.EffectiveBounds
import equational_theories.Spectrum.Equation1083_1286.EffectiveBounds

/-!
Finite spectra for the original 4694 equations. See `docs/spectrum_status.md` for
coverage, conventions, theorem names, explicit proof gaps, and genuinely UNKNOWN
exact spectra. The complete PDF catalogue includes named `sorry` obligations;
import the individual constructive modules for a sorry-free dependency graph.
-/
