#!/usr/bin/env python3
"""Generate and audit compact, Lean-checked E467 order-sixteen certificates.

Requires CaDiCaL with LRAT output and a C++ compiler only for --generate.
Ordinary Lean builds reconstruct and check saved RUP data without a solver. See
scripts/spectrum_467_sixteen_data.py for the finite normalization data.
"""
import sys,json,subprocess,time,gzip,hashlib,shutil
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
sys.path.insert(0,'scripts')
from spectrum_467_square_search import clauses,full_first_use_clauses
from spectrum_467_1516_search import first_use_clauses
from spectrum_467_sixteen_data import ROOT as root, axes, fixed, full, records
import argparse
work=root/'.cache/e467-sixteen-certificates';work.mkdir(parents=True,exist_ok=True)
out=root/'data/spectrum/467_sixteen_rup';out.mkdir(exist_ok=True)
data=dict(axes=axes,fixed=fixed,full=full)

def make_base(r):
 i=r['case'];d=data['axes'][i] if i<50 else list(range(16))
 cs=clauses(d,first_use=i<50)
 if data['full'][i]:cs+=full_first_use_clauses(16,data['fixed'][i])
 if i>=50:
  cs+=[[1+y*16+z] for y,z in enumerate(data['axes'][i])]
  cs+=first_use_clauses(16,r['shape'])
 if r['return_point']>=0:cs.append([1+d.index(0)*16+r['return_point']])
 return (f'p cnf 4096 {len(cs)}\n'+''.join(' '.join(map(str,c))+' 0\n' for c in cs)).encode()

def make(r):
 raw = make_base(r)
 if not r.get('rotation',False):
  return raw
 i=r['case'];k=data['fixed'][i];off=0 if i<50 else 1;length=k-off
 p=lambda x,y,z:1+(x*16+y)*16+z
 x,y=(0,3) if i<50 else (1,0)
 lines=raw.decode().splitlines()[1:]
 for shift in range(1,length):
  e=[off+(j-off+shift)%length if off<=j<k else j for j in range(16)]
  inv=[e.index(j) for j in range(16)]
  for a in range(16):
   for b in range(16):
    if a>e[b]:lines.append(f'{-p(x,y,a)} {-p(inv[x],inv[y],b)} 0')
 return (f'p cnf 4096 {len(lines)}\n'+'\n'.join(lines)+'\n').encode()

def job(pair):
 index,r=pair;tag=f'{index:03d}';meta=out/f'{tag}.json'
 if meta.exists():return json.loads(meta.read_text())
 r=dict(r,rotation=index not in (0,20,30))
 raw=make(r);base=work/tag;base.with_suffix('.cnf').write_bytes(raw)
 proof=base.with_suffix('.lrat');start=time.monotonic()
 with base.with_suffix('.log').open('w') as f:
  proc=subprocess.run([SOLVER,'--quiet','--lrat','-t','600',str(base.with_suffix('.cnf')),str(proof)],stdout=f,stderr=f)
 record=dict(r,index=index,cnf_sha256=hashlib.sha256(raw).hexdigest(),status={20:'UNSAT',10:'SAT',0:'TIMEOUT'}.get(proc.returncode,'ERROR'),solver_seconds=time.monotonic()-start)
 if proc.returncode==20:
  subprocess.run([str(work/'check'),str(base)],check=True)
  binary=base.with_suffix('.trimmed.lrat').read_bytes()
  subprocess.run([str(work/'pack'),str(base.with_suffix('.rup'))],input=binary,check=True)
  payload=base.with_suffix('.rup').read_bytes();packed=gzip.compress(payload,mtime=0)
  dest=out/f'{tag}.rup.gz';dest.write_bytes(packed)
  record.update(format='compact RUP v1',file=str(dest.relative_to(root)),proof_sha256=hashlib.sha256(payload).hexdigest(),gzip_sha256=hashlib.sha256(packed).hexdigest(),expanded_bytes=len(payload),gzip_bytes=len(packed),source_lrat_bytes=len(binary),source_lrat_sha256=hashlib.sha256(binary).hexdigest())
  for suffix in ('.lrat','.trimmed.lrat','.cnf','.rup'):base.with_suffix(suffix).unlink()
  meta.write_text(json.dumps(record,indent=2)+'\n')
 else:proof.unlink(missing_ok=True)
 print(json.dumps(record),flush=True)
 return record

def write_lean():
    lean = root/'equational_theories/Spectrum/Equation467/OrderSixteen'
    (lean/'Certificates').mkdir(exist_ok=True)
    missing = [i for i in range(len(records)) if not (out/f'{i:03d}.json').exists()]
    if missing:
        raise RuntimeError(f'Cannot generate a partial certificate cover; missing indices: {missing}')
    flags = [json.loads((out/f'{i:03d}.json').read_text()).get('rotation',False) if (out/f'{i:03d}.json').exists() else False for i in range(len(records))]
    options = 'import equational_theories.Spectrum.Equation467.OrderSixteen.RotatedEncoding\n\nnamespace Spectrum.E467.OrderSixteen\ndef useRotation (r : Ref) : Bool := #[%s][r.val]!\nend Spectrum.E467.OrderSixteen\n' % ','.join(str(v).lower() for v in flags)
    (lean/'CertificateOptions.lean').write_text(options)
    sources = {}
    for index, r in enumerate(records):
        meta = out/f'{index:03d}.json'
        if not meta.exists():
            continue
        r = json.loads(meta.read_text())
        assert r['status'] == 'UNSAT'
        files = [r['file']]
        payload = ' ++\n    '.join('(include_binary_gzip "../../../../../'+f+'")' for f in files)
        source = f'''import equational_theories.Spectrum.Equation467.OrderSixteen.CertificateOptions
import SpectrumCertificateData
import SpectrumCertificateData.Replay

/- Generated by scripts/spectrum_467_sixteen_certificate.py.
CNF SHA-256: {r['cnf_sha256']}
Compact RUP SHA-256: {r['proof_sha256']}
Lean reconstructs the omitted propagation hints, then checks every inference
with its verified LRAT checker under spectrum_native. No solver runs at build time. -/
namespace Spectrum.E467.OrderSixteen.Certificates.C{index:03d}
open Std.Sat Std.Tactic.BVDecide LRAT Spectrum.CertificateData

private def refutation : Array IntAction :=
  CompactRup.reconstruct ({payload}) (Encoding.natOptimized useRotation {index})

@[spectrum_native]
theorem checked : check refutation (Encoding.natOptimized useRotation {index}) = true := by
  native_decide

theorem unsat : (Encoding.natOptimized useRotation {index}).Unsat := check_sound refutation _ checked

spectrum_assert unsat complete
end Spectrum.E467.OrderSixteen.Certificates.C{index:03d}
'''
        sources[index] = source
    # Balance the large checks across modules, rather than putting six large
    # neighboring cases in one serial build job. Keep the four-case final
    # idempotent batch stable.
    batch_count = 19
    groups = [[] for _ in range(18)] + [list(range(108,112))]
    weights = [0]*18
    sizes = {i:json.loads((out/f'{i:03d}.json').read_text())['expanded_bytes'] for i in sources}
    saved_batches = {i:json.loads((out/f'{i:03d}.json').read_text()).get('batch') for i in sources}
    if all(isinstance(b,int) for b in saved_batches.values()):
        # Keep an established assignment stable when replacing one proof;
        # otherwise a small size change can invalidate every batch's cache.
        groups = [[i for i in sources if saved_batches[i] == b] for b in range(19)]
        assert sorted(i for group in groups for i in group) == list(range(112))
        assert all(len(group) <= 6 for group in groups)
    else:
        for i in sorted(range(108),key=lambda i:-sizes.get(i,0)):
            batch = min((b for b in range(18) if len(groups[b])<6),key=lambda b:(weights[b],b))
            groups[batch].append(i)
            weights[batch] += max(100_000,sizes.get(i,0))
    for batch, indices in enumerate(groups):
        indices.sort()
        if not all(i in sources for i in indices):
            continue
        header = '\n'.join(sources[indices[0]].splitlines()[:3])+'\n'
        body = '\n'.join('\n'.join(sources[i].splitlines()[3:]) for i in indices)+'\n'
        path = lean/'Certificates'/f'Batch{batch:02d}.lean'
        if not path.exists() or path.read_text() != header+body:
            path.write_text(header+body)
    for path in (lean/'Certificates').glob('C*.lean'):
        path.unlink()
    imports = 'import Mathlib.Tactic.FinCases\n' + ''.join(f'import equational_theories.Spectrum.Equation467.OrderSixteen.Certificates.Batch{i:02d}\n' for i in range(batch_count))
    proofs = '\n'.join(f'  · exact Certificates.C{i:03d}.unsat' for i in range(len(records)))
    (lean/'Certificates.lean').write_text(imports+f'''
namespace Spectrum.E467.OrderSixteen
/-- All canonical cases, including all sixteen return values in each long-cycle case. -/
theorem all_unsat (r : Ref) : (Encoding.natOptimized useRotation r).Unsat := by
  fin_cases r
{proofs}
spectrum_assert all_unsat complete
end Spectrum.E467.OrderSixteen
''')

    if len(sources) == len(records):
        saved = [json.loads((out/f'{i:03d}.json').read_text()) for i in range(len(records))]
        manifest = dict(
            law=467, order=16, result='NO_MODEL',
            lean_theorem='Spectrum.not_order_467_16',
            separation_theorem='Spectrum.spectrum_467_ne_1516',
            finite_fo_obstruction='Equation467_not_definableFromFin_Equation1516',
            canonical_square_types=50, idempotent_row_types=17,
            refutation_count=len(saved),
            compressed_bytes=sum(r['gzip_bytes'] for r in saved),
            compact_payload_bytes=sum(r['expanded_bytes'] for r in saved),
            previous_compressed_bytes=1734568959,
            format='compact RUP v1; ordinary gzip, no Git LFS',
            reconstruction='Spectrum.CertificateData.CompactRup.reconstruct',
            coverage_theorem='Spectrum.E467.OrderSixteen.exists_case',
            normalization_theorem='Spectrum.E467.OrderSixteen.exists_minimal',
            soundness_theorem='Spectrum.E467.OrderSixteen.Encoding.model_optimized',
            checker='Std.Tactic.BVDecide.LRAT.check',
            trust_policy='spectrum_native; each theorem has a spectrum_assert complete audit',
            cases=[dict(index=i, case=r['case'], shape=r['shape'], return_point=r['return_point'],
                        metadata=f'data/spectrum/467_sixteen_rup/{i:03d}.json', rotation=r.get('rotation',False),
                        lean_theorem=f'Spectrum.E467.OrderSixteen.Certificates.C{i:03d}.unsat')
                   for i,r in enumerate(saved)])
        (root/'data/spectrum/467_order16_refutations.json').write_text(json.dumps(manifest,indent=2)+'\n')

def audit_compact(payload):
    """Check stream boundaries and clause IDs before the expensive Lean replay."""
    pos = 0

    def word():
        nonlocal pos
        value = 0
        for shift in range(0,70,7):
            assert pos < len(payload), 'Truncated compact integer'
            byte = payload[pos]
            pos += 1
            value |= (byte & 127) << shift
            if byte < 128:
                return value
        raise AssertionError('Oversized compact integer')

    initial = word()
    assert initial > 0 and initial % 2 == 0
    initial //= 2
    count = 0
    while pos < len(payload):
        tag = payload[pos]
        pos += 1
        if tag == ord('a'):
            back = word()
            assert back <= min(count,256), 'Invalid clause-history reference'
            if back:
                word()  # Keep-mask; Lean checks the reconstructed clause.
            while word():
                pass
            count += 1
        elif tag == ord('d'):
            clause = 0
            while (delta := word()):
                clause += delta-1
                assert clause < initial+count, 'No-op deletion must be omitted by the packer'
        else:
            raise AssertionError(f'Invalid compact record tag: {tag}')
    assert count > 0

def audit():
    for index, expected in enumerate(records):
        r = json.loads((out/f'{index:03d}.json').read_text())
        assert all(r[k] == (list(v) if isinstance(v,tuple) else v) for k,v in expected.items()), index
        assert r['status'] == 'UNSAT', index
        assert isinstance(r.get('rotation',False),bool), index
        assert hashlib.sha256(make(r)).hexdigest() == r['cnf_sha256'], index
        chunks = r.get('chunks',[r])
        payloads = []
        for chunk in chunks:
            packed = (root/chunk['file']).read_bytes()
            assert hashlib.sha256(packed).hexdigest() == chunk['gzip_sha256'], index
            assert len(packed) == chunk['gzip_bytes'], index
            assert len(packed) < 100_000_000, index
            payloads.append(gzip.decompress(packed))
        payload = b''.join(payloads)
        assert r['format'] == 'compact RUP v1' and payload, index
        assert len(payload) == r['expanded_bytes'], index
        assert hashlib.sha256(payload).hexdigest() == r['proof_sha256'], index
        audit_compact(payload)
    print(f'Audited {len(records)} saved compact RUP certificates and their exact CNFs.')

def audit_lean_cnf():
    subprocess.run(['lake','build','equational_theories.Spectrum.Equation467.OrderSixteen.CertificateOptions'],check=True)
    result = subprocess.run(['lake','env','lean','--run',str(root/'scripts/templates/Spectrum467SixteenExport.lean'),str(work/'export.cnf')],check=True,text=True,capture_output=True)
    lines = result.stdout.splitlines()
    assert len(lines) == len(records), result.stdout
    for index, line in enumerate(lines):
        fields = line.split()
        assert int(fields[0]) == index
        r = json.loads((out/f'{index:03d}.json').read_text())
        assert fields[1] == r['cnf_sha256'], index
    print(f'All {len(records)} Lean-generated CNFs match the saved certificate inputs byte for byte.')

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generate',action='store_true',help='Run CaDiCaL, trim/check LRAT, save compressed certificates; cached successes are reused.')
    parser.add_argument('--write-lean',action='store_true',help='Regenerate certificate wrappers from saved metadata.')
    parser.add_argument('--audit',action='store_true',help='Recompute all CNFs and verify saved hashes (Lean validates the proof contents).')
    parser.add_argument('--audit-lean-cnf',action='store_true',help='Export all formulas from Lean and compare their DIMACS hashes (several minutes).')
    parser.add_argument('--solver',default='cadical',help='CaDiCaL executable; version 3.0.1 was used for the optimized runs.')
    args=parser.parse_args()
    SOLVER=args.solver
    if args.generate:
        helper=work/'Check.lean'
        helper.write_text((root/'scripts/templates/SpectrumResearchLRAT.lean').read_text().replace('trimmed false','trimmed true'))
        subprocess.run(['lake','env','lean','-c',str(work/'Check.c'),str(helper)],check=True)
        subprocess.run(['lake','env','leanc','-O3','-o',str(work/'check'),str(work/'Check.c')],check=True)
        subprocess.run(['c++','-O3','-std=c++17',str(root/'scripts/spectrum_compact_rup.cpp'),'-o',str(work/'pack')],check=True)
        with ThreadPoolExecutor(max_workers=2) as pool:
            results=list(pool.map(job,enumerate(records)))
        (work/'summary.json').write_text(json.dumps(results,indent=2)+'\n')
        if any(r['status'] != 'UNSAT' for r in results):
            raise SystemExit('Some searches did not finish with refutations; see the generation summary. Cached successes were retained.')
    if args.audit:
        audit()
    if args.write_lean:
        write_lean()

    if args.audit_lean_cnf:
        audit_lean_cnf()
